/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CGeoDataSetAarray {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CGeoDataSetAarray(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CGeoDataSetAarray obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CGeoDataSetAarray(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public CGeoDataSetAarray() {
		this(elecchartcoreJNI.new_CGeoDataSetAarray(), true);
	}

	public void addGeoDataSetDirectly(CVCFGeoDataSet arg0) {
		elecchartcoreJNI.CGeoDataSetAarray_addGeoDataSetDirectly(swigCPtr,
				this, CVCFGeoDataSet.getCPtr(arg0), arg0);
	}

	public int getGeoDataSetNums() {
		return elecchartcoreJNI.CGeoDataSetAarray_getGeoDataSetNums(swigCPtr,
				this);
	}

	public CVCFGeoDataSet getGeoDataSet(int i) {
		long cPtr = elecchartcoreJNI.CGeoDataSetAarray_getGeoDataSet__SWIG_0(
				swigCPtr, this, i);
		return (cPtr == 0) ? null : new CVCFGeoDataSet(cPtr, false);
	}

	public void clearGeoDataSet() {
		elecchartcoreJNI.CGeoDataSetAarray_clearGeoDataSet(swigCPtr, this);
	}

	public void sort(int nSort) {
		elecchartcoreJNI.CGeoDataSetAarray_sort(swigCPtr, this, nSort);
	}

	public void erase(int i) {
		elecchartcoreJNI.CGeoDataSetAarray_erase(swigCPtr, this, i);
	}

}
