/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CGeo2DPoint {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CGeo2DPoint(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CGeo2DPoint obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CGeo2DPoint(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public CGeo2DPoint() {
		this(elecchartcoreJNI.new_CGeo2DPoint(), true);
	}

	public void setM_x(double value) {
		elecchartcoreJNI.CGeo2DPoint_m_x_set(swigCPtr, this, value);
	}

	public double getM_x() {
		return elecchartcoreJNI.CGeo2DPoint_m_x_get(swigCPtr, this);
	}

	public void setM_y(double value) {
		elecchartcoreJNI.CGeo2DPoint_m_y_set(swigCPtr, this, value);
	}

	public double getM_y() {
		return elecchartcoreJNI.CGeo2DPoint_m_y_get(swigCPtr, this);
	}

}
