/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CGeoDataSetDesrArray {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CGeoDataSetDesrArray(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CGeoDataSetDesrArray obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CGeoDataSetDesrArray(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public CGeoDataSetDesrArray() {
		this(elecchartcoreJNI.new_CGeoDataSetDesrArray(), true);
	}

	public void addGeoDataSetDescrDirectly(stVCFGEODATASETDESCR arg0) {
		elecchartcoreJNI.CGeoDataSetDesrArray_addGeoDataSetDescrDirectly(
				swigCPtr, this, stVCFGEODATASETDESCR.getCPtr(arg0), arg0);
	}

	public int getGeoDataSetDescrNums() {
		return elecchartcoreJNI.CGeoDataSetDesrArray_getGeoDataSetDescrNums(
				swigCPtr, this);
	}

	public stVCFGEODATASETDESCR getGeoDataSetDescr(int i) {
		long cPtr = elecchartcoreJNI
				.CGeoDataSetDesrArray_getGeoDataSetDescr__SWIG_0(swigCPtr,
						this, i);
		return (cPtr == 0) ? null : new stVCFGEODATASETDESCR(cPtr, false);
	}

	public void clearGeoDataSetDescr() {
		elecchartcoreJNI.CGeoDataSetDesrArray_clearGeoDataSetDescr(swigCPtr,
				this);
	}

	public int size() {
		return elecchartcoreJNI.CGeoDataSetDesrArray_size(swigCPtr, this);
	}

	public void clear() {
		elecchartcoreJNI.CGeoDataSetDesrArray_clear(swigCPtr, this);
	}

	public void sort(int nSort) {
		elecchartcoreJNI.CGeoDataSetDesrArray_sort(swigCPtr, this, nSort);
	}

}
