/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class Chars {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected Chars(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(Chars obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_Chars(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public Chars() {
		this(elecchartcoreJNI.new_Chars__SWIG_0(), true);
	}

	public Chars(int n) {
		this(elecchartcoreJNI.new_Chars__SWIG_1(n), true);
	}

	public void recount(int n) {
		elecchartcoreJNI.Chars_recount(swigCPtr, this, n);
	}

	public void clear() {
		elecchartcoreJNI.Chars_clear(swigCPtr, this);
	}

	public int size() {
		return elecchartcoreJNI.Chars_size(swigCPtr, this);
	}

	public int count() {
		return elecchartcoreJNI.Chars_count(swigCPtr, this);
	}

	public char get(int index) {
		return elecchartcoreJNI.Chars_get(swigCPtr, this, index);
	}

	public char gethead() {
		return elecchartcoreJNI.Chars_gethead(swigCPtr, this);
	}

	public char gettail() {
		return elecchartcoreJNI.Chars_gettail(swigCPtr, this);
	}

	public void set(int index, char value) {
		elecchartcoreJNI.Chars_set(swigCPtr, this, index, value);
	}

	public void setNoSize(int index, char value) {
		elecchartcoreJNI.Chars_setNoSize(swigCPtr, this, index, value);
	}

	public void add(char value) {
		elecchartcoreJNI.Chars_add(swigCPtr, this, value);
	}

}
