/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CHfAISProtocol {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CHfAISProtocol(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CHfAISProtocol obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CHfAISProtocol(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public CHfAISProtocol() {
		this(elecchartcoreJNI.new_CHfAISProtocol(), true);
	}

	public boolean AISStdProtocolPackDecode(String bytes, int nLen) {
		return elecchartcoreJNI.CHfAISProtocol_AISStdProtocolPackDecode(
				swigCPtr, this, bytes, nLen);
	}

	public int GetRcvTelegramType() {
		return elecchartcoreJNI.CHfAISProtocol_GetRcvTelegramType(swigCPtr,
				this);
	}

	public boolean GetVDMMSG01Info(stBODY_UAIS_MESSAGE_01 stMsg01) {
		return elecchartcoreJNI.CHfAISProtocol_GetVDMMSG01Info(swigCPtr, this,
				stBODY_UAIS_MESSAGE_01.getCPtr(stMsg01), stMsg01);
	}

	public boolean GetVDMMSG05Info(stBODY_UAIS_MESSAGE_05 stMsg05) {
		return elecchartcoreJNI.CHfAISProtocol_GetVDMMSG05Info(swigCPtr, this,
				stBODY_UAIS_MESSAGE_05.getCPtr(stMsg05), stMsg05);
	}

	public boolean GetVDMMSG18Info(stBODY_UAIS_MESSAGE_18 stMsg18) {
		return elecchartcoreJNI.CHfAISProtocol_GetVDMMSG18Info(swigCPtr, this,
				stBODY_UAIS_MESSAGE_18.getCPtr(stMsg18), stMsg18);
	}

	public boolean GetVDMMSG19Info(stBODY_UAIS_MESSAGE_19 stMsg19) {
		return elecchartcoreJNI.CHfAISProtocol_GetVDMMSG19Info(swigCPtr, this,
				stBODY_UAIS_MESSAGE_19.getCPtr(stMsg19), stMsg19);
	}

	public boolean GetVDMMSG21Info(stBODY_UAIS_MESSAGE_21 stMsg21) {
		return elecchartcoreJNI.CHfAISProtocol_GetVDMMSG21Info(swigCPtr, this,
				stBODY_UAIS_MESSAGE_21.getCPtr(stMsg21), stMsg21);
	}

	public boolean GetVDOMSG01Info(stBODY_UAIS_MESSAGE_01 stMsg01) {
		return elecchartcoreJNI.CHfAISProtocol_GetVDOMSG01Info(swigCPtr, this,
				stBODY_UAIS_MESSAGE_01.getCPtr(stMsg01), stMsg01);
	}

	public boolean GetVDOMSG05Info(stBODY_UAIS_MESSAGE_05 stMsg05) {
		return elecchartcoreJNI.CHfAISProtocol_GetVDOMSG05Info(swigCPtr, this,
				stBODY_UAIS_MESSAGE_05.getCPtr(stMsg05), stMsg05);
	}

	public boolean GetVDOMSG18Info(stBODY_UAIS_MESSAGE_18 stMsg18) {
		return elecchartcoreJNI.CHfAISProtocol_GetVDOMSG18Info(swigCPtr, this,
				stBODY_UAIS_MESSAGE_18.getCPtr(stMsg18), stMsg18);
	}

	public boolean GetVDOMSG19Info(stBODY_UAIS_MESSAGE_19 stMsg19) {
		return elecchartcoreJNI.CHfAISProtocol_GetVDOMSG19Info(swigCPtr, this,
				stBODY_UAIS_MESSAGE_19.getCPtr(stMsg19), stMsg19);
	}

	public void setM_stAisDataPack(stAISDATA_PACK value) {
		elecchartcoreJNI.CHfAISProtocol_m_stAisDataPack_set(swigCPtr, this,
				stAISDATA_PACK.getCPtr(value), value);
	}

	public stAISDATA_PACK getM_stAisDataPack() {
		long cPtr = elecchartcoreJNI.CHfAISProtocol_m_stAisDataPack_get(
				swigCPtr, this);
		return (cPtr == 0) ? null : new stAISDATA_PACK(cPtr, false);
	}

	public void setM_emTelemType(int value) {
		elecchartcoreJNI
				.CHfAISProtocol_m_emTelemType_set(swigCPtr, this, value);
	}

	public int getM_emTelemType() {
		return elecchartcoreJNI
				.CHfAISProtocol_m_emTelemType_get(swigCPtr, this);
	}

}
