/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CHfGPSProtocol {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CHfGPSProtocol(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CHfGPSProtocol obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CHfGPSProtocol(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public CHfGPSProtocol() {
		this(elecchartcoreJNI.new_CHfGPSProtocol(), true);
	}

	public boolean GPSStdProtocolPackDecode(String bytes, int nLen) {
		return elecchartcoreJNI.CHfGPSProtocol_GPSStdProtocolPackDecode(
				swigCPtr, this, bytes, nLen);
	}

	public boolean GPSSlfProtocolPackDecode(String bytes, int nLen) {
		return elecchartcoreJNI.CHfGPSProtocol_GPSSlfProtocolPackDecode(
				swigCPtr, this, bytes, nLen);
	}

	public boolean GetGGAInfo(stBODY_NEMA_GPGGA stGGA) {
		return elecchartcoreJNI.CHfGPSProtocol_GetGGAInfo(swigCPtr, this,
				stBODY_NEMA_GPGGA.getCPtr(stGGA), stGGA);
	}

	public boolean GetRMCInfo(stBODY_NEMA_GPRMC stRMC) {
		return elecchartcoreJNI.CHfGPSProtocol_GetRMCInfo(swigCPtr, this,
				stBODY_NEMA_GPRMC.getCPtr(stRMC), stRMC);
	}

	public void setM_stGpsDataPack(stGPSDATA_PACK value) {
		elecchartcoreJNI.CHfGPSProtocol_m_stGpsDataPack_set(swigCPtr, this,
				stGPSDATA_PACK.getCPtr(value), value);
	}

	public stGPSDATA_PACK getM_stGpsDataPack() {
		long cPtr = elecchartcoreJNI.CHfGPSProtocol_m_stGpsDataPack_get(
				swigCPtr, this);
		return (cPtr == 0) ? null : new stGPSDATA_PACK(cPtr, false);
	}

}
