/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CHfGeoProjection {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CHfGeoProjection(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CHfGeoProjection obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CHfGeoProjection(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public CHfGeoProjection() {
		this(elecchartcoreJNI.new_CHfGeoProjection(), true);
	}

	public void GeoCoordTransferPlaneCoord(stCHARTGEOPARAMETER stChartGeoParam,
			double dLong, double dLat, SWIGTYPE_p_long lX, SWIGTYPE_p_long lY) {
		elecchartcoreJNI.CHfGeoProjection_GeoCoordTransferPlaneCoord__SWIG_0(
				swigCPtr, this, stCHARTGEOPARAMETER.getCPtr(stChartGeoParam),
				stChartGeoParam, dLong, dLat, SWIGTYPE_p_long.getCPtr(lX),
				SWIGTYPE_p_long.getCPtr(lY));
	}

	public void GeoCoordTransferPlaneCoord(double dLong, double dLat,
			SWIGTYPE_p_long lX, SWIGTYPE_p_long lY) {
		elecchartcoreJNI.CHfGeoProjection_GeoCoordTransferPlaneCoord__SWIG_1(
				swigCPtr, this, dLong, dLat, SWIGTYPE_p_long.getCPtr(lX),
				SWIGTYPE_p_long.getCPtr(lY));
	}

	public void PlaneCoordTransferGeoCoord(stCHARTGEOPARAMETER stChartGeoParam,
			int lX, int lY, SWIGTYPE_p_double dLong, SWIGTYPE_p_double dLat) {
		elecchartcoreJNI.CHfGeoProjection_PlaneCoordTransferGeoCoord__SWIG_0(
				swigCPtr, this, stCHARTGEOPARAMETER.getCPtr(stChartGeoParam),
				stChartGeoParam, lX, lY, SWIGTYPE_p_double.getCPtr(dLong),
				SWIGTYPE_p_double.getCPtr(dLat));
	}

	public void PlaneCoordTransferGeoCoord(int lX, int lY,
			SWIGTYPE_p_double dLong, SWIGTYPE_p_double dLat) {
		elecchartcoreJNI.CHfGeoProjection_PlaneCoordTransferGeoCoord__SWIG_1(
				swigCPtr, this, lX, lY, SWIGTYPE_p_double.getCPtr(dLong),
				SWIGTYPE_p_double.getCPtr(dLat));
	}

	public void getChartTableRect(stCHARTGEOPARAMETER stChartGeoParam,
			stCHARTPLANPARAMETER stChartPlanParam) {
		elecchartcoreJNI.CHfGeoProjection_getChartTableRect__SWIG_0(swigCPtr,
				this, stCHARTGEOPARAMETER.getCPtr(stChartGeoParam),
				stChartGeoParam,
				stCHARTPLANPARAMETER.getCPtr(stChartPlanParam),
				stChartPlanParam);
	}

	public void getChartTableRect(stCHARTPLANPARAMETER stChartPlanParam) {
		elecchartcoreJNI.CHfGeoProjection_getChartTableRect__SWIG_1(swigCPtr,
				this, stCHARTPLANPARAMETER.getCPtr(stChartPlanParam),
				stChartPlanParam);
	}

	public void SetChartGeoExtenParam(stCHARTGEOPARAMETER stGeoExten) {
		elecchartcoreJNI.CHfGeoProjection_SetChartGeoExtenParam(swigCPtr, this,
				stCHARTGEOPARAMETER.getCPtr(stGeoExten), stGeoExten);
	}

	public void GetChartGeoExtenParam(stCHARTGEOPARAMETER stGeoExten) {
		elecchartcoreJNI.CHfGeoProjection_GetChartGeoExtenParam(swigCPtr, this,
				stCHARTGEOPARAMETER.getCPtr(stGeoExten), stGeoExten);
	}

	public void getGeoPointLongLat(double dLat0, double dLong0, double dScale0,
			double dHoriLen, double dVertLen, SWIGTYPE_p_double dLat1,
			SWIGTYPE_p_double dLong1) {
		elecchartcoreJNI.CHfGeoProjection_getGeoPointLongLat(swigCPtr, this,
				dLat0, dLong0, dScale0, dHoriLen, dVertLen,
				SWIGTYPE_p_double.getCPtr(dLat1),
				SWIGTYPE_p_double.getCPtr(dLong1));
	}

}
