/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CHfHDTProtocol {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CHfHDTProtocol(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CHfHDTProtocol obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CHfHDTProtocol(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public CHfHDTProtocol() {
		this(elecchartcoreJNI.new_CHfHDTProtocol(), true);
	}

	public boolean HDTProtocolPackDecode(String bytes, int nLen) {
		return elecchartcoreJNI.CHfHDTProtocol_HDTProtocolPackDecode(swigCPtr,
				this, bytes, nLen);
	}

	public boolean GetHDTInfo(stBODY_LOGO_HCHDT stHDT) {
		return elecchartcoreJNI.CHfHDTProtocol_GetHDTInfo(swigCPtr, this,
				stBODY_LOGO_HCHDT.getCPtr(stHDT), stHDT);
	}

	public void setM_stHdtDataPack(stBODY_LOGO_HCHDT value) {
		elecchartcoreJNI.CHfHDTProtocol_m_stHdtDataPack_set(swigCPtr, this,
				stBODY_LOGO_HCHDT.getCPtr(value), value);
	}

	public stBODY_LOGO_HCHDT getM_stHdtDataPack() {
		long cPtr = elecchartcoreJNI.CHfHDTProtocol_m_stHdtDataPack_get(
				swigCPtr, this);
		return (cPtr == 0) ? null : new stBODY_LOGO_HCHDT(cPtr, false);
	}

}
