/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CHFLogManage {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CHFLogManage(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CHFLogManage obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CHFLogManage(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public CHFLogManage() {
		this(elecchartcoreJNI.new_CHFLogManage(), true);
	}

	public void WriteLogFile(String pszLog, int nLen) {
		elecchartcoreJNI
				.CHFLogManage_WriteLogFile(swigCPtr, this, pszLog, nLen);
	}

}
