/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CHfSensorDataFlow {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CHfSensorDataFlow(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CHfSensorDataFlow obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CHfSensorDataFlow(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	protected void swigDirectorDisconnect() {
		swigCMemOwn = false;
		delete();
	}

	public void swigReleaseOwnership() {
		swigCMemOwn = false;
		elecchartcoreJNI.CHfSensorDataFlow_change_ownership(this, swigCPtr,
				false);
	}

	public void swigTakeOwnership() {
		swigCMemOwn = true;
		elecchartcoreJNI.CHfSensorDataFlow_change_ownership(this, swigCPtr,
				true);
	}

	public CHfSensorDataFlow() {
		this(elecchartcoreJNI.new_CHfSensorDataFlow(), true);
		elecchartcoreJNI.CHfSensorDataFlow_director_connect(this, swigCPtr,
				swigCMemOwn, true);
	}

	public void GetGpsGPGGAInfo(stBODY_NEMA_GPGGA stGGA) {
		if (getClass() == CHfSensorDataFlow.class)
			elecchartcoreJNI.CHfSensorDataFlow_GetGpsGPGGAInfo(swigCPtr, this,
					stBODY_NEMA_GPGGA.getCPtr(stGGA), stGGA);
		else
			elecchartcoreJNI
					.CHfSensorDataFlow_GetGpsGPGGAInfoSwigExplicitCHfSensorDataFlow(
							swigCPtr, this, stBODY_NEMA_GPGGA.getCPtr(stGGA),
							stGGA);
	}

	public void GetGpsGPRMCInfo(stBODY_NEMA_GPRMC stRMC) {
		if (getClass() == CHfSensorDataFlow.class)
			elecchartcoreJNI.CHfSensorDataFlow_GetGpsGPRMCInfo(swigCPtr, this,
					stBODY_NEMA_GPRMC.getCPtr(stRMC), stRMC);
		else
			elecchartcoreJNI
					.CHfSensorDataFlow_GetGpsGPRMCInfoSwigExplicitCHfSensorDataFlow(
							swigCPtr, this, stBODY_NEMA_GPRMC.getCPtr(stRMC),
							stRMC);
	}

	public void GetAisVDMMSG01Info(stBODY_UAIS_MESSAGE_01 stMsg01) {
		if (getClass() == CHfSensorDataFlow.class)
			elecchartcoreJNI.CHfSensorDataFlow_GetAisVDMMSG01Info(swigCPtr,
					this, stBODY_UAIS_MESSAGE_01.getCPtr(stMsg01), stMsg01);
		else
			elecchartcoreJNI
					.CHfSensorDataFlow_GetAisVDMMSG01InfoSwigExplicitCHfSensorDataFlow(
							swigCPtr, this,
							stBODY_UAIS_MESSAGE_01.getCPtr(stMsg01), stMsg01);
	}

	public void GetAisVDMMSG05Info(stBODY_UAIS_MESSAGE_05 stMsg05) {
		if (getClass() == CHfSensorDataFlow.class)
			elecchartcoreJNI.CHfSensorDataFlow_GetAisVDMMSG05Info(swigCPtr,
					this, stBODY_UAIS_MESSAGE_05.getCPtr(stMsg05), stMsg05);
		else
			elecchartcoreJNI
					.CHfSensorDataFlow_GetAisVDMMSG05InfoSwigExplicitCHfSensorDataFlow(
							swigCPtr, this,
							stBODY_UAIS_MESSAGE_05.getCPtr(stMsg05), stMsg05);
	}

	public void GetAisVDMMSG18Info(stBODY_UAIS_MESSAGE_18 stMsg18) {
		if (getClass() == CHfSensorDataFlow.class)
			elecchartcoreJNI.CHfSensorDataFlow_GetAisVDMMSG18Info(swigCPtr,
					this, stBODY_UAIS_MESSAGE_18.getCPtr(stMsg18), stMsg18);
		else
			elecchartcoreJNI
					.CHfSensorDataFlow_GetAisVDMMSG18InfoSwigExplicitCHfSensorDataFlow(
							swigCPtr, this,
							stBODY_UAIS_MESSAGE_18.getCPtr(stMsg18), stMsg18);
	}

	public void GetAisVDMMSG19Info(stBODY_UAIS_MESSAGE_19 stMsg19) {
		if (getClass() == CHfSensorDataFlow.class)
			elecchartcoreJNI.CHfSensorDataFlow_GetAisVDMMSG19Info(swigCPtr,
					this, stBODY_UAIS_MESSAGE_19.getCPtr(stMsg19), stMsg19);
		else
			elecchartcoreJNI
					.CHfSensorDataFlow_GetAisVDMMSG19InfoSwigExplicitCHfSensorDataFlow(
							swigCPtr, this,
							stBODY_UAIS_MESSAGE_19.getCPtr(stMsg19), stMsg19);
	}

	public void GetAisVDMMSG21Info(stBODY_UAIS_MESSAGE_21 stMsg21) {
		if (getClass() == CHfSensorDataFlow.class)
			elecchartcoreJNI.CHfSensorDataFlow_GetAisVDMMSG21Info(swigCPtr,
					this, stBODY_UAIS_MESSAGE_21.getCPtr(stMsg21), stMsg21);
		else
			elecchartcoreJNI
					.CHfSensorDataFlow_GetAisVDMMSG21InfoSwigExplicitCHfSensorDataFlow(
							swigCPtr, this,
							stBODY_UAIS_MESSAGE_21.getCPtr(stMsg21), stMsg21);
	}

	public void GetAisVDOMSG01Info(stBODY_UAIS_MESSAGE_01 stMsg01) {
		if (getClass() == CHfSensorDataFlow.class)
			elecchartcoreJNI.CHfSensorDataFlow_GetAisVDOMSG01Info(swigCPtr,
					this, stBODY_UAIS_MESSAGE_01.getCPtr(stMsg01), stMsg01);
		else
			elecchartcoreJNI
					.CHfSensorDataFlow_GetAisVDOMSG01InfoSwigExplicitCHfSensorDataFlow(
							swigCPtr, this,
							stBODY_UAIS_MESSAGE_01.getCPtr(stMsg01), stMsg01);
	}

	public void GetAisVDOMSG05Info(stBODY_UAIS_MESSAGE_05 stMsg05) {
		if (getClass() == CHfSensorDataFlow.class)
			elecchartcoreJNI.CHfSensorDataFlow_GetAisVDOMSG05Info(swigCPtr,
					this, stBODY_UAIS_MESSAGE_05.getCPtr(stMsg05), stMsg05);
		else
			elecchartcoreJNI
					.CHfSensorDataFlow_GetAisVDOMSG05InfoSwigExplicitCHfSensorDataFlow(
							swigCPtr, this,
							stBODY_UAIS_MESSAGE_05.getCPtr(stMsg05), stMsg05);
	}

	public void GetAisVDOMSG18Info(stBODY_UAIS_MESSAGE_18 stMsg18) {
		if (getClass() == CHfSensorDataFlow.class)
			elecchartcoreJNI.CHfSensorDataFlow_GetAisVDOMSG18Info(swigCPtr,
					this, stBODY_UAIS_MESSAGE_18.getCPtr(stMsg18), stMsg18);
		else
			elecchartcoreJNI
					.CHfSensorDataFlow_GetAisVDOMSG18InfoSwigExplicitCHfSensorDataFlow(
							swigCPtr, this,
							stBODY_UAIS_MESSAGE_18.getCPtr(stMsg18), stMsg18);
	}

	public void GetAisVDOMSG19Info(stBODY_UAIS_MESSAGE_19 stMsg19) {
		if (getClass() == CHfSensorDataFlow.class)
			elecchartcoreJNI.CHfSensorDataFlow_GetAisVDOMSG19Info(swigCPtr,
					this, stBODY_UAIS_MESSAGE_19.getCPtr(stMsg19), stMsg19);
		else
			elecchartcoreJNI
					.CHfSensorDataFlow_GetAisVDOMSG19InfoSwigExplicitCHfSensorDataFlow(
							swigCPtr, this,
							stBODY_UAIS_MESSAGE_19.getCPtr(stMsg19), stMsg19);
	}

	public void GetHdtHCHDTInfo(stBODY_LOGO_HCHDT stHDT) {
		if (getClass() == CHfSensorDataFlow.class)
			elecchartcoreJNI.CHfSensorDataFlow_GetHdtHCHDTInfo(swigCPtr, this,
					stBODY_LOGO_HCHDT.getCPtr(stHDT), stHDT);
		else
			elecchartcoreJNI
					.CHfSensorDataFlow_GetHdtHCHDTInfoSwigExplicitCHfSensorDataFlow(
							swigCPtr, this, stBODY_LOGO_HCHDT.getCPtr(stHDT),
							stHDT);
	}

	public void GetAISGPRMCInfo(stBODY_NEMA_GPRMC stRMC) {
		if (getClass() == CHfSensorDataFlow.class)
			elecchartcoreJNI.CHfSensorDataFlow_GetAISGPRMCInfo(swigCPtr, this,
					stBODY_NEMA_GPRMC.getCPtr(stRMC), stRMC);
		else
			elecchartcoreJNI
					.CHfSensorDataFlow_GetAISGPRMCInfoSwigExplicitCHfSensorDataFlow(
							swigCPtr, this, stBODY_NEMA_GPRMC.getCPtr(stRMC),
							stRMC);
	}

	public void InitSensorDataFlow(int nSensorType) {
		elecchartcoreJNI.CHfSensorDataFlow_InitSensorDataFlow(swigCPtr, this,
				nSensorType);
	}

	public void SensorRecevDataFlowMsg(String pszData, int nDataLen) {
		elecchartcoreJNI.CHfSensorDataFlow_SensorRecevDataFlowMsg(swigCPtr,
				this, pszData, nDataLen);
	}

	public void PickupProtocolDataPack(String ubytes, int nBuffLen) {
		elecchartcoreJNI.CHfSensorDataFlow_PickupProtocolDataPack__SWIG_0(
				swigCPtr, this, ubytes, nBuffLen);
	}

	public void PickupProtocolDataPack(char ubyte) {
		elecchartcoreJNI.CHfSensorDataFlow_PickupProtocolDataPack__SWIG_1(
				swigCPtr, this, ubyte);
	}

	public void SensorDataFlowDecodMsg(String pszMsgbw, int nLen) {
		elecchartcoreJNI.CHfSensorDataFlow_SensorDataFlowDecodMsg(swigCPtr,
				this, pszMsgbw, nLen);
	}

	public void setM_nSensorType(int value) {
		elecchartcoreJNI.CHfSensorDataFlow_m_nSensorType_set(swigCPtr, this,
				value);
	}

	public int getM_nSensorType() {
		return elecchartcoreJNI.CHfSensorDataFlow_m_nSensorType_get(swigCPtr,
				this);
	}

	public void setM_nTelegramType(int value) {
		elecchartcoreJNI.CHfSensorDataFlow_m_nTelegramType_set(swigCPtr, this,
				value);
	}

	public int getM_nTelegramType() {
		return elecchartcoreJNI.CHfSensorDataFlow_m_nTelegramType_get(swigCPtr,
				this);
	}

}
