/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CHfVCFAreasSymbol extends CHfVCFSymbol {
	private long swigCPtr;

	protected CHfVCFAreasSymbol(long cPtr, boolean cMemoryOwn) {
		super(elecchartcoreJNI.CHfVCFAreasSymbol_SWIGUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CHfVCFAreasSymbol obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CHfVCFAreasSymbol(swigCPtr);
			}
			swigCPtr = 0;
		}
		super.delete();
	}

	public CHfVCFAreasSymbol() {
		this(elecchartcoreJNI.new_CHfVCFAreasSymbol__SWIG_0(), true);
	}

	public CHfVCFAreasSymbol(int nSymId, String pszSymName, int nMetaNums) {
		this(elecchartcoreJNI.new_CHfVCFAreasSymbol__SWIG_1(nSymId, pszSymName,
				nMetaNums), true);
	}

	public void SetSymbolMetaNums(int nSymNums) {
		elecchartcoreJNI.CHfVCFAreasSymbol_SetSymbolMetaNums(swigCPtr, this,
				nSymNums);
	}

	public void Clear() {
		elecchartcoreJNI.CHfVCFAreasSymbol_Clear(swigCPtr, this);
	}

	public void addSymbolMeta(stHFVCFAREAMETASYM stSymMeta) {
		elecchartcoreJNI.CHfVCFAreasSymbol_addSymbolMeta(swigCPtr, this,
				stHFVCFAREAMETASYM.getCPtr(stSymMeta), stSymMeta);
	}

	public void setSymbolMetas(int nNums, stHFVCFAREAMETASYM stSymMeta) {
		elecchartcoreJNI.CHfVCFAreasSymbol_setSymbolMetas(swigCPtr, this,
				nNums, stHFVCFAREAMETASYM.getCPtr(stSymMeta), stSymMeta);
	}

	public int GetSymbolMteaNums() {
		return elecchartcoreJNI.CHfVCFAreasSymbol_GetSymbolMteaNums(swigCPtr,
				this);
	}

	public stHFVCFAREAMETASYM GetSymbolMeta(int nMetaNum) {
		long cPtr = elecchartcoreJNI.CHfVCFAreasSymbol_GetSymbolMeta(swigCPtr,
				this, nMetaNum);
		return (cPtr == 0) ? null : new stHFVCFAREAMETASYM(cPtr, false);
	}

}
