/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CHfVCFPointSymbol extends CHfVCFSymbol {
	private long swigCPtr;

	protected CHfVCFPointSymbol(long cPtr, boolean cMemoryOwn) {
		super(elecchartcoreJNI.CHfVCFPointSymbol_SWIGUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CHfVCFPointSymbol obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CHfVCFPointSymbol(swigCPtr);
			}
			swigCPtr = 0;
		}
		super.delete();
	}

	public CHfVCFPointSymbol() {
		this(elecchartcoreJNI.new_CHfVCFPointSymbol__SWIG_0(), true);
	}

	public CHfVCFPointSymbol(int nSymId, String pszSymName, int nMetaNums) {
		this(elecchartcoreJNI.new_CHfVCFPointSymbol__SWIG_1(nSymId, pszSymName,
				nMetaNums), true);
	}

	public void SetSymbolMetaNums(int nSymNums) {
		elecchartcoreJNI.CHfVCFPointSymbol_SetSymbolMetaNums(swigCPtr, this,
				nSymNums);
	}

	public void Clear() {
		elecchartcoreJNI.CHfVCFPointSymbol_Clear(swigCPtr, this);
	}

	public void addSymbolMeta(stHFVCFPOINTMETASYM stSymMeta) {
		elecchartcoreJNI.CHfVCFPointSymbol_addSymbolMeta(swigCPtr, this,
				stHFVCFPOINTMETASYM.getCPtr(stSymMeta), stSymMeta);
	}

	public void setSymbolMetas(int nNums, stHFVCFPOINTMETASYM stSymMeta) {
		elecchartcoreJNI.CHfVCFPointSymbol_setSymbolMetas(swigCPtr, this,
				nNums, stHFVCFPOINTMETASYM.getCPtr(stSymMeta), stSymMeta);
	}

	public int GetSymbolMteaNums() {
		return elecchartcoreJNI.CHfVCFPointSymbol_GetSymbolMteaNums(swigCPtr,
				this);
	}

	public stHFVCFPOINTMETASYM GetSymbolMeta(int nMetaNum) {
		long cPtr = elecchartcoreJNI.CHfVCFPointSymbol_GetSymbolMeta(swigCPtr,
				this, nMetaNum);
		return (cPtr == 0) ? null : new stHFVCFPOINTMETASYM(cPtr, false);
	}

}
