/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CHfVCFLineSymbol extends CHfVCFSymbol {
	private long swigCPtr;

	protected CHfVCFLineSymbol(long cPtr, boolean cMemoryOwn) {
		super(elecchartcoreJNI.CHfVCFLineSymbol_SWIGUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CHfVCFLineSymbol obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CHfVCFLineSymbol(swigCPtr);
			}
			swigCPtr = 0;
		}
		super.delete();
	}

	public CHfVCFLineSymbol() {
		this(elecchartcoreJNI.new_CHfVCFLineSymbol__SWIG_0(), true);
	}

	public CHfVCFLineSymbol(int nSymId, String pszSymName, int nMetaNums) {
		this(elecchartcoreJNI.new_CHfVCFLineSymbol__SWIG_1(nSymId, pszSymName,
				nMetaNums), true);
	}

	public void SetSymbolMetaNums(int nSymNums) {
		elecchartcoreJNI.CHfVCFLineSymbol_SetSymbolMetaNums(swigCPtr, this,
				nSymNums);
	}

	public void Clear() {
		elecchartcoreJNI.CHfVCFLineSymbol_Clear(swigCPtr, this);
	}

	public void addSymbolMeta(stHFVCFLINEMETASYM stSymMeta) {
		elecchartcoreJNI.CHfVCFLineSymbol_addSymbolMeta(swigCPtr, this,
				stHFVCFLINEMETASYM.getCPtr(stSymMeta), stSymMeta);
	}

	public void setSymbolMetas(int nNums, stHFVCFLINEMETASYM stSymMeta) {
		elecchartcoreJNI.CHfVCFLineSymbol_setSymbolMetas(swigCPtr, this, nNums,
				stHFVCFLINEMETASYM.getCPtr(stSymMeta), stSymMeta);
	}

	public int GetSymbolMteaNums() {
		return elecchartcoreJNI.CHfVCFLineSymbol_GetSymbolMteaNums(swigCPtr,
				this);
	}

	public stHFVCFLINEMETASYM GetSymbolMeta(int nMetaNum) {
		long cPtr = elecchartcoreJNI.CHfVCFLineSymbol_GetSymbolMeta(swigCPtr,
				this, nMetaNum);
		return (cPtr == 0) ? null : new stHFVCFLINEMETASYM(cPtr, false);
	}

}
