/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CHfVCFPresentationLib {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CHfVCFPresentationLib(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CHfVCFPresentationLib obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CHfVCFPresentationLib(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public CHfVCFPresentationLib() {
		this(elecchartcoreJNI.new_CHfVCFPresentationLib(), true);
	}

	public int InitializePresLib(String pszFilePath, int nColorMode,
			int nDisplayMode, int nBkColor) {
		return elecchartcoreJNI
				.CHfVCFPresentationLib_InitializePresLib__SWIG_0(swigCPtr,
						this, pszFilePath, nColorMode, nDisplayMode, nBkColor);
	}

	public int InitializePresLib(String pszFilePath, int nColorMode,
			int nDisplayMode) {
		return elecchartcoreJNI
				.CHfVCFPresentationLib_InitializePresLib__SWIG_1(swigCPtr,
						this, pszFilePath, nColorMode, nDisplayMode);
	}

	public int InitializePresLib(String pszFilePath, int nColorMode) {
		return elecchartcoreJNI
				.CHfVCFPresentationLib_InitializePresLib__SWIG_2(swigCPtr,
						this, pszFilePath, nColorMode);
	}

	public int InitializePresLib(String pszFilePath) {
		return elecchartcoreJNI
				.CHfVCFPresentationLib_InitializePresLib__SWIG_3(swigCPtr,
						this, pszFilePath);
	}

	public void Close() {
		elecchartcoreJNI.CHfVCFPresentationLib_Close(swigCPtr, this);
	}

	public void SetColorMode(int nColorMode) {
		elecchartcoreJNI.CHfVCFPresentationLib_SetColorMode(swigCPtr, this,
				nColorMode);
	}

	public int GetColorMode() {
		return elecchartcoreJNI.CHfVCFPresentationLib_GetColorMode(swigCPtr,
				this);
	}

	public void SetBackColor(int nBkColor) {
		elecchartcoreJNI.CHfVCFPresentationLib_SetBackColor(swigCPtr, this,
				nBkColor);
	}

	public int GetBackColor() {
		return elecchartcoreJNI.CHfVCFPresentationLib_GetBackColor(swigCPtr,
				this);
	}

	public void SetFontColor(int nFtColor) {
		elecchartcoreJNI.CHfVCFPresentationLib_SetFontColor(swigCPtr, this,
				nFtColor);
	}

	public int GetFontColor() {
		return elecchartcoreJNI.CHfVCFPresentationLib_GetFontColor(swigCPtr,
				this);
	}

	public void SetTideColor(int nTdColor) {
		elecchartcoreJNI.CHfVCFPresentationLib_SetTideColor(swigCPtr, this,
				nTdColor);
	}

	public int GetTideColor() {
		return elecchartcoreJNI.CHfVCFPresentationLib_GetTideColor(swigCPtr,
				this);
	}

	public void SetTideHight(double dTideValue) {
		elecchartcoreJNI.CHfVCFPresentationLib_SetTideHight(swigCPtr, this,
				dTideValue);
	}

	public double GetTideHight() {
		return elecchartcoreJNI.CHfVCFPresentationLib_GetTideHight(swigCPtr,
				this);
	}

	public void SetDisplayMode(int nDisplayMode) {
		elecchartcoreJNI.CHfVCFPresentationLib_SetDisplayMode(swigCPtr, this,
				nDisplayMode);
	}

	public int GetDisplayMode() {
		return elecchartcoreJNI.CHfVCFPresentationLib_GetDisplayMode(swigCPtr,
				this);
	}

	public void SetOrieanMode(int nOrieanMode) {
		elecchartcoreJNI.CHfVCFPresentationLib_SetOrieanMode(swigCPtr, this,
				nOrieanMode);
	}

	public int GetOrieanMode() {
		return elecchartcoreJNI.CHfVCFPresentationLib_GetOrieanMode(swigCPtr,
				this);
	}

	public boolean vcfDrawVCFGeoDatabase(CVCFGeoDatabase pGeoDatabase,
			CHfVCFGeoCanvas pGeoCanvas) {
		return elecchartcoreJNI.CHfVCFPresentationLib_vcfDrawVCFGeoDatabase(
				swigCPtr, this, CVCFGeoDatabase.getCPtr(pGeoDatabase),
				pGeoDatabase, CHfVCFGeoCanvas.getCPtr(pGeoCanvas), pGeoCanvas);
	}

}
