/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CHfVCFElectronicChart {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CHfVCFElectronicChart(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CHfVCFElectronicChart obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CHfVCFElectronicChart(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public CHfVCFElectronicChart() {
		this(elecchartcoreJNI.new_CHfVCFElectronicChart__SWIG_0(), true);
	}

	public CHfVCFElectronicChart(CHfVCFGeoCanvas pGeoCanvas) {
		this(elecchartcoreJNI.new_CHfVCFElectronicChart__SWIG_1(
				CHfVCFGeoCanvas.getCPtr(pGeoCanvas), pGeoCanvas), true);
	}

	public void Initialize(String pszGeoDatabasePath, String pszVcfPresLibPath) {
		elecchartcoreJNI.CHfVCFElectronicChart_Initialize(swigCPtr, this,
				pszGeoDatabasePath, pszVcfPresLibPath);
	}

	public void SetMouseCursorResourceIds(SWIGTYPE_p_int nscrResId) {
		elecchartcoreJNI.CHfVCFElectronicChart_SetMouseCursorResourceIds(
				swigCPtr, this, SWIGTYPE_p_int.getCPtr(nscrResId));
	}

	public void Destory() {
		elecchartcoreJNI.CHfVCFElectronicChart_Destory(swigCPtr, this);
	}

	public void SetGeoCanvas(CHfVCFGeoCanvas pGeoCanvas) {
		elecchartcoreJNI.CHfVCFElectronicChart_SetGeoCanvas(swigCPtr, this,
				CHfVCFGeoCanvas.getCPtr(pGeoCanvas), pGeoCanvas);
	}

	public void SetChartScrViewRect(CRect scrRect) {
		elecchartcoreJNI.CHfVCFElectronicChart_SetChartScrViewRect(swigCPtr,
				this, CRect.getCPtr(scrRect), scrRect);
	}

	public void GetChartScrViewRect(CRect scrRect) {
		elecchartcoreJNI.CHfVCFElectronicChart_GetChartScrViewRect(swigCPtr,
				this, CRect.getCPtr(scrRect), scrRect);
	}

	public void ManualSingleSelectChart(String pszChartCode) {
		elecchartcoreJNI.CHfVCFElectronicChart_ManualSingleSelectChart(
				swigCPtr, this, pszChartCode);
	}

	public void ManualManySelectChart(String pszChartCode) {
		elecchartcoreJNI.CHfVCFElectronicChart_ManualManySelectChart(swigCPtr,
				this, pszChartCode);
	}

	public void AutomManySelectChart(double dCenLong, double dCenLat) {
		elecchartcoreJNI.CHfVCFElectronicChart_AutomManySelectChart(swigCPtr,
				this, dCenLong, dCenLat);
	}

	public void CloseVCFChart(String pszChartCode) {
		elecchartcoreJNI.CHfVCFElectronicChart_CloseVCFChart(swigCPtr, this,
				pszChartCode);
	}

	public void SetChartSelectMode(int nMode) {
		elecchartcoreJNI.CHfVCFElectronicChart_SetChartSelectMode(swigCPtr,
				this, nMode);
	}

	public int GetChartSelectMode() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetChartSelectMode(
				swigCPtr, this);
	}

	public void ChartRotate(double dAangle) {
		elecchartcoreJNI.CHfVCFElectronicChart_ChartRotate(swigCPtr, this,
				dAangle);
	}

	public double GetRotateAngle() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetRotateAngle(swigCPtr,
				this);
	}

	public void ChartScaleLevelAdjust(double dScaleLevel) {
		elecchartcoreJNI.CHfVCFElectronicChart_ChartScaleLevelAdjust(swigCPtr,
				this, dScaleLevel);
	}

	public double GetChartDspScaleLevel() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetChartDspScaleLevel(
				swigCPtr, this);
	}

	public double GetChartStdScale() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetChartStdScale(
				swigCPtr, this);
	}

	public double GetChartDspScale() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetChartDspScale(
				swigCPtr, this);
	}

	public void SetChartDspScale(double fDspScale) {
		elecchartcoreJNI.CHfVCFElectronicChart_SetChartDspScale(swigCPtr, this,
				fDspScale);
	}

	public void ChartZoomout() {
		elecchartcoreJNI.CHfVCFElectronicChart_ChartZoomout(swigCPtr, this);
	}

	public void ChartZoomin() {
		elecchartcoreJNI.CHfVCFElectronicChart_ChartZoomin(swigCPtr, this);
	}

	public void ChartScaleReset() {
		elecchartcoreJNI.CHfVCFElectronicChart_ChartScaleReset(swigCPtr, this);
	}

	public void ChartColorMode(int nColorMode) {
		elecchartcoreJNI.CHfVCFElectronicChart_ChartColorMode(swigCPtr, this,
				nColorMode);
	}

	public int GetColorMode() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetColorMode(swigCPtr,
				this);
	}

	public void SetTideHight(double dTideValue) {
		elecchartcoreJNI.CHfVCFElectronicChart_SetTideHight(swigCPtr, this,
				dTideValue);
	}

	public double GetTideHight() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetTideHight(swigCPtr,
				this);
	}

	public void ChartDisplayMode(int nDisplayMode) {
		elecchartcoreJNI.CHfVCFElectronicChart_ChartDisplayMode(swigCPtr, this,
				nDisplayMode);
	}

	public int GetDisplayMode() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetDisplayMode(swigCPtr,
				this);
	}

	public String GetChartCode() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetChartCode(swigCPtr,
				this);
	}

	public void GetMousePointLongLat(stDPOINT stLatLong) {
		elecchartcoreJNI.CHfVCFElectronicChart_GetMousePointLongLat(swigCPtr,
				this, stDPOINT.getCPtr(stLatLong), stLatLong);
	}

	public void ChartCenterShow(double fCenLong, double fCenLat) {
		elecchartcoreJNI.CHfVCFElectronicChart_ChartCenterShow(swigCPtr, this,
				fCenLong, fCenLat);
	}

	public boolean GeoPointIsInChart(double fLong, double fLat) {
		return elecchartcoreJNI.CHfVCFElectronicChart_GeoPointIsInChart(
				swigCPtr, this, fLong, fLat);
	}

	public boolean GeoPointIsInScreen(double fLong, double fLat) {
		return elecchartcoreJNI.CHfVCFElectronicChart_GeoPointIsInScreen(
				swigCPtr, this, fLong, fLat);
	}

	public boolean VoyageAutoSwitchChart(double fLong, double fLat,
			double fCourse) {
		return elecchartcoreJNI.CHfVCFElectronicChart_VoyageAutoSwitchChart(
				swigCPtr, this, fLong, fLat, fCourse);
	}

	public boolean VoyageAutoCenterShow(double fLong, double fLat,
			double fCourse, int nTxHead) {
		return elecchartcoreJNI
				.CHfVCFElectronicChart_VoyageAutoCenterShow__SWIG_0(swigCPtr,
						this, fLong, fLat, fCourse, nTxHead);
	}

	public boolean VoyageAutoCenterShow(double fLong, double fLat,
			double fCourse) {
		return elecchartcoreJNI
				.CHfVCFElectronicChart_VoyageAutoCenterShow__SWIG_1(swigCPtr,
						this, fLong, fLat, fCourse);
	}

	public boolean VoyageManuCenterShow(double fLong, double fLat,
			double fCourse) {
		return elecchartcoreJNI.CHfVCFElectronicChart_VoyageManuCenterShow(
				swigCPtr, this, fLong, fLat, fCourse);
	}

	public boolean VoyageAutoOrientMode(double fOrieanAngle) {
		return elecchartcoreJNI.CHfVCFElectronicChart_VoyageAutoOrientMode(
				swigCPtr, this, fOrieanAngle);
	}

	public void ChartOrientMode(int nMode, double fOrieanAngle) {
		elecchartcoreJNI.CHfVCFElectronicChart_ChartOrientMode(swigCPtr, this,
				nMode, fOrieanAngle);
	}

	public int GetChartOrientMode() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetChartOrientMode(
				swigCPtr, this);
	}

	public void FlushOtherLayerDrawBuffer() {
		elecchartcoreJNI.CHfVCFElectronicChart_FlushOtherLayerDrawBuffer(
				swigCPtr, this);
	}

	public void FlushShowDrawBuffer() {
		elecchartcoreJNI.CHfVCFElectronicChart_FlushShowDrawBuffer(swigCPtr,
				this);
	}

	public void FlushScreenLayer() {
		elecchartcoreJNI.CHfVCFElectronicChart_FlushScreenLayer(swigCPtr, this);
	}

	public void SetChartConfigParam(stCHARTINITCONFIG stChartConfig) {
		elecchartcoreJNI.CHfVCFElectronicChart_SetChartConfigParam(swigCPtr,
				this, stCHARTINITCONFIG.getCPtr(stChartConfig), stChartConfig);
	}

	public void GetChartConfigParam(stCHARTINITCONFIG stChartConfig) {
		elecchartcoreJNI.CHfVCFElectronicChart_GetChartConfigParam(swigCPtr,
				this, stCHARTINITCONFIG.getCPtr(stChartConfig), stChartConfig);
	}

	public void SetLongLatShowStyle(int nStyle) {
		elecchartcoreJNI.CHfVCFElectronicChart_SetLongLatShowStyle(swigCPtr,
				this, nStyle);
	}

	public int GetLongLatShowStyle() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetLongLatShowStyle(
				swigCPtr, this);
	}

	public void SetNavShipCenterShowMode(int nMode) {
		elecchartcoreJNI.CHfVCFElectronicChart_SetNavShipCenterShowMode(
				swigCPtr, this, nMode);
	}

	public int GetNavShipCenterShowMode() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetNavShipCenterShowMode(
				swigCPtr, this);
	}

	public void SetIsAutoSwitchChart(boolean bAutoSwitch) {
		elecchartcoreJNI.CHfVCFElectronicChart_SetIsAutoSwitchChart(swigCPtr,
				this, bAutoSwitch);
	}

	public boolean GetIsAutoSwitchChart() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetIsAutoSwitchChart(
				swigCPtr, this);
	}

	public void SetGpsPosCorrectMode(int nMode) {
		elecchartcoreJNI.CHfVCFElectronicChart_SetGpsPosCorrectMode(swigCPtr,
				this, nMode);
	}

	public int GetGpsPosCorrectMode() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetGpsPosCorrectMode(
				swigCPtr, this);
	}

	public void SetTideAutoCorrect(boolean bAuto) {
		elecchartcoreJNI.CHfVCFElectronicChart_SetTideAutoCorrect(swigCPtr,
				this, bAuto);
	}

	public boolean GetTideAutoCorrect() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetTideAutoCorrect(
				swigCPtr, this);
	}

	public void GetUsableScaleGather(CxhfLongerSet lScaleSet) {
		elecchartcoreJNI.CHfVCFElectronicChart_GetUsableScaleGather(swigCPtr,
				this, CxhfLongerSet.getCPtr(lScaleSet), lScaleSet);
	}

	public double GetCurrChartMaxScale() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetCurrChartMaxScale(
				swigCPtr, this);
	}

	public double GetCurrChartMinScale() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetCurrChartMinScale(
				swigCPtr, this);
	}

	public void SetCurrChartMaxScale(double fMaxScale) {
		elecchartcoreJNI.CHfVCFElectronicChart_SetCurrChartMaxScale(swigCPtr,
				this, fMaxScale);
	}

	public void SetCurrChartMinScale(double fMinScale) {
		elecchartcoreJNI.CHfVCFElectronicChart_SetCurrChartMinScale(swigCPtr,
				this, fMinScale);
	}

	public void GetChartCoordCorrectValue(String strChartNo, stDPOINT stLatLong) {
		elecchartcoreJNI.CHfVCFElectronicChart_GetChartCoordCorrectValue(
				swigCPtr, this, strChartNo, stDPOINT.getCPtr(stLatLong),
				stLatLong);
	}

	public void SetChartCoordCorrectValue(String strChartNo,
			double fLatCorrect, double fLongCorrect) {
		elecchartcoreJNI.CHfVCFElectronicChart_SetChartCoordCorrectValue(
				swigCPtr, this, strChartNo, fLatCorrect, fLongCorrect);
	}

	public void GeoLongLatToScreenPoint(double dLong, double dLat,
			CPoint ptScrPoint) {
		elecchartcoreJNI.CHfVCFElectronicChart_GeoLongLatToScreenPoint(
				swigCPtr, this, dLong, dLat, CPoint.getCPtr(ptScrPoint),
				ptScrPoint);
	}

	public void GeoLongLatToPlanePoint(double dLong, double dLat,
			CPoint ptPlaPoint) {
		elecchartcoreJNI.CHfVCFElectronicChart_GeoLongLatToPlanePoint(swigCPtr,
				this, dLong, dLat, CPoint.getCPtr(ptPlaPoint), ptPlaPoint);
	}

	public void ScreenPointToGeoLongLat(CPoint ptscrPoint, stDPOINT stLatLong) {
		elecchartcoreJNI.CHfVCFElectronicChart_ScreenPointToGeoLongLat(
				swigCPtr, this, CPoint.getCPtr(ptscrPoint), ptscrPoint,
				stDPOINT.getCPtr(stLatLong), stLatLong);
	}

	public void ScreenPointToPlanePoint(CPoint ptscrPoint, CPoint ptPlaPoint) {
		elecchartcoreJNI.CHfVCFElectronicChart_ScreenPointToPlanePoint(
				swigCPtr, this, CPoint.getCPtr(ptscrPoint), ptscrPoint,
				CPoint.getCPtr(ptPlaPoint), ptPlaPoint);
	}

	public void CalculateDisAndDir(double dLong1, double dLat1, double dLong2,
			double dLat2, stDPOINT stDirDis) {
		elecchartcoreJNI.CHfVCFElectronicChart_CalculateDisAndDir(swigCPtr,
				this, dLong1, dLat1, dLong2, dLat2, stDPOINT.getCPtr(stDirDis),
				stDirDis);
	}

	public double CalculatePlanePointDis(CPoint ptPoint1, CPoint ptPoint2) {
		return elecchartcoreJNI
				.CHfVCFElectronicChart_CalculatePlanePointDis__SWIG_0(swigCPtr,
						this, CPoint.getCPtr(ptPoint1), ptPoint1,
						CPoint.getCPtr(ptPoint2), ptPoint2);
	}

	public double CalculatePlanePointDis(int x1, int y1, int x2, int y2) {
		return elecchartcoreJNI
				.CHfVCFElectronicChart_CalculatePlanePointDis__SWIG_1(swigCPtr,
						this, x1, y1, x2, y2);
	}

	public void CalculateLongLatByDisDir(double dLong0, double dLat0,
			double dDis, double dDir, stDPOINT stLatLong) {
		elecchartcoreJNI.CHfVCFElectronicChart_CalculateLongLatByDisDir(
				swigCPtr, this, dLong0, dLat0, dDis, dDir,
				stDPOINT.getCPtr(stLatLong), stLatLong);
	}

	public void GpsPosOffsetCorrect(double fInLong, double fInLat,
			stDPOINT stLatLong) {
		elecchartcoreJNI.CHfVCFElectronicChart_GpsPosOffsetCorrect(swigCPtr,
				this, fInLong, fInLat, stDPOINT.getCPtr(stLatLong), stLatLong);
	}

	public void GpsPosCenterCorrect(double fInLong, double fInLat,
			double fGpsDir, int nTxHead, int nTxTail, int nTxLeft,
			int nTxRight, stDPOINT stLatLong) {
		elecchartcoreJNI.CHfVCFElectronicChart_GpsPosCenterCorrect(swigCPtr,
				this, fInLong, fInLat, fGpsDir, nTxHead, nTxTail, nTxLeft,
				nTxRight, stDPOINT.getCPtr(stLatLong), stLatLong);
	}

	public void LongLatDegreeChangeToDMS(double fDegree,
			SWIGTYPE_p_int nDegree, SWIGTYPE_p_int nMinute,
			SWIGTYPE_p_double fSecond) {
		elecchartcoreJNI.CHfVCFElectronicChart_LongLatDegreeChangeToDMS(
				swigCPtr, this, fDegree, SWIGTYPE_p_int.getCPtr(nDegree),
				SWIGTYPE_p_int.getCPtr(nMinute),
				SWIGTYPE_p_double.getCPtr(fSecond));
	}

	public void GetSeaMeasurePoint(CPoint lp1, CPoint lp2) {
		elecchartcoreJNI.CHfVCFElectronicChart_GetSeaMeasurePoint(swigCPtr,
				this, CPoint.getCPtr(lp1), lp1, CPoint.getCPtr(lp2), lp2);
	}

	public int GetSeaMeasurePoint1X() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetSeaMeasurePoint1X(
				swigCPtr, this);
	}

	public int GetSeaMeasurePoint1Y() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetSeaMeasurePoint1Y(
				swigCPtr, this);
	}

	public int GetSeaMeasurePoint2X() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetSeaMeasurePoint2X(
				swigCPtr, this);
	}

	public int GetSeaMeasurePoint2Y() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetSeaMeasurePoint2Y(
				swigCPtr, this);
	}

	public void GetSeaMeasureDirDis(stDPOINT stDirDis) {
		elecchartcoreJNI.CHfVCFElectronicChart_GetSeaMeasureDirDis(swigCPtr,
				this, stDPOINT.getCPtr(stDirDis), stDirDis);
	}

	public float GetSeaMeasureDir() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetSeaMeasureDir(
				swigCPtr, this);
	}

	public float GetSeaMeasureDis() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetSeaMeasureDis(
				swigCPtr, this);
	}

	public int GetGeoDataSetNums() {
		return elecchartcoreJNI.CHfVCFElectronicChart_GetGeoDataSetNums(
				swigCPtr, this);
	}

	public stVCFGEODATASETDESCR GetGeoDataSetDescr(int nIndex) {
		long cPtr = elecchartcoreJNI
				.CHfVCFElectronicChart_GetGeoDataSetDescr__SWIG_0(swigCPtr,
						this, nIndex);
		return (cPtr == 0) ? null : new stVCFGEODATASETDESCR(cPtr, false);
	}

	public int GetGeoDataSetDescr(int nIndex,
			stVCFGEODATASETDESCR stDataSetDescr) {
		return elecchartcoreJNI
				.CHfVCFElectronicChart_GetGeoDataSetDescr__SWIG_1(swigCPtr,
						this, nIndex,
						stVCFGEODATASETDESCR.getCPtr(stDataSetDescr),
						stDataSetDescr);
	}

	public void SetMouseOperationMode(emCHART_OPERATION_MODE emMouseMode) {
		elecchartcoreJNI.CHfVCFElectronicChart_SetMouseOperationMode(swigCPtr,
				this, emMouseMode.swigValue());
	}

	public emCHART_OPERATION_MODE GetMouseOperationMode() {
		return emCHART_OPERATION_MODE.swigToEnum(elecchartcoreJNI
				.CHfVCFElectronicChart_GetMouseOperationMode(swigCPtr, this));
	}

	public boolean OnLButtonDbClk(CPoint point) {
		return elecchartcoreJNI.CHfVCFElectronicChart_OnLButtonDbClk(swigCPtr,
				this, CPoint.getCPtr(point), point);
	}

	public boolean OnRButtonDown(CPoint point) {
		return elecchartcoreJNI.CHfVCFElectronicChart_OnRButtonDown(swigCPtr,
				this, CPoint.getCPtr(point), point);
	}

	public boolean OnRButtonUp(CPoint point) {
		return elecchartcoreJNI.CHfVCFElectronicChart_OnRButtonUp(swigCPtr,
				this, CPoint.getCPtr(point), point);
	}

	public boolean OnRButtonDblClk(CPoint point) {
		return elecchartcoreJNI.CHfVCFElectronicChart_OnRButtonDblClk(swigCPtr,
				this, CPoint.getCPtr(point), point);
	}

	public boolean OnTouchDown(float x, float y) {
		return elecchartcoreJNI.CHfVCFElectronicChart_OnTouchDown(swigCPtr,
				this, x, y);
	}

	public boolean OnTouchMove(float x, float y) {
		return elecchartcoreJNI.CHfVCFElectronicChart_OnTouchMove(swigCPtr,
				this, x, y);
	}

	public boolean OnTouchUp(float x, float y) {
		return elecchartcoreJNI.CHfVCFElectronicChart_OnTouchUp(swigCPtr, this,
				x, y);
	}

	public void calcTouchPtLatLong(int x, int y) {
		elecchartcoreJNI.CHfVCFElectronicChart_calcTouchPtLatLong(swigCPtr,
				this, x, y);
	}

	public boolean SetCursor() {
		return elecchartcoreJNI.CHfVCFElectronicChart_SetCursor(swigCPtr, this);
	}

	public void RTimeMousePtLatLongCalc(CPoint point) {
		elecchartcoreJNI.CHfVCFElectronicChart_RTimeMousePtLatLongCalc(
				swigCPtr, this, CPoint.getCPtr(point), point);
	}

	public void twoFingerPinchChart(double fChangeScale) {
		elecchartcoreJNI.CHfVCFElectronicChart_twoFingerPinchChart__SWIG_0(
				swigCPtr, this, fChangeScale);
	}

	public void twoFingerPinchChart(float x, float y, double fChangeScale) {
		elecchartcoreJNI.CHfVCFElectronicChart_twoFingerPinchChart__SWIG_1(
				swigCPtr, this, x, y, fChangeScale);
	}

	public void OneFingerDoubleTapZoomin(int x, int y) {
		elecchartcoreJNI.CHfVCFElectronicChart_OneFingerDoubleTapZoomin(
				swigCPtr, this, x, y);
	}

	public void DrawVCFChart() {
		elecchartcoreJNI.CHfVCFElectronicChart_DrawVCFChart(swigCPtr, this);
	}

}
