/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CHfVCFSymbol {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CHfVCFSymbol(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CHfVCFSymbol obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CHfVCFSymbol(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public CHfVCFSymbol() {
		this(elecchartcoreJNI.new_CHfVCFSymbol(), true);
	}

	public emVCF_SYMBOL_TB GetType() {
		return emVCF_SYMBOL_TB.swigToEnum(elecchartcoreJNI
				.CHfVCFSymbol_GetType(swigCPtr, this));
	}

	public void SetSymbolId(int nSymId) {
		elecchartcoreJNI.CHfVCFSymbol_SetSymbolId(swigCPtr, this, nSymId);
	}

	public int GetSymbolId() {
		return elecchartcoreJNI.CHfVCFSymbol_GetSymbolId(swigCPtr, this);
	}

	public void SetSymbolName(String pszName) {
		elecchartcoreJNI.CHfVCFSymbol_SetSymbolName(swigCPtr, this, pszName);
	}

	public String GetSymbolName() {
		return elecchartcoreJNI.CHfVCFSymbol_GetSymbolName(swigCPtr, this);
	}

}
