/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CHfVCFGeoSymbolization {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CHfVCFGeoSymbolization(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CHfVCFGeoSymbolization obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CHfVCFGeoSymbolization(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public CHfVCFGeoSymbolization() {
		this(elecchartcoreJNI.new_CHfVCFGeoSymbolization(), true);
	}

	public void VCFPointGeometrySymbolization(CHfVCFSymbol pSymbol,
			CVCFGeometry pGeometry, CHfVCFGeoCanvas pGeoCanvas, double dAngle,
			double dScale, int lFC, int nOffX, int nOffY) {
		elecchartcoreJNI
				.CHfVCFGeoSymbolization_VCFPointGeometrySymbolization__SWIG_0(
						swigCPtr, this, CHfVCFSymbol.getCPtr(pSymbol), pSymbol,
						CVCFGeometry.getCPtr(pGeometry), pGeometry,
						CHfVCFGeoCanvas.getCPtr(pGeoCanvas), pGeoCanvas,
						dAngle, dScale, lFC, nOffX, nOffY);
	}

	public void VCFPointGeometrySymbolization(CHfVCFSymbol pSymbol,
			CVCFGeometry pGeometry, CHfVCFGeoCanvas pGeoCanvas, double dAngle,
			double dScale, int lFC, int nOffX) {
		elecchartcoreJNI
				.CHfVCFGeoSymbolization_VCFPointGeometrySymbolization__SWIG_1(
						swigCPtr, this, CHfVCFSymbol.getCPtr(pSymbol), pSymbol,
						CVCFGeometry.getCPtr(pGeometry), pGeometry,
						CHfVCFGeoCanvas.getCPtr(pGeoCanvas), pGeoCanvas,
						dAngle, dScale, lFC, nOffX);
	}

	public void VCFPointGeometrySymbolization(CHfVCFSymbol pSymbol,
			CVCFGeometry pGeometry, CHfVCFGeoCanvas pGeoCanvas, double dAngle,
			double dScale, int lFC) {
		elecchartcoreJNI
				.CHfVCFGeoSymbolization_VCFPointGeometrySymbolization__SWIG_2(
						swigCPtr, this, CHfVCFSymbol.getCPtr(pSymbol), pSymbol,
						CVCFGeometry.getCPtr(pGeometry), pGeometry,
						CHfVCFGeoCanvas.getCPtr(pGeoCanvas), pGeoCanvas,
						dAngle, dScale, lFC);
	}

	public void VCFPointGeometrySymbolization(CHfVCFSymbol pSymbol,
			CVCFGeometry pGeometry, CHfVCFGeoCanvas pGeoCanvas, double dAngle,
			double dScale) {
		elecchartcoreJNI
				.CHfVCFGeoSymbolization_VCFPointGeometrySymbolization__SWIG_3(
						swigCPtr, this, CHfVCFSymbol.getCPtr(pSymbol), pSymbol,
						CVCFGeometry.getCPtr(pGeometry), pGeometry,
						CHfVCFGeoCanvas.getCPtr(pGeoCanvas), pGeoCanvas,
						dAngle, dScale);
	}

	public void VCFLineGeometrySymbolization(CHfVCFSymbol pSymbol,
			CVCFGeometry pGeometry, CHfVCFGeoCanvas pGeoCanvas, double dAngle,
			double dScale) {
		elecchartcoreJNI
				.CHfVCFGeoSymbolization_VCFLineGeometrySymbolization(swigCPtr,
						this, CHfVCFSymbol.getCPtr(pSymbol), pSymbol,
						CVCFGeometry.getCPtr(pGeometry), pGeometry,
						CHfVCFGeoCanvas.getCPtr(pGeoCanvas), pGeoCanvas,
						dAngle, dScale);
	}

	public void VCFAreaGeometrySymbolization(CHfVCFSymbol pSymbol,
			CVCFGeometry pGeometry, CHfVCFGeoCanvas pGeoCanvas, double dScale) {
		elecchartcoreJNI.CHfVCFGeoSymbolization_VCFAreaGeometrySymbolization(
				swigCPtr, this, CHfVCFSymbol.getCPtr(pSymbol), pSymbol,
				CVCFGeometry.getCPtr(pGeometry), pGeometry,
				CHfVCFGeoCanvas.getCPtr(pGeoCanvas), pGeoCanvas, dScale);
	}

}
