/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CHfVCFSymbolLib {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CHfVCFSymbolLib(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CHfVCFSymbolLib obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CHfVCFSymbolLib(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public CHfVCFSymbolLib() {
		this(elecchartcoreJNI.new_CHfVCFSymbolLib(), true);
	}

	public void InitialSymbolTable(String pszFileName) {
		elecchartcoreJNI.CHfVCFSymbolLib_InitialSymbolTable(swigCPtr, this,
				pszFileName);
	}

	public void DestorySymbolTable() {
		elecchartcoreJNI.CHfVCFSymbolLib_DestorySymbolTable(swigCPtr, this);
	}

	public int GetSymbolNums(emVCF_SYMBOL_TB emType) {
		return elecchartcoreJNI.CHfVCFSymbolLib_GetSymbolNums(swigCPtr, this,
				emType.swigValue());
	}

	public CHfVCFSymbol GetSymbolBySymId(emVCF_SYMBOL_TB emType, int SymId) {
		long cPtr = elecchartcoreJNI.CHfVCFSymbolLib_GetSymbolBySymId(swigCPtr,
				this, emType.swigValue(), SymId);
		return (cPtr == 0) ? null : new CHfVCFSymbol(cPtr, false);
	}

}
