/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CLineSegment {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CLineSegment(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CLineSegment obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CLineSegment(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setX1(int value) {
		elecchartcoreJNI.CLineSegment_x1_set(swigCPtr, this, value);
	}

	public int getX1() {
		return elecchartcoreJNI.CLineSegment_x1_get(swigCPtr, this);
	}

	public void setY1(int value) {
		elecchartcoreJNI.CLineSegment_y1_set(swigCPtr, this, value);
	}

	public int getY1() {
		return elecchartcoreJNI.CLineSegment_y1_get(swigCPtr, this);
	}

	public void setX2(int value) {
		elecchartcoreJNI.CLineSegment_x2_set(swigCPtr, this, value);
	}

	public int getX2() {
		return elecchartcoreJNI.CLineSegment_x2_get(swigCPtr, this);
	}

	public void setY2(int value) {
		elecchartcoreJNI.CLineSegment_y2_set(swigCPtr, this, value);
	}

	public int getY2() {
		return elecchartcoreJNI.CLineSegment_y2_get(swigCPtr, this);
	}

	public CLineSegment(stLPOINT p1, stLPOINT p2) {
		this(elecchartcoreJNI.new_CLineSegment(stLPOINT.getCPtr(p1), p1,
				stLPOINT.getCPtr(p2), p2), true);
	}

	public void LineSegmentSet(stLPOINT p1, stLPOINT p2) {
		elecchartcoreJNI.CLineSegment_LineSegmentSet(swigCPtr, this,
				stLPOINT.getCPtr(p1), p1, stLPOINT.getCPtr(p2), p2);
	}

	public double Length() {
		return elecchartcoreJNI.CLineSegment_Length(swigCPtr, this);
	}

	public double Angle() {
		return elecchartcoreJNI.CLineSegment_Angle(swigCPtr, this);
	}

}
