/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CPoint {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CPoint(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CPoint obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CPoint(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public CPoint() {
		this(elecchartcoreJNI.new_CPoint__SWIG_0(), true);
	}

	public CPoint(int initX, int initY) {
		this(elecchartcoreJNI.new_CPoint__SWIG_1(initX, initY), true);
	}

	public void setX(int value) {
		elecchartcoreJNI.CPoint_x_set(swigCPtr, this, value);
	}

	public int getX() {
		return elecchartcoreJNI.CPoint_x_get(swigCPtr, this);
	}

	public void setY(int value) {
		elecchartcoreJNI.CPoint_y_set(swigCPtr, this, value);
	}

	public int getY() {
		return elecchartcoreJNI.CPoint_y_get(swigCPtr, this);
	}

}
