/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CRect extends RECT {
	private long swigCPtr;

	protected CRect(long cPtr, boolean cMemoryOwn) {
		super(elecchartcoreJNI.CRect_SWIGUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CRect obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CRect(swigCPtr);
			}
			swigCPtr = 0;
		}
		super.delete();
	}

	public CRect() {
		this(elecchartcoreJNI.new_CRect__SWIG_0(), true);
	}

	public CRect(int l, int t, int r, int b) {
		this(elecchartcoreJNI.new_CRect__SWIG_1(l, t, r, b), true);
	}

	public CRect(RECT srcRect) {
		this(
				elecchartcoreJNI.new_CRect__SWIG_2(RECT.getCPtr(srcRect),
						srcRect), true);
	}

	public CRect(CPoint topLeft, CPoint bottomRight) {
		this(elecchartcoreJNI.new_CRect__SWIG_3(CPoint.getCPtr(topLeft),
				topLeft, CPoint.getCPtr(bottomRight), bottomRight), true);
	}

	public int Width() {
		return elecchartcoreJNI.CRect_Width(swigCPtr, this);
	}

	public int Height() {
		return elecchartcoreJNI.CRect_Height(swigCPtr, this);
	}

	public void SetRect(int x1, int y1, int x2, int y2) {
		elecchartcoreJNI.CRect_SetRect__SWIG_0(swigCPtr, this, x1, y1, x2, y2);
	}

	public void SetRect(POINT topLeft, POINT bottomRight) {
		elecchartcoreJNI.CRect_SetRect__SWIG_1(swigCPtr, this,
				POINT.getCPtr(topLeft), topLeft, POINT.getCPtr(bottomRight),
				bottomRight);
	}

	public void SetRect(CPoint topLeft, CPoint bottomRight) {
		elecchartcoreJNI.CRect_SetRect__SWIG_2(swigCPtr, this,
				CPoint.getCPtr(topLeft), topLeft, CPoint.getCPtr(bottomRight),
				bottomRight);
	}

	public void InflateRect(int offx, int offy) {
		elecchartcoreJNI.CRect_InflateRect(swigCPtr, this, offx, offy);
	}

	public boolean PtInRect(POINT point) {
		return elecchartcoreJNI.CRect_PtInRect__SWIG_0(swigCPtr, this,
				POINT.getCPtr(point), point);
	}

	public boolean PtInRect(CPoint point) {
		return elecchartcoreJNI.CRect_PtInRect__SWIG_1(swigCPtr, this,
				CPoint.getCPtr(point), point);
	}

}
