/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CVCFSymLookupTable {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CVCFSymLookupTable(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CVCFSymLookupTable obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CVCFSymLookupTable(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public CVCFSymLookupTable() {
		this(elecchartcoreJNI.new_CVCFSymLookupTable(), true);
	}

	public void InitialLookupTable(String pszFileName) {
		elecchartcoreJNI.CVCFSymLookupTable_InitialLookupTable(swigCPtr, this,
				pszFileName);
	}

	public void DestoryLookupTable() {
		elecchartcoreJNI.CVCFSymLookupTable_DestoryLookupTable(swigCPtr, this);
	}

	public int GetSymbolIdByFC(emVCF_LOOKUP_TB emlupTabtype, int lfc) {
		return elecchartcoreJNI.CVCFSymLookupTable_GetSymbolIdByFC(swigCPtr,
				this, emlupTabtype.swigValue(), lfc);
	}

}
