/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CVCFGeoPolygon extends CVCFGeometry {
	private long swigCPtr;

	protected CVCFGeoPolygon(long cPtr, boolean cMemoryOwn) {
		super(elecchartcoreJNI.CVCFGeoPolygon_SWIGUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CVCFGeoPolygon obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CVCFGeoPolygon(swigCPtr);
			}
			swigCPtr = 0;
		}
		super.delete();
	}

	public CVCFGeoPolygon() {
		this(elecchartcoreJNI.new_CVCFGeoPolygon(), true);
	}

	public xhfGeometryType getGeometryType() {
		return xhfGeometryType.swigToEnum(elecchartcoreJNI
				.CVCFGeoPolygon_getGeometryType(swigCPtr, this));
	}

	public boolean ScrPointSelectAt(CPoint pt, stGEOOBJPICKINDEX pkIndex) {
		return elecchartcoreJNI.CVCFGeoPolygon_ScrPointSelectAt(swigCPtr, this,
				CPoint.getCPtr(pt), pt, stGEOOBJPICKINDEX.getCPtr(pkIndex),
				pkIndex);
	}

	public void addRing(CVCFGeoRing arg0) {
		elecchartcoreJNI.CVCFGeoPolygon_addRing(swigCPtr, this,
				CVCFGeoRing.getCPtr(arg0), arg0);
	}

	public void addRingDirectly(CVCFGeoRing arg0) {
		elecchartcoreJNI.CVCFGeoPolygon_addRingDirectly(swigCPtr, this,
				CVCFGeoRing.getCPtr(arg0), arg0);
	}

	public CVCFGeoRing getExteriorRing() {
		long cPtr = elecchartcoreJNI.CVCFGeoPolygon_getExteriorRing__SWIG_0(
				swigCPtr, this);
		return (cPtr == 0) ? null : new CVCFGeoRing(cPtr, false);
	}

	public int getNumInteriorRings() {
		return elecchartcoreJNI.CVCFGeoPolygon_getNumInteriorRings(swigCPtr,
				this);
	}

	public CVCFGeoRing getInteriorRing(int arg0) {
		long cPtr = elecchartcoreJNI.CVCFGeoPolygon_getInteriorRing__SWIG_0(
				swigCPtr, this, arg0);
		return (cPtr == 0) ? null : new CVCFGeoRing(cPtr, false);
	}

	public int IsPointOnSurface(CVCFGeoPoint pt) {
		return elecchartcoreJNI.CVCFGeoPolygon_IsPointOnSurface(swigCPtr, this,
				CVCFGeoPoint.getCPtr(pt), pt);
	}

	public void closeRings() {
		elecchartcoreJNI.CVCFGeoPolygon_closeRings(swigCPtr, this);
	}

	public int GetTatolPointNums() {
		return elecchartcoreJNI
				.CVCFGeoPolygon_GetTatolPointNums(swigCPtr, this);
	}

	public int GetTatollPointNums() {
		return elecchartcoreJNI.CVCFGeoPolygon_GetTatollPointNums(swigCPtr,
				this);
	}

	public int getNumdspPoints() {
		return elecchartcoreJNI.CVCFGeoPolygon_getNumdspPoints(swigCPtr, this);
	}

	public void setNumdspPoints(int arg0) {
		elecchartcoreJNI.CVCFGeoPolygon_setNumdspPoints(swigCPtr, this, arg0);
	}

	public void setdspPoint(int arg0, int arg1, int arg2) {
		elecchartcoreJNI.CVCFGeoPolygon_setdspPoint(swigCPtr, this, arg0, arg1,
				arg2);
	}

	public void setNumdspEdgeLens(int arg0) {
		elecchartcoreJNI.CVCFGeoPolygon_setNumdspEdgeLens(swigCPtr, this, arg0);
	}

	public void setdspEdgeLen(int arg0, int arg1) {
		elecchartcoreJNI.CVCFGeoPolygon_setdspEdgeLen(swigCPtr, this, arg0,
				arg1);
	}

	public void setM_ndspPointCount(int value) {
		elecchartcoreJNI.CVCFGeoPolygon_m_ndspPointCount_set(swigCPtr, this,
				value);
	}

	public int getM_ndspPointCount() {
		return elecchartcoreJNI.CVCFGeoPolygon_m_ndspPointCount_get(swigCPtr,
				this);
	}

	public void setM_paoDspPointXs(Ints value) {
		elecchartcoreJNI.CVCFGeoPolygon_m_paoDspPointXs_set(swigCPtr, this,
				Ints.getCPtr(value), value);
	}

	public Ints getM_paoDspPointXs() {
		long cPtr = elecchartcoreJNI.CVCFGeoPolygon_m_paoDspPointXs_get(
				swigCPtr, this);
		return (cPtr == 0) ? null : new Ints(cPtr, false);
	}

	public void setM_paoDspPointYs(Ints value) {
		elecchartcoreJNI.CVCFGeoPolygon_m_paoDspPointYs_set(swigCPtr, this,
				Ints.getCPtr(value), value);
	}

	public Ints getM_paoDspPointYs() {
		long cPtr = elecchartcoreJNI.CVCFGeoPolygon_m_paoDspPointYs_get(
				swigCPtr, this);
		return (cPtr == 0) ? null : new Ints(cPtr, false);
	}

	public void setM_nEdgeLens(Ints value) {
		elecchartcoreJNI.CVCFGeoPolygon_m_nEdgeLens_set(swigCPtr, this,
				Ints.getCPtr(value), value);
	}

	public Ints getM_nEdgeLens() {
		long cPtr = elecchartcoreJNI.CVCFGeoPolygon_m_nEdgeLens_get(swigCPtr,
				this);
		return (cPtr == 0) ? null : new Ints(cPtr, false);
	}

}
