/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CVcfSencManageModul {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CVcfSencManageModul(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CVcfSencManageModul obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CVcfSencManageModul(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public CVcfSencManageModul() {
		this(elecchartcoreJNI.new_CVcfSencManageModul(), true);
	}

	public void CloseVcfSencDatabase() {
		elecchartcoreJNI.CVcfSencManageModul_CloseVcfSencDatabase(swigCPtr,
				this);
	}

	public int IsOpenGeoDatabase() {
		return elecchartcoreJNI.CVcfSencManageModul_IsOpenGeoDatabase(swigCPtr,
				this);
	}

	public int GetGeoDataSetCount() {
		return elecchartcoreJNI.CVcfSencManageModul_GetGeoDataSetCount(
				swigCPtr, this);
	}

	public void GetCoverage(stGEOENVELOPE coverage) {
		elecchartcoreJNI.CVcfSencManageModul_GetCoverage(swigCPtr, this,
				stGEOENVELOPE.getCPtr(coverage), coverage);
	}

	public void SetVcfSencDatabasePath(String pszFilePath) {
		elecchartcoreJNI.CVcfSencManageModul_SetVcfSencDatabasePath(swigCPtr,
				this, pszFilePath);
	}

	public int OpenVcfSencDatabase() {
		return elecchartcoreJNI.CVcfSencManageModul_OpenVcfSencDatabase(
				swigCPtr, this);
	}

	public int LoadVCFGeoDataSet(String pszDataSetName,
			CVCFGeoDataSet pGeoDataSet) {
		return elecchartcoreJNI.CVcfSencManageModul_LoadVCFGeoDataSet(swigCPtr,
				this, pszDataSetName, CVCFGeoDataSet.getCPtr(pGeoDataSet),
				pGeoDataSet);
	}

	public int GetAllGeoDataSetDescrs(CGeoDataSetDesrArray vecDataSetDescList) {
		return elecchartcoreJNI.CVcfSencManageModul_GetAllGeoDataSetDescrs(
				swigCPtr, this,
				CGeoDataSetDesrArray.getCPtr(vecDataSetDescList),
				vecDataSetDescList);
	}

	public int SaveAllGeoDataSetDescrs(CGeoDataSetDesrArray vecDataSetDescList) {
		return elecchartcoreJNI.CVcfSencManageModul_SaveAllGeoDataSetDescrs(
				swigCPtr, this,
				CGeoDataSetDesrArray.getCPtr(vecDataSetDescList),
				vecDataSetDescList);
	}

	public int SaveManUpdateVCFGeoDataSet(String pszDataSetName,
			CVCFGeoDataSet pGeoDataSet) {
		return elecchartcoreJNI.CVcfSencManageModul_SaveManUpdateVCFGeoDataSet(
				swigCPtr, this, pszDataSetName,
				CVCFGeoDataSet.getCPtr(pGeoDataSet), pGeoDataSet);
	}

	public int LoadManUpdateVCFGeoDataSet(String pszDataSetName,
			CVCFGeoDataSet pGeoDataSet) {
		return elecchartcoreJNI.CVcfSencManageModul_LoadManUpdateVCFGeoDataSet(
				swigCPtr, this, pszDataSetName,
				CVCFGeoDataSet.getCPtr(pGeoDataSet), pGeoDataSet);
	}

}
