/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CVCFGeoRing extends CVCFGeoEdge {
	private long swigCPtr;

	protected CVCFGeoRing(long cPtr, boolean cMemoryOwn) {
		super(elecchartcoreJNI.CVCFGeoRing_SWIGUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CVCFGeoRing obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CVCFGeoRing(swigCPtr);
			}
			swigCPtr = 0;
		}
		super.delete();
	}

	public CVCFGeoRing() {
		this(elecchartcoreJNI.new_CVCFGeoRing__SWIG_0(), true);
	}

	public CVCFGeoRing(CVCFGeoRing arg0) {
		this(elecchartcoreJNI.new_CVCFGeoRing__SWIG_1(
				CVCFGeoRing.getCPtr(arg0), arg0), true);
	}

	public int isClockwise() {
		return elecchartcoreJNI.CVCFGeoRing_isClockwise(swigCPtr, this);
	}

	public void reverseWindingOrder() {
		elecchartcoreJNI.CVCFGeoRing_reverseWindingOrder(swigCPtr, this);
	}

	public void closeRings() {
		elecchartcoreJNI.CVCFGeoRing_closeRings(swigCPtr, this);
	}

	public double get_Area() {
		return elecchartcoreJNI.CVCFGeoRing_get_Area(swigCPtr, this);
	}

	public int isPointInRing(CVCFGeoPoint pt, int bTestEnvelope) {
		return elecchartcoreJNI.CVCFGeoRing_isPointInRing__SWIG_0(swigCPtr,
				this, CVCFGeoPoint.getCPtr(pt), pt, bTestEnvelope);
	}

	public int isPointInRing(CVCFGeoPoint pt) {
		return elecchartcoreJNI.CVCFGeoRing_isPointInRing__SWIG_1(swigCPtr,
				this, CVCFGeoPoint.getCPtr(pt), pt);
	}

	public int isPointOnRingBoundary(CVCFGeoPoint pt, int bTestEnvelope) {
		return elecchartcoreJNI.CVCFGeoRing_isPointOnRingBoundary__SWIG_0(
				swigCPtr, this, CVCFGeoPoint.getCPtr(pt), pt, bTestEnvelope);
	}

	public int isPointOnRingBoundary(CVCFGeoPoint pt) {
		return elecchartcoreJNI.CVCFGeoRing_isPointOnRingBoundary__SWIG_1(
				swigCPtr, this, CVCFGeoPoint.getCPtr(pt), pt);
	}

	public int islClockwise() {
		return elecchartcoreJNI.CVCFGeoRing_islClockwise(swigCPtr, this);
	}

}
