/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CVCFDataDictionary {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CVCFDataDictionary(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CVCFDataDictionary obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CVCFDataDictionary(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public CVCFDataDictionary() {
		this(elecchartcoreJNI.new_CVCFDataDictionary(), true);
	}

	public int LoadVCFDisplayPrioritys(String pszFilePathName) {
		return elecchartcoreJNI.CVCFDataDictionary_LoadVCFDisplayPrioritys(
				swigCPtr, this, pszFilePathName);
	}

	public int LoadVCFSimpObjectDictonary(String pszFilePathName) {
		return elecchartcoreJNI.CVCFDataDictionary_LoadVCFSimpObjectDictonary(
				swigCPtr, this, pszFilePathName);
	}

	public void ClearVCFDisplayPrioritys() {
		elecchartcoreJNI.CVCFDataDictionary_ClearVCFDisplayPrioritys(swigCPtr,
				this);
	}

	public void ClearVCFSimpObjectDictonary() {
		elecchartcoreJNI.CVCFDataDictionary_ClearVCFSimpObjectDictonary(
				swigCPtr, this);
	}

	public int GetVCFDisplayPriorityNums() {
		return elecchartcoreJNI.CVCFDataDictionary_GetVCFDisplayPriorityNums(
				swigCPtr, this);
	}

	public stVCFDISPLAYPRIO GetVCFDisplayDictionary(int nIndex) {
		long cPtr = elecchartcoreJNI
				.CVCFDataDictionary_GetVCFDisplayDictionary(swigCPtr, this,
						nIndex);
		return (cPtr == 0) ? null : new stVCFDISPLAYPRIO(cPtr, false);
	}

	public int GetVCFDisplayPriorityBySmLAncroy(String pszSmlLayerName) {
		return elecchartcoreJNI
				.CVCFDataDictionary_GetVCFDisplayPriorityBySmLAncroy(swigCPtr,
						this, pszSmlLayerName);
	}

	public int GetVCFDisplayPriorityByGeoLayerNo(int nGeoLayer) {
		return elecchartcoreJNI
				.CVCFDataDictionary_GetVCFDisplayPriorityByGeoLayerNo(swigCPtr,
						this, nGeoLayer);
	}

	public int GetGeoLayerNumsByBigLayerNo(int nBigLayerNo) {
		return elecchartcoreJNI.CVCFDataDictionary_GetGeoLayerNumsByBigLayerNo(
				swigCPtr, this, nBigLayerNo);
	}

	public int GetVCFObjectDictionaryByFC(int lFC,
			stOBJECTDICTIONARY stDictionary) {
		return elecchartcoreJNI.CVCFDataDictionary_GetVCFObjectDictionaryByFC(
				swigCPtr, this, lFC, stOBJECTDICTIONARY.getCPtr(stDictionary),
				stDictionary);
	}

	public int GetVCFObjectClassNums() {
		return elecchartcoreJNI.CVCFDataDictionary_GetVCFObjectClassNums(
				swigCPtr, this);
	}

	public int GetVCFObjectSymbolIdByFC(int lFC, SWIGTYPE_p_int nSymbolId) {
		return elecchartcoreJNI.CVCFDataDictionary_GetVCFObjectSymbolIdByFC(
				swigCPtr, this, lFC, SWIGTYPE_p_int.getCPtr(nSymbolId));
	}

	public int GetVCFGeoLayerIMOCategoryByPri(int nPri) {
		return elecchartcoreJNI
				.CVCFDataDictionary_GetVCFGeoLayerIMOCategoryByPri(swigCPtr,
						this, nPri);
	}

	public int GetSmlLayerNameByLayerCode(int nGeoLayer, String szGeoLayerName) {
		return elecchartcoreJNI.CVCFDataDictionary_GetSmlLayerNameByLayerCode(
				swigCPtr, this, nGeoLayer, szGeoLayerName);
	}

	public int GetSmlLayerCodeByLayerName(String szGeoLayerName) {
		return elecchartcoreJNI.CVCFDataDictionary_GetSmlLayerCodeByLayerName(
				swigCPtr, this, szGeoLayerName);
	}

	public int GetGeoLayerSimpObDictNums(int nGeoLayer) {
		return elecchartcoreJNI.CVCFDataDictionary_GetGeoLayerSimpObDictNums(
				swigCPtr, this, nGeoLayer);
	}

	public stSIMPOBJECTDICTIONARY GetGeoLayerSimpObDict(int nGeoLayer, int i) {
		long cPtr = elecchartcoreJNI.CVCFDataDictionary_GetGeoLayerSimpObDict(
				swigCPtr, this, nGeoLayer, i);
		return (cPtr == 0) ? null : new stSIMPOBJECTDICTIONARY(cPtr, false);
	}

	public stSIMPOBJECTDICTIONARY GetGeoLayerSimpObDictByFC(int nGeoLayer,
			int lFC) {
		long cPtr = elecchartcoreJNI
				.CVCFDataDictionary_GetGeoLayerSimpObDictByFC(swigCPtr, this,
						nGeoLayer, lFC);
		return (cPtr == 0) ? null : new stSIMPOBJECTDICTIONARY(cPtr, false);
	}

}
