/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CVCFAttrField {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CVCFAttrField(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CVCFAttrField obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CVCFAttrField(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public CVCFAttrField(CVCFAttrField vcfattri) {
		this(elecchartcoreJNI.new_CVCFAttrField__SWIG_0(
				CVCFAttrField.getCPtr(vcfattri), vcfattri), true);
	}

	public CVCFAttrField() {
		this(elecchartcoreJNI.new_CVCFAttrField__SWIG_1(), true);
	}

	public void SetVcfFieldType(euVcfFieldType eType) {
		elecchartcoreJNI.CVCFAttrField_SetVcfFieldType(swigCPtr, this,
				eType.swigValue());
	}

	public euVcfFieldType GetVcfFieldType() {
		return euVcfFieldType.swigToEnum(elecchartcoreJNI
				.CVCFAttrField_GetVcfFieldType(swigCPtr, this));
	}

	public void SetVcfAttrCode(int nCode) {
		elecchartcoreJNI.CVCFAttrField_SetVcfAttrCode(swigCPtr, this, nCode);
	}

	public int GetVcfAttrCode() {
		return elecchartcoreJNI.CVCFAttrField_GetVcfAttrCode(swigCPtr, this);
	}

	public void SetVcfFieldValue(int nValue) {
		elecchartcoreJNI.CVCFAttrField_SetVcfFieldValue__SWIG_0(swigCPtr, this,
				nValue);
	}

	public void SetVcfFieldValue(double dfValue) {
		elecchartcoreJNI.CVCFAttrField_SetVcfFieldValue__SWIG_1(swigCPtr, this,
				dfValue);
	}

	public void SetVcfFieldValue(String pszString) {
		elecchartcoreJNI.CVCFAttrField_SetVcfFieldValue__SWIG_2(swigCPtr, this,
				pszString);
	}

	public int GetFieldValueAsInteger() {
		return elecchartcoreJNI.CVCFAttrField_GetFieldValueAsInteger(swigCPtr,
				this);
	}

	public double GetFieldValueAsDouble() {
		return elecchartcoreJNI.CVCFAttrField_GetFieldValueAsDouble(swigCPtr,
				this);
	}

	public String GetFieldValueAsString() {
		return elecchartcoreJNI.CVCFAttrField_GetFieldValueAsString(swigCPtr,
				this);
	}

	public void setM_nAttrCode(int value) {
		elecchartcoreJNI.CVCFAttrField_m_nAttrCode_set(swigCPtr, this, value);
	}

	public int getM_nAttrCode() {
		return elecchartcoreJNI.CVCFAttrField_m_nAttrCode_get(swigCPtr, this);
	}

	public void setM_euFieldType(euVcfFieldType value) {
		elecchartcoreJNI.CVCFAttrField_m_euFieldType_set(swigCPtr, this,
				value.swigValue());
	}

	public euVcfFieldType getM_euFieldType() {
		return euVcfFieldType.swigToEnum(elecchartcoreJNI
				.CVCFAttrField_m_euFieldType_get(swigCPtr, this));
	}

	public void setM_uiFieldValue(uiVcfField value) {
		elecchartcoreJNI.CVCFAttrField_m_uiFieldValue_set(swigCPtr, this,
				uiVcfField.getCPtr(value), value);
	}

	public uiVcfField getM_uiFieldValue() {
		long cPtr = elecchartcoreJNI.CVCFAttrField_m_uiFieldValue_get(swigCPtr,
				this);
		return (cPtr == 0) ? null : new uiVcfField(cPtr, false);
	}

}
