/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CVCFGeometry {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CVCFGeometry(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CVCFGeometry obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CVCFGeometry(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public xhfGeometryType getGeometryType() {
		return xhfGeometryType.swigToEnum(elecchartcoreJNI
				.CVCFGeometry_getGeometryType(swigCPtr, this));
	}

	public boolean ScrPointSelectAt(CPoint pt, stGEOOBJPICKINDEX pkIndex) {
		return elecchartcoreJNI.CVCFGeometry_ScrPointSelectAt(swigCPtr, this,
				CPoint.getCPtr(pt), pt, stGEOOBJPICKINDEX.getCPtr(pkIndex),
				pkIndex);
	}

	public void setEnvelope(stGEOENVELOPE stEnvelope) {
		elecchartcoreJNI.CVCFGeometry_setEnvelope(swigCPtr, this,
				stGEOENVELOPE.getCPtr(stEnvelope), stEnvelope);
	}

	public void getEnvelope(stGEOENVELOPE stEnvelope) {
		elecchartcoreJNI.CVCFGeometry_getEnvelope(swigCPtr, this,
				stGEOENVELOPE.getCPtr(stEnvelope), stEnvelope);
	}

	public boolean Intersects(stGEOENVELOPE stEnvelope) {
		return elecchartcoreJNI.CVCFGeometry_Intersects(swigCPtr, this,
				stGEOENVELOPE.getCPtr(stEnvelope), stEnvelope);
	}

	public int getCoordinateDimension() {
		return elecchartcoreJNI.CVCFGeometry_getCoordinateDimension(swigCPtr,
				this);
	}

	public void setCoordinateDimension(int nDimension) {
		elecchartcoreJNI.CVCFGeometry_setCoordinateDimension(swigCPtr, this,
				nDimension);
	}

	public void setSelect(boolean bIsSel) {
		elecchartcoreJNI.CVCFGeometry_setSelect(swigCPtr, this, bIsSel);
	}

	public boolean getSelect() {
		return elecchartcoreJNI.CVCFGeometry_getSelect(swigCPtr, this);
	}

}
