/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CVCFGeoEdge extends CVCFGeometry {
	private long swigCPtr;

	protected CVCFGeoEdge(long cPtr, boolean cMemoryOwn) {
		super(elecchartcoreJNI.CVCFGeoEdge_SWIGUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CVCFGeoEdge obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CVCFGeoEdge(swigCPtr);
			}
			swigCPtr = 0;
		}
		super.delete();
	}

	public CVCFGeoEdge() {
		this(elecchartcoreJNI.new_CVCFGeoEdge__SWIG_0(), true);
	}

	public CVCFGeoEdge(CVCFGeoEdge arg0) {
		this(elecchartcoreJNI.new_CVCFGeoEdge__SWIG_1(
				CVCFGeoEdge.getCPtr(arg0), arg0), true);
	}

	public xhfGeometryType getGeometryType() {
		return xhfGeometryType.swigToEnum(elecchartcoreJNI
				.CVCFGeoEdge_getGeometryType(swigCPtr, this));
	}

	public boolean ScrPointSelectAt(CPoint pt, stGEOOBJPICKINDEX pkIndex) {
		return elecchartcoreJNI.CVCFGeoEdge_ScrPointSelectAt(swigCPtr, this,
				CPoint.getCPtr(pt), pt, stGEOOBJPICKINDEX.getCPtr(pkIndex),
				pkIndex);
	}

	public int getNumPoints() {
		return elecchartcoreJNI.CVCFGeoEdge_getNumPoints(swigCPtr, this);
	}

	public void getPoint(int arg0, CVCFGeoPoint arg1) {
		elecchartcoreJNI.CVCFGeoEdge_getPoint(swigCPtr, this, arg0,
				CVCFGeoPoint.getCPtr(arg1), arg1);
	}

	public double getX(int i) {
		return elecchartcoreJNI.CVCFGeoEdge_getX(swigCPtr, this, i);
	}

	public double getY(int i) {
		return elecchartcoreJNI.CVCFGeoEdge_getY(swigCPtr, this, i);
	}

	public double getZ(int i) {
		return elecchartcoreJNI.CVCFGeoEdge_getZ(swigCPtr, this, i);
	}

	public void Make3DCorrd() {
		elecchartcoreJNI.CVCFGeoEdge_Make3DCorrd(swigCPtr, this);
	}

	public void Make2DCorrd() {
		elecchartcoreJNI.CVCFGeoEdge_Make2DCorrd(swigCPtr, this);
	}

	public void setNumPoints(int arg0) {
		elecchartcoreJNI.CVCFGeoEdge_setNumPoints(swigCPtr, this, arg0);
	}

	public void setPoint(int arg0, CVCFGeoPoint arg1) {
		elecchartcoreJNI.CVCFGeoEdge_setPoint__SWIG_0(swigCPtr, this, arg0,
				CVCFGeoPoint.getCPtr(arg1), arg1);
	}

	public void setPoint(int arg0, double arg1, double arg2) {
		elecchartcoreJNI.CVCFGeoEdge_setPoint__SWIG_1(swigCPtr, this, arg0,
				arg1, arg2);
	}

	public void setPoint(int arg0, double arg1, double arg2, double arg3) {
		elecchartcoreJNI.CVCFGeoEdge_setPoint__SWIG_2(swigCPtr, this, arg0,
				arg1, arg2, arg3);
	}

	public void setPoints(int arg0, CGeo2DPoint arg1, SWIGTYPE_p_double arg2) {
		elecchartcoreJNI.CVCFGeoEdge_setPoints__SWIG_0(swigCPtr, this, arg0,
				CGeo2DPoint.getCPtr(arg1), arg1,
				SWIGTYPE_p_double.getCPtr(arg2));
	}

	public void setPoints(int arg0, CGeo2DPoint arg1) {
		elecchartcoreJNI.CVCFGeoEdge_setPoints__SWIG_1(swigCPtr, this, arg0,
				CGeo2DPoint.getCPtr(arg1), arg1);
	}

	public void setPoints(int arg0, SWIGTYPE_p_double padfX,
			SWIGTYPE_p_double padfY, SWIGTYPE_p_double padfZ) {
		elecchartcoreJNI.CVCFGeoEdge_setPoints__SWIG_2(swigCPtr, this, arg0,
				SWIGTYPE_p_double.getCPtr(padfX),
				SWIGTYPE_p_double.getCPtr(padfY),
				SWIGTYPE_p_double.getCPtr(padfZ));
	}

	public void setPoints(int arg0, SWIGTYPE_p_double padfX,
			SWIGTYPE_p_double padfY) {
		elecchartcoreJNI.CVCFGeoEdge_setPoints__SWIG_3(swigCPtr, this, arg0,
				SWIGTYPE_p_double.getCPtr(padfX),
				SWIGTYPE_p_double.getCPtr(padfY));
	}

	public void addPoint(CVCFGeoPoint arg0) {
		elecchartcoreJNI.CVCFGeoEdge_addPoint__SWIG_0(swigCPtr, this,
				CVCFGeoPoint.getCPtr(arg0), arg0);
	}

	public void addPoint(double arg0, double arg1) {
		elecchartcoreJNI.CVCFGeoEdge_addPoint__SWIG_1(swigCPtr, this, arg0,
				arg1);
	}

	public void addPoint(double arg0, double arg1, double arg2) {
		elecchartcoreJNI.CVCFGeoEdge_addPoint__SWIG_2(swigCPtr, this, arg0,
				arg1, arg2);
	}

	public void getPoints(CGeo2DPoint arg0, SWIGTYPE_p_double arg1) {
		elecchartcoreJNI.CVCFGeoEdge_getPoints__SWIG_0(swigCPtr, this,
				CGeo2DPoint.getCPtr(arg0), arg0,
				SWIGTYPE_p_double.getCPtr(arg1));
	}

	public void getPoints(CGeo2DPoint arg0) {
		elecchartcoreJNI.CVCFGeoEdge_getPoints__SWIG_1(swigCPtr, this,
				CGeo2DPoint.getCPtr(arg0), arg0);
	}

	public int getNumlPoints() {
		return elecchartcoreJNI.CVCFGeoEdge_getNumlPoints(swigCPtr, this);
	}

	public void setNumlPoints(int arg0) {
		elecchartcoreJNI.CVCFGeoEdge_setNumlPoints(swigCPtr, this, arg0);
	}

	public int getlX(int i) {
		return elecchartcoreJNI.CVCFGeoEdge_getlX(swigCPtr, this, i);
	}

	public int getlY(int i) {
		return elecchartcoreJNI.CVCFGeoEdge_getlY(swigCPtr, this, i);
	}

	public void setlPoint(int arg0, int arg1, int arg2) {
		elecchartcoreJNI
				.CVCFGeoEdge_setlPoint(swigCPtr, this, arg0, arg1, arg2);
	}

	public void addlPoint(int arg0, int arg1) {
		elecchartcoreJNI.CVCFGeoEdge_addlPoint(swigCPtr, this, arg0, arg1);
	}

}
