/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class CxhfIntegerSet {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected CxhfIntegerSet(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(CxhfIntegerSet obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_CxhfIntegerSet(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public CxhfIntegerSet() {
		this(elecchartcoreJNI.new_CxhfIntegerSet(), true);
	}

	public int GetIntergerNums() {
		return elecchartcoreJNI.CxhfIntegerSet_GetIntergerNums(swigCPtr, this);
	}

	public void AddInteger(int nInteger) {
		elecchartcoreJNI.CxhfIntegerSet_AddInteger(swigCPtr, this, nInteger);
	}

	public int GetInteger(int nIndex) {
		return elecchartcoreJNI.CxhfIntegerSet_GetInteger(swigCPtr, this,
				nIndex);
	}

	public void RemoveAllIntegers() {
		elecchartcoreJNI.CxhfIntegerSet_RemoveAllIntegers(swigCPtr, this);
	}

}
