/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class elecchartcore implements elecchartcoreConstants {
	public static double getG_tool_e() {
		return elecchartcoreJNI.g_tool_e_get();
	}

	public static double getG_tool_e2() {
		return elecchartcoreJNI.g_tool_e2_get();
	}

	public static double getG_tool_a() {
		return elecchartcoreJNI.g_tool_a_get();
	}

	public static double getG_tool_Ru() {
		return elecchartcoreJNI.g_tool_Ru_get();
	}

	public static double getG_tool_M_PI() {
		return elecchartcoreJNI.g_tool_M_PI_get();
	}

	public static double getG_tool_M_PI_4() {
		return elecchartcoreJNI.g_tool_M_PI_4_get();
	}

	public static double getG_tool_Ua() {
		return elecchartcoreJNI.g_tool_Ua_get();
	}

	public static double getG_tool_Uc() {
		return elecchartcoreJNI.g_tool_Uc_get();
	}

	public static double F_Mercator(double fa) {
		return elecchartcoreJNI.F_Mercator(fa);
	}

	public static double getN(double fa) {
		return elecchartcoreJNI.getN(fa);
	}

	public static SWIGTYPE_p_a_4__unsigned_long getVCFCOLORPALETTE() {
		long cPtr = elecchartcoreJNI.VCFCOLORPALETTE_get();
		return (cPtr == 0) ? null : new SWIGTYPE_p_a_4__unsigned_long(cPtr,
				false);
	}

	public static int StrntoScanInt(String pszString, int nMaxChars) {
		return elecchartcoreJNI.StrntoScanInt(pszString, nMaxChars);
	}

	public static SWIGTYPE_p_void xhfMalloc(long nSize) {
		long cPtr = elecchartcoreJNI.xhfMalloc(nSize);
		return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
	}

	public static void xhfFree(SWIGTYPE_p_void pData) {
		elecchartcoreJNI.xhfFree(SWIGTYPE_p_void.getCPtr(pData));
	}

	public static String xhfStrdup(String pszString) {
		return elecchartcoreJNI.xhfStrdup(pszString);
	}

	public static void charSafeStrncpy(String pDest, String pSource, int nCount) {
		elecchartcoreJNI.charSafeStrncpy(pDest, pSource, nCount);
	}

	public static void charSafeStrcat(String pDest, String pSource, int nDestLen) {
		elecchartcoreJNI.charSafeStrcat(pDest, pSource, nDestLen);
	}

	public static SWIGTYPE_p_void xhfRealloc(SWIGTYPE_p_void pData,
			long nNewSize) {
		long cPtr = elecchartcoreJNI.xhfRealloc(SWIGTYPE_p_void.getCPtr(pData),
				nNewSize);
		return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
	}

	public static void xhfDestroy(SWIGTYPE_p_p_char papszStrList) {
		elecchartcoreJNI.xhfDestroy(SWIGTYPE_p_p_char.getCPtr(papszStrList));
	}

	public static int xhfFindcharCRightPosition(String pszSrcStr, char pszSubC) {
		return elecchartcoreJNI.xhfFindcharCRightPosition(pszSrcStr, pszSubC);
	}

	public static int xhfFindcharCLeftPosition(String pszSrcStr, char pszSubC) {
		return elecchartcoreJNI.xhfFindcharCLeftPosition(pszSrcStr, pszSubC);
	}

	public static int xhfSafeExactitudeCopy(String pszDest, String pszSrc,
			int nStart, int nCount) {
		return elecchartcoreJNI.xhfSafeExactitudeCopy(pszDest, pszSrc, nStart,
				nCount);
	}

	public static int xhfSplitFileNameFromFilePath(String pszFileName,
			String pszFilePath) {
		return elecchartcoreJNI.xhfSplitFileNameFromFilePath(pszFileName,
				pszFilePath);
	}

	public static int xhfSplitNoDotNameFromFileName(String pszName,
			String pszFileName) {
		return elecchartcoreJNI.xhfSplitNoDotNameFromFileName(pszName,
				pszFileName);
	}

	public static int xhfSplitPathFromFilePath(String pszPath,
			String pszFilePath) {
		return elecchartcoreJNI.xhfSplitPathFromFilePath(pszPath, pszFilePath);
	}

	public static int xhfStrCompare(String pDes, String pSrc) {
		return elecchartcoreJNI.xhfStrCompare(pDes, pSrc);
	}

	public static int xhfStrlength(String pszStr) {
		return elecchartcoreJNI.xhfStrlength(pszStr);
	}

	public static String xhfStrTrim(String src) {
		return elecchartcoreJNI.xhfStrTrim(src);
	}

	public static String xhfStrTrimLeft(String src) {
		return elecchartcoreJNI.xhfStrTrimLeft(src);
	}

	public static String xhfUTFStrTrim(String src) {
		return elecchartcoreJNI.xhfUTFStrTrim(src);
	}

	public static void setG_SysDataWorkDirectory(String value) {
		elecchartcoreJNI.g_SysDataWorkDirectory_set(value);
	}

	public static String getG_SysDataWorkDirectory() {
		return elecchartcoreJNI.g_SysDataWorkDirectory_get();
	}

	public static void setG_GeoProjection(CHfGeoProjection value) {
		elecchartcoreJNI.g_GeoProjection_set(CHfGeoProjection.getCPtr(value),
				value);
	}

	public static CHfGeoProjection getG_GeoProjection() {
		long cPtr = elecchartcoreJNI.g_GeoProjection_get();
		return (cPtr == 0) ? null : new CHfGeoProjection(cPtr, false);
	}

	public static void setG_vcfGeoCanvas(CHfVCFGeoCanvas value) {
		elecchartcoreJNI.g_vcfGeoCanvas_set(CHfVCFGeoCanvas.getCPtr(value),
				value);
	}

	public static CHfVCFGeoCanvas getG_vcfGeoCanvas() {
		long cPtr = elecchartcoreJNI.g_vcfGeoCanvas_get();
		return (cPtr == 0) ? null : new CHfVCFGeoCanvas(cPtr, false);
	}

	public static void setG_vcfDataDictionary(CVCFDataDictionary value) {
		elecchartcoreJNI.g_vcfDataDictionary_set(
				CVCFDataDictionary.getCPtr(value), value);
	}

	public static CVCFDataDictionary getG_vcfDataDictionary() {
		long cPtr = elecchartcoreJNI.g_vcfDataDictionary_get();
		return (cPtr == 0) ? null : new CVCFDataDictionary(cPtr, false);
	}

	public static void setG_vcfSencManageModul(CVcfSencManageModul value) {
		elecchartcoreJNI.g_vcfSencManageModul_set(
				CVcfSencManageModul.getCPtr(value), value);
	}

	public static CVcfSencManageModul getG_vcfSencManageModul() {
		long cPtr = elecchartcoreJNI.g_vcfSencManageModul_get();
		return (cPtr == 0) ? null : new CVcfSencManageModul(cPtr, false);
	}

	public static void setG_vcfGeoSymbolize(CHfVCFGeoSymbolization value) {
		elecchartcoreJNI.g_vcfGeoSymbolize_set(
				CHfVCFGeoSymbolization.getCPtr(value), value);
	}

	public static CHfVCFGeoSymbolization getG_vcfGeoSymbolize() {
		long cPtr = elecchartcoreJNI.g_vcfGeoSymbolize_get();
		return (cPtr == 0) ? null : new CHfVCFGeoSymbolization(cPtr, false);
	}

	public static void setG_vcfSymbolLib(CHfVCFSymbolLib value) {
		elecchartcoreJNI.g_vcfSymbolLib_set(CHfVCFSymbolLib.getCPtr(value),
				value);
	}

	public static CHfVCFSymbolLib getG_vcfSymbolLib() {
		long cPtr = elecchartcoreJNI.g_vcfSymbolLib_get();
		return (cPtr == 0) ? null : new CHfVCFSymbolLib(cPtr, false);
	}

	public static void setG_vcfLookupTable(CVCFSymLookupTable value) {
		elecchartcoreJNI.g_vcfLookupTable_set(
				CVCFSymLookupTable.getCPtr(value), value);
	}

	public static CVCFSymLookupTable getG_vcfLookupTable() {
		long cPtr = elecchartcoreJNI.g_vcfLookupTable_get();
		return (cPtr == 0) ? null : new CVCFSymLookupTable(cPtr, false);
	}

	public static void setG_vcfGeoDatabase(CVCFGeoDatabase value) {
		elecchartcoreJNI.g_vcfGeoDatabase_set(CVCFGeoDatabase.getCPtr(value),
				value);
	}

	public static CVCFGeoDatabase getG_vcfGeoDatabase() {
		long cPtr = elecchartcoreJNI.g_vcfGeoDatabase_get();
		return (cPtr == 0) ? null : new CVCFGeoDatabase(cPtr, false);
	}

	public static void setG_vcfPresentationLib(CHfVCFPresentationLib value) {
		elecchartcoreJNI.g_vcfPresentationLib_set(
				CHfVCFPresentationLib.getCPtr(value), value);
	}

	public static CHfVCFPresentationLib getG_vcfPresentationLib() {
		long cPtr = elecchartcoreJNI.g_vcfPresentationLib_get();
		return (cPtr == 0) ? null : new CHfVCFPresentationLib(cPtr, false);
	}

	public static void setG_vcfLogManage(CHFLogManage value) {
		elecchartcoreJNI.g_vcfLogManage_set(CHFLogManage.getCPtr(value), value);
	}

	public static CHFLogManage getG_vcfLogManage() {
		long cPtr = elecchartcoreJNI.g_vcfLogManage_get();
		return (cPtr == 0) ? null : new CHFLogManage(cPtr, false);
	}

}
