/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public interface elecchartcoreConstants {
	public final static int MARKGEO = elecchartcoreJNI.MARKGEO_get();
	public final static int ANVGPTP = elecchartcoreJNI.ANVGPTP_get();
	public final static int AREANT_1 = elecchartcoreJNI.AREANT_1_get();
	public final static int AREANT_2 = elecchartcoreJNI.AREANT_2_get();
	public final static int AREANT_3 = elecchartcoreJNI.AREANT_3_get();
	public final static int AREANT_4 = elecchartcoreJNI.AREANT_4_get();
	public final static int AREANT_5 = elecchartcoreJNI.AREANT_5_get();
	public final static int AREANTL = elecchartcoreJNI.AREANTL_get();
	public final static int AREAPTP = elecchartcoreJNI.AREAPTP_get();
	public final static int BULDNT_1 = elecchartcoreJNI.BULDNT_1_get();
	public final static int BULDNTL = elecchartcoreJNI.BULDNTL_get();
	public final static int BULDPTP = elecchartcoreJNI.BULDPTP_get();
	public final static int CINDNT_1 = elecchartcoreJNI.CINDNT_1_get();
	public final static int CINDNTL = elecchartcoreJNI.CINDNTL_get();
	public final static int CTRLPTP = elecchartcoreJNI.CTRLPTP_get();
	public final static int ANNCOVP = elecchartcoreJNI.ANNCOVP_get();
	public final static int ANNCOVL = elecchartcoreJNI.ANNCOVL_get();
	public final static int DOCUNTL = elecchartcoreJNI.DOCUNTL_get();
	public final static int DRNGNTA = elecchartcoreJNI.DRNGNTA_get();
	public final static int DRNGNTL = elecchartcoreJNI.DRNGNTL_get();
	public final static int DRNGPTP = elecchartcoreJNI.DRNGPTP_get();
	public final static int LDMKNTA = elecchartcoreJNI.LDMKNTA_get();
	public final static int LDMKNTL = elecchartcoreJNI.LDMKNTL_get();
	public final static int LDMKPTP = elecchartcoreJNI.LDMKPTP_get();
	public final static int OBSTNT_1 = elecchartcoreJNI.OBSTNT_1_get();
	public final static int OBSTNTL = elecchartcoreJNI.OBSTNTL_get();
	public final static int OBSTPTP = elecchartcoreJNI.OBSTPTP_get();
	public final static int OCLDNT_1 = elecchartcoreJNI.OCLDNT_1_get();
	public final static int OCLDNTA = elecchartcoreJNI.OCLDNTA_get();
	public final static int OCLDNTL = elecchartcoreJNI.OCLDNTL_get();
	public final static int OCLDPTP = elecchartcoreJNI.OCLDPTP_get();
	public final static int OINTNT_1 = elecchartcoreJNI.OINTNT_1_get();
	public final static int OINTNTL = elecchartcoreJNI.OINTNTL_get();
	public final static int PORTNTA = elecchartcoreJNI.PORTNTA_get();
	public final static int PORTNTL = elecchartcoreJNI.PORTNTL_get();
	public final static int PORTPTP = elecchartcoreJNI.PORTPTP_get();
	public final static int RELFNTL = elecchartcoreJNI.RELFNTL_get();
	public final static int RELFPTP = elecchartcoreJNI.RELFPTP_get();
	public final static int SERVPTP = elecchartcoreJNI.SERVPTP_get();
	public final static int SOUDPTP = elecchartcoreJNI.SOUDPTP_get();
	public final static int TDMGPLL = elecchartcoreJNI.TDMGPLL_get();
	public final static int TDMGPLP = elecchartcoreJNI.TDMGPLP_get();
	public final static int TRAKNT_1 = elecchartcoreJNI.TRAKNT_1_get();
	public final static int TRAKNTL = elecchartcoreJNI.TRAKNTL_get();
	public final static int TRAKPTP = elecchartcoreJNI.TRAKPTP_get();
	public final static int TRSPNT_1 = elecchartcoreJNI.TRSPNT_1_get();
	public final static int TRSPNTL = elecchartcoreJNI.TRSPNTL_get();
	public final static int TRSPPLL = elecchartcoreJNI.TRSPPLL_get();
	public final static int TRSPPLP = elecchartcoreJNI.TRSPPLP_get();
	public final static int UTLTPLL = elecchartcoreJNI.UTLTPLL_get();
	public final static int UTLTPLP = elecchartcoreJNI.UTLTPLP_get();
	public final static int UNKNGEO = elecchartcoreJNI.UNKNGEO_get();
	public final static int GEOLNUM = elecchartcoreJNI.GEOLNUM_get();
	public final static int VCF_DISPLAY_BASE = elecchartcoreJNI
			.VCF_DISPLAY_BASE_get();
	public final static int VCF_DISPLAY_STANDARD = elecchartcoreJNI
			.VCF_DISPLAY_STANDARD_get();
	public final static int VCF_DISPLAY_ALL = elecchartcoreJNI
			.VCF_DISPLAY_ALL_get();
	public final static int VCF_DISPLAY_LAYER = elecchartcoreJNI
			.VCF_DISPLAY_LAYER_get();
	public final static int COLOR_MODE_DAY = elecchartcoreJNI
			.COLOR_MODE_DAY_get();
	public final static int COLOR_MODE_SUN = elecchartcoreJNI
			.COLOR_MODE_SUN_get();
	public final static int COLOR_MODE_DUSK = elecchartcoreJNI
			.COLOR_MODE_DUSK_get();
	public final static int COLOR_MODE_NIGHT = elecchartcoreJNI
			.COLOR_MODE_NIGHT_get();
	public final static int COLOR_MODE_RAIN = elecchartcoreJNI
			.COLOR_MODE_RAIN_get();
	public final static int COLOR_MODE_S52 = elecchartcoreJNI
			.COLOR_MODE_S52_get();
	public final static int CHART_NORTH_UP = elecchartcoreJNI
			.CHART_NORTH_UP_get();
	public final static int CHART_HEAD_UP = elecchartcoreJNI
			.CHART_HEAD_UP_get();
	public final static int CHART_COURSE_UP = elecchartcoreJNI
			.CHART_COURSE_UP_get();
	public final static int CHART_NAVLEG_UP = elecchartcoreJNI
			.CHART_NAVLEG_UP_get();
	public final static int DESIGNA_SINGL_CHART = elecchartcoreJNI
			.DESIGNA_SINGL_CHART_get();
	public final static int DESIGNA_MULTI_CHART = elecchartcoreJNI
			.DESIGNA_MULTI_CHART_get();
	public final static int FREEDOM_AUTOM_CHART = elecchartcoreJNI
			.FREEDOM_AUTOM_CHART_get();
	public final static int LONGLAT_DFM_MODE = elecchartcoreJNI
			.LONGLAT_DFM_MODE_get();
	public final static int LONGLAT_DF_MODE = elecchartcoreJNI
			.LONGLAT_DF_MODE_get();
	public final static int VCF_COLOR_BLACK = elecchartcoreJNI
			.VCF_COLOR_BLACK_get();
	public final static int VCF_COLOR_WHITE = elecchartcoreJNI
			.VCF_COLOR_WHITE_get();
	public final static int VCF_COLOR_RED = elecchartcoreJNI
			.VCF_COLOR_RED_get();
	public final static int VCF_COLOR_RED_LIGHT = elecchartcoreJNI
			.VCF_COLOR_RED_LIGHT_get();
	public final static int VCF_COLOR_GREEN = elecchartcoreJNI
			.VCF_COLOR_GREEN_get();
	public final static int VCF_COLOR_GREEN_LIGHT = elecchartcoreJNI
			.VCF_COLOR_GREEN_LIGHT_get();
	public final static int VCF_COLOR_BLUE = elecchartcoreJNI
			.VCF_COLOR_BLUE_get();
	public final static int VCF_COLOR_BLUE_LIGHT = elecchartcoreJNI
			.VCF_COLOR_BLUE_LIGHT_get();
	public final static int VCF_COLOR_CYAN = elecchartcoreJNI
			.VCF_COLOR_CYAN_get();
	public final static int VCF_COLOR_CYAN_LIGHT = elecchartcoreJNI
			.VCF_COLOR_CYAN_LIGHT_get();
	public final static int VCF_COLOR_YELLOW_DARK = elecchartcoreJNI
			.VCF_COLOR_YELLOW_DARK_get();
	public final static int VCF_COLOR_YELLOW = elecchartcoreJNI
			.VCF_COLOR_YELLOW_get();
	public final static int VCF_COLOR_BUFF = elecchartcoreJNI
			.VCF_COLOR_BUFF_get();
	public final static int VCF_COLOR_BROWN = elecchartcoreJNI
			.VCF_COLOR_BROWN_get();
	public final static int VCF_COLOR_MAGENTA = elecchartcoreJNI
			.VCF_COLOR_MAGENTA_get();
	public final static int VCF_COLOR_MAGENTA_LIGHT = elecchartcoreJNI
			.VCF_COLOR_MAGENTA_LIGHT_get();
	public final static int VCF_COLOR_BEIGE = elecchartcoreJNI
			.VCF_COLOR_BEIGE_get();
	public final static int HS_HORIZONTAL = elecchartcoreJNI
			.HS_HORIZONTAL_get();
	public final static int HS_BDIAGONAL = elecchartcoreJNI.HS_BDIAGONAL_get();
	public final static int HS_FDIAGONAL = elecchartcoreJNI.HS_FDIAGONAL_get();
	public final static int HS_VERTICAL = elecchartcoreJNI.HS_VERTICAL_get();
	public final static boolean TRUE = elecchartcoreJNI.TRUE_get();
	public final static boolean FALSE = elecchartcoreJNI.FALSE_get();
	public final static double PI = elecchartcoreJNI.PI_get();
	public final static int SENC_HEADER_LEN = elecchartcoreJNI
			.SENC_HEADER_LEN_get();
	public final static int FILENAME_LEN = elecchartcoreJNI.FILENAME_LEN_get();
	public final static int FILE_PATH_MAX_LEN = elecchartcoreJNI
			.FILE_PATH_MAX_LEN_get();
	public final static int SYS_FILEPATH_MAX_LEN = elecchartcoreJNI
			.SYS_FILEPATH_MAX_LEN_get();
	public final static int GEOERR_NONE = elecchartcoreJNI.GEOERR_NONE_get();
	public final static int GEOERR_NOT_ENOUGH_DATA = elecchartcoreJNI
			.GEOERR_NOT_ENOUGH_DATA_get();
	public final static int GEOERR_NOT_ENOUGH_MEMORY = elecchartcoreJNI
			.GEOERR_NOT_ENOUGH_MEMORY_get();
	public final static int GEOERR_UNSUPPORTED_GEOMETRY_TYPE = elecchartcoreJNI
			.GEOERR_UNSUPPORTED_GEOMETRY_TYPE_get();
	public final static int GEOERR_UNSUPPORTED_OPERATION = elecchartcoreJNI
			.GEOERR_UNSUPPORTED_OPERATION_get();
	public final static int GEOERR_CORRUPT_DATA = elecchartcoreJNI
			.GEOERR_CORRUPT_DATA_get();
	public final static int GEOERR_FAILURE = elecchartcoreJNI
			.GEOERR_FAILURE_get();
	public final static int GEOERR_UNSUPPORTED_SRS = elecchartcoreJNI
			.GEOERR_UNSUPPORTED_SRS_get();
	public final static int GEOERR_INVALID_HANDLE = elecchartcoreJNI
			.GEOERR_INVALID_HANDLE_get();
	public final static int geometry25DBit = elecchartcoreJNI
			.geometry25DBit_get();
	public final static int COM_TX_MAX_LENGTH = elecchartcoreJNI
			.COM_TX_MAX_LENGTH_get();
	public final static int COM_RX_MAX_LENGTH = elecchartcoreJNI
			.COM_RX_MAX_LENGTH_get();
	public final static int NEMA_SEN_MAX_LENGTH = elecchartcoreJNI
			.NEMA_SEN_MAX_LENGTH_get();
	public final static int NEMA_SEN_MIN_LENGTH = elecchartcoreJNI
			.NEMA_SEN_MIN_LENGTH_get();
	public final static int UAIS_SEN_MAX_LENGTH = elecchartcoreJNI
			.UAIS_SEN_MAX_LENGTH_get();
	public final static int UAIS_SEN_MIN_LENGTH = elecchartcoreJNI
			.UAIS_SEN_MIN_LENGTH_get();
	public final static int UAIS_SUBSEN_MAX_NUM = elecchartcoreJNI
			.UAIS_SUBSEN_MAX_NUM_get();
	public final static int UAIS_SUNSEN_MAX_LEN = elecchartcoreJNI
			.UAIS_SUNSEN_MAX_LEN_get();
	public final static char NEMA_STANDAD_HEAD = elecchartcoreJNI
			.NEMA_STANDAD_HEAD_get();
	public final static char UAIS_STANDAD_HEAD = elecchartcoreJNI
			.UAIS_STANDAD_HEAD_get();
	public final static char NEMA_STANDAD_HEAD_1 = elecchartcoreJNI
			.NEMA_STANDAD_HEAD_1_get();
	public final static char NEMA_STANDAD_HEAD_2 = elecchartcoreJNI
			.NEMA_STANDAD_HEAD_2_get();
	public final static char UAIS_STANDAD_HEAD_1 = elecchartcoreJNI
			.UAIS_STANDAD_HEAD_1_get();
	public final static char UAIS_STANDAD_HEAD_2 = elecchartcoreJNI
			.UAIS_STANDAD_HEAD_2_get();
	public final static char SELF_DEFINED_HEAD_1 = elecchartcoreJNI
			.SELF_DEFINED_HEAD_1_get();
	public final static char NEMA_SPLIT_FLAG = elecchartcoreJNI
			.NEMA_SPLIT_FLAG_get();
	public final static char NEMA_STANDAD_CHECK = elecchartcoreJNI
			.NEMA_STANDAD_CHECK_get();
	public final static char NEMA_STANDAD_TAIL_1 = elecchartcoreJNI
			.NEMA_STANDAD_TAIL_1_get();
	public final static char NEMA_STANDAD_TAIL_2 = elecchartcoreJNI
			.NEMA_STANDAD_TAIL_2_get();
	public final static int NEMA_TAIL_LENGTH = elecchartcoreJNI
			.NEMA_TAIL_LENGTH_get();
	public final static int STANDAD_COMMI = elecchartcoreJNI
			.STANDAD_COMMI_get();
	public final static int SELFDEF_COMMI = elecchartcoreJNI
			.SELFDEF_COMMI_get();
	public final static String NEMA_STANDARD_GPGGA = elecchartcoreJNI
			.NEMA_STANDARD_GPGGA_get();
	public final static String NEMA_STANDARD_GPGSA = elecchartcoreJNI
			.NEMA_STANDARD_GPGSA_get();
	public final static String NEMA_STANDARD_GPGSV = elecchartcoreJNI
			.NEMA_STANDARD_GPGSV_get();
	public final static String NEMA_STANDARD_GPRMC = elecchartcoreJNI
			.NEMA_STANDARD_GPRMC_get();
	public final static String NEMA_STANDARD_GPVTG = elecchartcoreJNI
			.NEMA_STANDARD_GPVTG_get();
	public final static String NEMA_STANDARD_GPGLL = elecchartcoreJNI
			.NEMA_STANDARD_GPGLL_get();
	public final static String NEMA_STANDARD_GPZDA = elecchartcoreJNI
			.NEMA_STANDARD_GPZDA_get();
	public final static String NEMA_STANDARD_GPDTM = elecchartcoreJNI
			.NEMA_STANDARD_GPDTM_get();
	public final static String UAIS_STANDARD_AIVDM = elecchartcoreJNI
			.UAIS_STANDARD_AIVDM_get();
	public final static String UAIS_STANDARD_AIVDO = elecchartcoreJNI
			.UAIS_STANDARD_AIVDO_get();
	public final static String UAIS_STANDARD_AIRMC = elecchartcoreJNI
			.UAIS_STANDARD_AIRMC_get();
	public final static String UAIS_STANDARD_AITXT = elecchartcoreJNI
			.UAIS_STANDARD_AITXT_get();
	public final static String UAIS_STANDARD_AIABK = elecchartcoreJNI
			.UAIS_STANDARD_AIABK_get();
	public final static String UAIS_STANDARD_AIACA = elecchartcoreJNI
			.UAIS_STANDARD_AIACA_get();
	public final static String UAIS_STANDARD_AIACS = elecchartcoreJNI
			.UAIS_STANDARD_AIACS_get();
	public final static String UAIS_STANDARD_AIALR = elecchartcoreJNI
			.UAIS_STANDARD_AIALR_get();
}
