/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public final class emCHART_CANVAS_FLUSHTYPE {
	public final static emCHART_CANVAS_FLUSHTYPE CANVAS_REDRAW = new emCHART_CANVAS_FLUSHTYPE(
			"CANVAS_REDRAW", elecchartcoreJNI.CANVAS_REDRAW_get());
	public final static emCHART_CANVAS_FLUSHTYPE CANVAS_FLUSH = new emCHART_CANVAS_FLUSHTYPE(
			"CANVAS_FLUSH");
	public final static emCHART_CANVAS_FLUSHTYPE CANVAS_SCREEN = new emCHART_CANVAS_FLUSHTYPE(
			"CANVAS_SCREEN");
	public final static emCHART_CANVAS_FLUSHTYPE CANVAS_PICK = new emCHART_CANVAS_FLUSHTYPE(
			"CANVAS_PICK");
	public final static emCHART_CANVAS_FLUSHTYPE CANVAS_CRINIT = new emCHART_CANVAS_FLUSHTYPE(
			"CANVAS_CRINIT");

	public final int swigValue() {
		return swigValue;
	}

	public String toString() {
		return swigName;
	}

	public static emCHART_CANVAS_FLUSHTYPE swigToEnum(int swigValue) {
		if (swigValue < swigValues.length && swigValue >= 0
				&& swigValues[swigValue].swigValue == swigValue)
			return swigValues[swigValue];
		for (int i = 0; i < swigValues.length; i++)
			if (swigValues[i].swigValue == swigValue)
				return swigValues[i];
		throw new IllegalArgumentException("No enum "
				+ emCHART_CANVAS_FLUSHTYPE.class + " with value " + swigValue);
	}

	private emCHART_CANVAS_FLUSHTYPE(String swigName) {
		this.swigName = swigName;
		this.swigValue = swigNext++;
	}

	private emCHART_CANVAS_FLUSHTYPE(String swigName, int swigValue) {
		this.swigName = swigName;
		this.swigValue = swigValue;
		swigNext = swigValue + 1;
	}

	private emCHART_CANVAS_FLUSHTYPE(String swigName,
			emCHART_CANVAS_FLUSHTYPE swigEnum) {
		this.swigName = swigName;
		this.swigValue = swigEnum.swigValue;
		swigNext = this.swigValue + 1;
	}

	private static emCHART_CANVAS_FLUSHTYPE[] swigValues = { CANVAS_REDRAW,
			CANVAS_FLUSH, CANVAS_SCREEN, CANVAS_PICK, CANVAS_CRINIT };
	private static int swigNext = 0;
	private final int swigValue;
	private final String swigName;
}
