/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public final class emGPSPOS_CORRECT_MODE {
	public final static emGPSPOS_CORRECT_MODE GPSPOS_NO_CT = new emGPSPOS_CORRECT_MODE(
			"GPSPOS_NO_CT", elecchartcoreJNI.GPSPOS_NO_CT_get());
	public final static emGPSPOS_CORRECT_MODE GPSPOS_TO_ZX = new emGPSPOS_CORRECT_MODE(
			"GPSPOS_TO_ZX");
	public final static emGPSPOS_CORRECT_MODE GPSPOS_TO_JS = new emGPSPOS_CORRECT_MODE(
			"GPSPOS_TO_JS");

	public final int swigValue() {
		return swigValue;
	}

	public String toString() {
		return swigName;
	}

	public static emGPSPOS_CORRECT_MODE swigToEnum(int swigValue) {
		if (swigValue < swigValues.length && swigValue >= 0
				&& swigValues[swigValue].swigValue == swigValue)
			return swigValues[swigValue];
		for (int i = 0; i < swigValues.length; i++)
			if (swigValues[i].swigValue == swigValue)
				return swigValues[i];
		throw new IllegalArgumentException("No enum "
				+ emGPSPOS_CORRECT_MODE.class + " with value " + swigValue);
	}

	private emGPSPOS_CORRECT_MODE(String swigName) {
		this.swigName = swigName;
		this.swigValue = swigNext++;
	}

	private emGPSPOS_CORRECT_MODE(String swigName, int swigValue) {
		this.swigName = swigName;
		this.swigValue = swigValue;
		swigNext = swigValue + 1;
	}

	private emGPSPOS_CORRECT_MODE(String swigName,
			emGPSPOS_CORRECT_MODE swigEnum) {
		this.swigName = swigName;
		this.swigValue = swigEnum.swigValue;
		swigNext = this.swigValue + 1;
	}

	private static emGPSPOS_CORRECT_MODE[] swigValues = { GPSPOS_NO_CT,
			GPSPOS_TO_ZX, GPSPOS_TO_JS };
	private static int swigNext = 0;
	private final int swigValue;
	private final String swigName;
}
