/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public final class emLOLATSHOWSTYLE {
	public final static emLOLATSHOWSTYLE DMS_SHOW_STYLE = new emLOLATSHOWSTYLE(
			"DMS_SHOW_STYLE", elecchartcoreJNI.DMS_SHOW_STYLE_get());
	public final static emLOLATSHOWSTYLE DMM_SHOW_STYLE = new emLOLATSHOWSTYLE(
			"DMM_SHOW_STYLE");
	public final static emLOLATSHOWSTYLE DDD_SHOW_STYLE = new emLOLATSHOWSTYLE(
			"DDD_SHOW_STYLE");

	public final int swigValue() {
		return swigValue;
	}

	public String toString() {
		return swigName;
	}

	public static emLOLATSHOWSTYLE swigToEnum(int swigValue) {
		if (swigValue < swigValues.length && swigValue >= 0
				&& swigValues[swigValue].swigValue == swigValue)
			return swigValues[swigValue];
		for (int i = 0; i < swigValues.length; i++)
			if (swigValues[i].swigValue == swigValue)
				return swigValues[i];
		throw new IllegalArgumentException("No enum " + emLOLATSHOWSTYLE.class
				+ " with value " + swigValue);
	}

	private emLOLATSHOWSTYLE(String swigName) {
		this.swigName = swigName;
		this.swigValue = swigNext++;
	}

	private emLOLATSHOWSTYLE(String swigName, int swigValue) {
		this.swigName = swigName;
		this.swigValue = swigValue;
		swigNext = swigValue + 1;
	}

	private emLOLATSHOWSTYLE(String swigName, emLOLATSHOWSTYLE swigEnum) {
		this.swigName = swigName;
		this.swigValue = swigEnum.swigValue;
		swigNext = this.swigValue + 1;
	}

	private static emLOLATSHOWSTYLE[] swigValues = { DMS_SHOW_STYLE,
			DMM_SHOW_STYLE, DDD_SHOW_STYLE };
	private static int swigNext = 0;
	private final int swigValue;
	private final String swigName;
}
