/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public final class emNAVSHIP_CENTER_MODE {
	public final static emNAVSHIP_CENTER_MODE NAVSHIP_PX = new emNAVSHIP_CENTER_MODE(
			"NAVSHIP_PX", elecchartcoreJNI.NAVSHIP_PX_get());
	public final static emNAVSHIP_CENTER_MODE NAVSHIP_ZX = new emNAVSHIP_CENTER_MODE(
			"NAVSHIP_ZX");
	public final static emNAVSHIP_CENTER_MODE NAVSHIP_BY = new emNAVSHIP_CENTER_MODE(
			"NAVSHIP_BY");

	public final int swigValue() {
		return swigValue;
	}

	public String toString() {
		return swigName;
	}

	public static emNAVSHIP_CENTER_MODE swigToEnum(int swigValue) {
		if (swigValue < swigValues.length && swigValue >= 0
				&& swigValues[swigValue].swigValue == swigValue)
			return swigValues[swigValue];
		for (int i = 0; i < swigValues.length; i++)
			if (swigValues[i].swigValue == swigValue)
				return swigValues[i];
		throw new IllegalArgumentException("No enum "
				+ emNAVSHIP_CENTER_MODE.class + " with value " + swigValue);
	}

	private emNAVSHIP_CENTER_MODE(String swigName) {
		this.swigName = swigName;
		this.swigValue = swigNext++;
	}

	private emNAVSHIP_CENTER_MODE(String swigName, int swigValue) {
		this.swigName = swigName;
		this.swigValue = swigValue;
		swigNext = swigValue + 1;
	}

	private emNAVSHIP_CENTER_MODE(String swigName,
			emNAVSHIP_CENTER_MODE swigEnum) {
		this.swigName = swigName;
		this.swigValue = swigEnum.swigValue;
		swigNext = this.swigValue + 1;
	}

	private static emNAVSHIP_CENTER_MODE[] swigValues = { NAVSHIP_PX,
			NAVSHIP_ZX, NAVSHIP_BY };
	private static int swigNext = 0;
	private final int swigValue;
	private final String swigName;
}
