/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public final class emTELEGRAMTYPE {
	public final static emTELEGRAMTYPE UNK_TELEM = new emTELEGRAMTYPE(
			"UNK_TELEM", elecchartcoreJNI.UNK_TELEM_get());
	public final static emTELEGRAMTYPE GPS_GPRMC = new emTELEGRAMTYPE(
			"GPS_GPRMC");
	public final static emTELEGRAMTYPE GPS_GPGGA = new emTELEGRAMTYPE(
			"GPS_GPGGA");
	public final static emTELEGRAMTYPE AIS_GPRMC = new emTELEGRAMTYPE(
			"AIS_GPRMC");
	public final static emTELEGRAMTYPE HDT_GPHDT = new emTELEGRAMTYPE(
			"HDT_GPHDT");
	public final static emTELEGRAMTYPE AIS_AIVDM = new emTELEGRAMTYPE(
			"AIS_AIVDM");
	public final static emTELEGRAMTYPE AIS_AIVDO = new emTELEGRAMTYPE(
			"AIS_AIVDO");
	public final static emTELEGRAMTYPE AIS_AITXT = new emTELEGRAMTYPE(
			"AIS_AITXT");
	public final static emTELEGRAMTYPE AIS_AIABK = new emTELEGRAMTYPE(
			"AIS_AIABK");
	public final static emTELEGRAMTYPE AIS_AIACA = new emTELEGRAMTYPE(
			"AIS_AIACA");
	public final static emTELEGRAMTYPE AIS_AIACS = new emTELEGRAMTYPE(
			"AIS_AIACS");
	public final static emTELEGRAMTYPE AIS_AIALR = new emTELEGRAMTYPE(
			"AIS_AIALR");
	public final static emTELEGRAMTYPE AIS_AIRMC = new emTELEGRAMTYPE(
			"AIS_AIRMC");
	public final static emTELEGRAMTYPE AIS_VDO_MSG1 = new emTELEGRAMTYPE(
			"AIS_VDO_MSG1");
	public final static emTELEGRAMTYPE AIS_VDO_MSG5 = new emTELEGRAMTYPE(
			"AIS_VDO_MSG5");
	public final static emTELEGRAMTYPE AIS_VDO_MSG18 = new emTELEGRAMTYPE(
			"AIS_VDO_MSG18");
	public final static emTELEGRAMTYPE AIS_VDO_MSG19 = new emTELEGRAMTYPE(
			"AIS_VDO_MSG19");
	public final static emTELEGRAMTYPE AIS_VDM_MSG1 = new emTELEGRAMTYPE(
			"AIS_VDM_MSG1");
	public final static emTELEGRAMTYPE AIS_VDM_MSG5 = new emTELEGRAMTYPE(
			"AIS_VDM_MSG5");
	public final static emTELEGRAMTYPE AIS_VDM_MSG18 = new emTELEGRAMTYPE(
			"AIS_VDM_MSG18");
	public final static emTELEGRAMTYPE AIS_VDM_MSG19 = new emTELEGRAMTYPE(
			"AIS_VDM_MSG19");
	public final static emTELEGRAMTYPE AIS_VDM_MSG21 = new emTELEGRAMTYPE(
			"AIS_VDM_MSG21");
	public final static emTELEGRAMTYPE COM_STATE = new emTELEGRAMTYPE(
			"COM_STATE");

	public final int swigValue() {
		return swigValue;
	}

	public String toString() {
		return swigName;
	}

	public static emTELEGRAMTYPE swigToEnum(int swigValue) {
		if (swigValue < swigValues.length && swigValue >= 0
				&& swigValues[swigValue].swigValue == swigValue)
			return swigValues[swigValue];
		for (int i = 0; i < swigValues.length; i++)
			if (swigValues[i].swigValue == swigValue)
				return swigValues[i];
		throw new IllegalArgumentException("No enum " + emTELEGRAMTYPE.class
				+ " with value " + swigValue);
	}

	private emTELEGRAMTYPE(String swigName) {
		this.swigName = swigName;
		this.swigValue = swigNext++;
	}

	private emTELEGRAMTYPE(String swigName, int swigValue) {
		this.swigName = swigName;
		this.swigValue = swigValue;
		swigNext = swigValue + 1;
	}

	private emTELEGRAMTYPE(String swigName, emTELEGRAMTYPE swigEnum) {
		this.swigName = swigName;
		this.swigValue = swigEnum.swigValue;
		swigNext = this.swigValue + 1;
	}

	private static emTELEGRAMTYPE[] swigValues = { UNK_TELEM, GPS_GPRMC,
			GPS_GPGGA, AIS_GPRMC, HDT_GPHDT, AIS_AIVDM, AIS_AIVDO, AIS_AITXT,
			AIS_AIABK, AIS_AIACA, AIS_AIACS, AIS_AIALR, AIS_AIRMC,
			AIS_VDO_MSG1, AIS_VDO_MSG5, AIS_VDO_MSG18, AIS_VDO_MSG19,
			AIS_VDM_MSG1, AIS_VDM_MSG5, AIS_VDM_MSG18, AIS_VDM_MSG19,
			AIS_VDM_MSG21, COM_STATE };
	private static int swigNext = 0;
	private final int swigValue;
	private final String swigName;
}
