/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public final class emVCF_LOOKUP_TB {
	public final static emVCF_LOOKUP_TB LUP_TB_POINT = new emVCF_LOOKUP_TB(
			"LUP_TB_POINT", elecchartcoreJNI.LUP_TB_POINT_get());
	public final static emVCF_LOOKUP_TB LUP_TB_LINE = new emVCF_LOOKUP_TB(
			"LUP_TB_LINE");
	public final static emVCF_LOOKUP_TB LUP_TB_AREA = new emVCF_LOOKUP_TB(
			"LUP_TB_AREA");
	public final static emVCF_LOOKUP_TB LUP_TBL_NUM = new emVCF_LOOKUP_TB(
			"LUP_TBL_NUM");

	public final int swigValue() {
		return swigValue;
	}

	public String toString() {
		return swigName;
	}

	public static emVCF_LOOKUP_TB swigToEnum(int swigValue) {
		if (swigValue < swigValues.length && swigValue >= 0
				&& swigValues[swigValue].swigValue == swigValue)
			return swigValues[swigValue];
		for (int i = 0; i < swigValues.length; i++)
			if (swigValues[i].swigValue == swigValue)
				return swigValues[i];
		throw new IllegalArgumentException("No enum " + emVCF_LOOKUP_TB.class
				+ " with value " + swigValue);
	}

	private emVCF_LOOKUP_TB(String swigName) {
		this.swigName = swigName;
		this.swigValue = swigNext++;
	}

	private emVCF_LOOKUP_TB(String swigName, int swigValue) {
		this.swigName = swigName;
		this.swigValue = swigValue;
		swigNext = swigValue + 1;
	}

	private emVCF_LOOKUP_TB(String swigName, emVCF_LOOKUP_TB swigEnum) {
		this.swigName = swigName;
		this.swigValue = swigEnum.swigValue;
		swigNext = this.swigValue + 1;
	}

	private static emVCF_LOOKUP_TB[] swigValues = { LUP_TB_POINT, LUP_TB_LINE,
			LUP_TB_AREA, LUP_TBL_NUM };
	private static int swigNext = 0;
	private final int swigValue;
	private final String swigName;
}
