/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public final class emVCF_SYMBOL_TB {
	public final static emVCF_SYMBOL_TB POINT_SYM = new emVCF_SYMBOL_TB(
			"POINT_SYM", elecchartcoreJNI.POINT_SYM_get());
	public final static emVCF_SYMBOL_TB LINES_SYM = new emVCF_SYMBOL_TB(
			"LINES_SYM");
	public final static emVCF_SYMBOL_TB AREAS_SYM = new emVCF_SYMBOL_TB(
			"AREAS_SYM");
	public final static emVCF_SYMBOL_TB SMB_TBL_NUM = new emVCF_SYMBOL_TB(
			"SMB_TBL_NUM");

	public final int swigValue() {
		return swigValue;
	}

	public String toString() {
		return swigName;
	}

	public static emVCF_SYMBOL_TB swigToEnum(int swigValue) {
		if (swigValue < swigValues.length && swigValue >= 0
				&& swigValues[swigValue].swigValue == swigValue)
			return swigValues[swigValue];
		for (int i = 0; i < swigValues.length; i++)
			if (swigValues[i].swigValue == swigValue)
				return swigValues[i];
		throw new IllegalArgumentException("No enum " + emVCF_SYMBOL_TB.class
				+ " with value " + swigValue);
	}

	private emVCF_SYMBOL_TB(String swigName) {
		this.swigName = swigName;
		this.swigValue = swigNext++;
	}

	private emVCF_SYMBOL_TB(String swigName, int swigValue) {
		this.swigName = swigName;
		this.swigValue = swigValue;
		swigNext = swigValue + 1;
	}

	private emVCF_SYMBOL_TB(String swigName, emVCF_SYMBOL_TB swigEnum) {
		this.swigName = swigName;
		this.swigValue = swigEnum.swigValue;
		swigNext = this.swigValue + 1;
	}

	private static emVCF_SYMBOL_TB[] swigValues = { POINT_SYM, LINES_SYM,
			AREAS_SYM, SMB_TBL_NUM };
	private static int swigNext = 0;
	private final int swigValue;
	private final String swigName;
}
