/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public final class emVCF_SYMBOL_FONT {
	public final static emVCF_SYMBOL_FONT VCFSYMBOL_ONE = new emVCF_SYMBOL_FONT(
			"VCFSYMBOL_ONE", elecchartcoreJNI.VCFSYMBOL_ONE_get());
	public final static emVCF_SYMBOL_FONT VCFSYMBOL_TWO = new emVCF_SYMBOL_FONT(
			"VCFSYMBOL_TWO");

	public final int swigValue() {
		return swigValue;
	}

	public String toString() {
		return swigName;
	}

	public static emVCF_SYMBOL_FONT swigToEnum(int swigValue) {
		if (swigValue < swigValues.length && swigValue >= 0
				&& swigValues[swigValue].swigValue == swigValue)
			return swigValues[swigValue];
		for (int i = 0; i < swigValues.length; i++)
			if (swigValues[i].swigValue == swigValue)
				return swigValues[i];
		throw new IllegalArgumentException("No enum " + emVCF_SYMBOL_FONT.class
				+ " with value " + swigValue);
	}

	private emVCF_SYMBOL_FONT(String swigName) {
		this.swigName = swigName;
		this.swigValue = swigNext++;
	}

	private emVCF_SYMBOL_FONT(String swigName, int swigValue) {
		this.swigName = swigName;
		this.swigValue = swigValue;
		swigNext = swigValue + 1;
	}

	private emVCF_SYMBOL_FONT(String swigName, emVCF_SYMBOL_FONT swigEnum) {
		this.swigName = swigName;
		this.swigValue = swigEnum.swigValue;
		swigNext = this.swigValue + 1;
	}

	private static emVCF_SYMBOL_FONT[] swigValues = { VCFSYMBOL_ONE,
			VCFSYMBOL_TWO };
	private static int swigNext = 0;
	private final int swigValue;
	private final String swigName;
}
