/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public final class euVcfFieldType {
	public final static euVcfFieldType XHFInteger = new euVcfFieldType(
			"XHFInteger", elecchartcoreJNI.XHFInteger_get());
	public final static euVcfFieldType XHFDouble = new euVcfFieldType(
			"XHFDouble", elecchartcoreJNI.XHFDouble_get());
	public final static euVcfFieldType XHFString = new euVcfFieldType(
			"XHFString", elecchartcoreJNI.XHFString_get());
	public final static euVcfFieldType XHFMAXType = new euVcfFieldType(
			"XHFMAXType", elecchartcoreJNI.XHFMAXType_get());

	public final int swigValue() {
		return swigValue;
	}

	public String toString() {
		return swigName;
	}

	public static euVcfFieldType swigToEnum(int swigValue) {
		if (swigValue < swigValues.length && swigValue >= 0
				&& swigValues[swigValue].swigValue == swigValue)
			return swigValues[swigValue];
		for (int i = 0; i < swigValues.length; i++)
			if (swigValues[i].swigValue == swigValue)
				return swigValues[i];
		throw new IllegalArgumentException("No enum " + euVcfFieldType.class
				+ " with value " + swigValue);
	}

	private euVcfFieldType(String swigName) {
		this.swigName = swigName;
		this.swigValue = swigNext++;
	}

	private euVcfFieldType(String swigName, int swigValue) {
		this.swigName = swigName;
		this.swigValue = swigValue;
		swigNext = swigValue + 1;
	}

	private euVcfFieldType(String swigName, euVcfFieldType swigEnum) {
		this.swigName = swigName;
		this.swigValue = swigEnum.swigValue;
		swigNext = this.swigValue + 1;
	}

	private static euVcfFieldType[] swigValues = { XHFInteger, XHFDouble,
			XHFString, XHFMAXType };
	private static int swigNext = 0;
	private final int swigValue;
	private final String swigName;
}
