/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class Floats {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected Floats(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(Floats obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_Floats(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public Floats() {
		this(elecchartcoreJNI.new_Floats__SWIG_0(), true);
	}

	public Floats(int n) {
		this(elecchartcoreJNI.new_Floats__SWIG_1(n), true);
	}

	public void recount(int n) {
		elecchartcoreJNI.Floats_recount(swigCPtr, this, n);
	}

	public void clear() {
		elecchartcoreJNI.Floats_clear(swigCPtr, this);
	}

	public int size() {
		return elecchartcoreJNI.Floats_size(swigCPtr, this);
	}

	public int count() {
		return elecchartcoreJNI.Floats_count(swigCPtr, this);
	}

	public float get(int index) {
		return elecchartcoreJNI.Floats_get(swigCPtr, this, index);
	}

	public float gethead() {
		return elecchartcoreJNI.Floats_gethead(swigCPtr, this);
	}

	public float gettail() {
		return elecchartcoreJNI.Floats_gettail(swigCPtr, this);
	}

	public void set(int index, float value) {
		elecchartcoreJNI.Floats_set(swigCPtr, this, index, value);
	}

	public void setNoSize(int index, float value) {
		elecchartcoreJNI.Floats_setNoSize(swigCPtr, this, index, value);
	}

	public void add(float value) {
		elecchartcoreJNI.Floats_add(swigCPtr, this, value);
	}

}
