/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class Ints {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected Ints(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(Ints obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_Ints(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public Ints() {
		this(elecchartcoreJNI.new_Ints__SWIG_0(), true);
	}

	public Ints(int n) {
		this(elecchartcoreJNI.new_Ints__SWIG_1(n), true);
	}

	public void recount(int n) {
		elecchartcoreJNI.Ints_recount(swigCPtr, this, n);
	}

	public void clear() {
		elecchartcoreJNI.Ints_clear(swigCPtr, this);
	}

	public int size() {
		return elecchartcoreJNI.Ints_size(swigCPtr, this);
	}

	public int count() {
		return elecchartcoreJNI.Ints_count(swigCPtr, this);
	}

	public int get(int index) {
		return elecchartcoreJNI.Ints_get(swigCPtr, this, index);
	}

	public int gethead() {
		return elecchartcoreJNI.Ints_gethead(swigCPtr, this);
	}

	public int gettail() {
		return elecchartcoreJNI.Ints_gettail(swigCPtr, this);
	}

	public void set(int index, int value) {
		elecchartcoreJNI.Ints_set(swigCPtr, this, index, value);
	}

	public void setNoSize(int index, int value) {
		elecchartcoreJNI.Ints_setNoSize(swigCPtr, this, index, value);
	}

	public void add(int value) {
		elecchartcoreJNI.Ints_add(swigCPtr, this, value);
	}

}
