/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class PkColor {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected PkColor(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(PkColor obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_PkColor(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setR(short value) {
		elecchartcoreJNI.PkColor_r_set(swigCPtr, this, value);
	}

	public short getR() {
		return elecchartcoreJNI.PkColor_r_get(swigCPtr, this);
	}

	public void setG(short value) {
		elecchartcoreJNI.PkColor_g_set(swigCPtr, this, value);
	}

	public short getG() {
		return elecchartcoreJNI.PkColor_g_get(swigCPtr, this);
	}

	public void setB(short value) {
		elecchartcoreJNI.PkColor_b_set(swigCPtr, this, value);
	}

	public short getB() {
		return elecchartcoreJNI.PkColor_b_get(swigCPtr, this);
	}

	public void setA(short value) {
		elecchartcoreJNI.PkColor_a_set(swigCPtr, this, value);
	}

	public short getA() {
		return elecchartcoreJNI.PkColor_a_get(swigCPtr, this);
	}

	public PkColor() {
		this(elecchartcoreJNI.new_PkColor__SWIG_0(), true);
	}

	public PkColor(short _r, short _g, short _b, short _a) {
		this(elecchartcoreJNI.new_PkColor__SWIG_1(_r, _g, _b, _a), true);
	}

	public PkColor(short _r, short _g, short _b) {
		this(elecchartcoreJNI.new_PkColor__SWIG_2(_r, _g, _b), true);
	}

	public PkColor(PkColor c) {
		this(elecchartcoreJNI.new_PkColor__SWIG_3(PkColor.getCPtr(c), c), true);
	}

	public static PkColor White() {
		return new PkColor(elecchartcoreJNI.PkColor_White(), true);
	}

	public static PkColor Black() {
		return new PkColor(elecchartcoreJNI.PkColor_Black(), true);
	}

	public static PkColor Invalid() {
		return new PkColor(elecchartcoreJNI.PkColor_Invalid(), true);
	}

	public void set(short _r, short _g, short _b) {
		elecchartcoreJNI.PkColor_set__SWIG_0(swigCPtr, this, _r, _g, _b);
	}

	public void set(short _r, short _g, short _b, short _a) {
		elecchartcoreJNI.PkColor_set__SWIG_1(swigCPtr, this, _r, _g, _b, _a);
	}

	public boolean isInvalid() {
		return elecchartcoreJNI.PkColor_isInvalid(swigCPtr, this);
	}

	public float toFloat(short c) {
		return elecchartcoreJNI.PkColor_toFloat(swigCPtr, this, c);
	}

}
