/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class Points {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected Points(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(Points obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_Points(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public Points() {
		this(elecchartcoreJNI.new_Points__SWIG_0(), true);
	}

	public Points(int n) {
		this(elecchartcoreJNI.new_Points__SWIG_1(n), true);
	}

	public void recount(int n) {
		elecchartcoreJNI.Points_recount(swigCPtr, this, n);
	}

	public void clear() {
		elecchartcoreJNI.Points_clear(swigCPtr, this);
	}

	public int size() {
		return elecchartcoreJNI.Points_size(swigCPtr, this);
	}

	public int count() {
		return elecchartcoreJNI.Points_count(swigCPtr, this);
	}

	public stLPOINT get(int index) {
		return new stLPOINT(elecchartcoreJNI.Points_get(swigCPtr, this, index),
				true);
	}

	public stLPOINT gethead() {
		return new stLPOINT(elecchartcoreJNI.Points_gethead(swigCPtr, this),
				true);
	}

	public stLPOINT gettail() {
		return new stLPOINT(elecchartcoreJNI.Points_gettail(swigCPtr, this),
				true);
	}

	public void set(int index, stLPOINT value) {
		elecchartcoreJNI.Points_set(swigCPtr, this, index,
				stLPOINT.getCPtr(value), value);
	}

	public void setNoSize(int index, stLPOINT value) {
		elecchartcoreJNI.Points_setNoSize(swigCPtr, this, index,
				stLPOINT.getCPtr(value), value);
	}

	public void add(stLPOINT value) {
		elecchartcoreJNI.Points_add(swigCPtr, this, stLPOINT.getCPtr(value),
				value);
	}

}
