/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stAISDATA_PACK {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stAISDATA_PACK(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stAISDATA_PACK obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stAISDATA_PACK(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setAiVDM(stUAIS_AIVDM value) {
		elecchartcoreJNI.stAISDATA_PACK_aiVDM_set(swigCPtr, this,
				stUAIS_AIVDM.getCPtr(value), value);
	}

	public stUAIS_AIVDM getAiVDM() {
		long cPtr = elecchartcoreJNI.stAISDATA_PACK_aiVDM_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stUAIS_AIVDM(cPtr, false);
	}

	public void setAiALR(stUAIS_AIALR value) {
		elecchartcoreJNI.stAISDATA_PACK_aiALR_set(swigCPtr, this,
				stUAIS_AIALR.getCPtr(value), value);
	}

	public stUAIS_AIALR getAiALR() {
		long cPtr = elecchartcoreJNI.stAISDATA_PACK_aiALR_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stUAIS_AIALR(cPtr, false);
	}

	public void setAiABK(stUAIS_AIABK value) {
		elecchartcoreJNI.stAISDATA_PACK_aiABK_set(swigCPtr, this,
				stUAIS_AIABK.getCPtr(value), value);
	}

	public stUAIS_AIABK getAiABK() {
		long cPtr = elecchartcoreJNI.stAISDATA_PACK_aiABK_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stUAIS_AIABK(cPtr, false);
	}

	public void setAiBBM(stUAIS_AIBBM value) {
		elecchartcoreJNI.stAISDATA_PACK_aiBBM_set(swigCPtr, this,
				stUAIS_AIBBM.getCPtr(value), value);
	}

	public stUAIS_AIBBM getAiBBM() {
		long cPtr = elecchartcoreJNI.stAISDATA_PACK_aiBBM_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stUAIS_AIBBM(cPtr, false);
	}

	public void setAiABM(stUAIS_AIABM value) {
		elecchartcoreJNI.stAISDATA_PACK_aiABM_set(swigCPtr, this,
				stUAIS_AIABM.getCPtr(value), value);
	}

	public stUAIS_AIABM getAiABM() {
		long cPtr = elecchartcoreJNI.stAISDATA_PACK_aiABM_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stUAIS_AIABM(cPtr, false);
	}

	public void setAiAIR(stUAIS_AIAIR value) {
		elecchartcoreJNI.stAISDATA_PACK_aiAIR_set(swigCPtr, this,
				stUAIS_AIAIR.getCPtr(value), value);
	}

	public stUAIS_AIAIR getAiAIR() {
		long cPtr = elecchartcoreJNI.stAISDATA_PACK_aiAIR_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stUAIS_AIAIR(cPtr, false);
	}

	public void setAiSSD(stUAIS_AISSD value) {
		elecchartcoreJNI.stAISDATA_PACK_aiSSD_set(swigCPtr, this,
				stUAIS_AISSD.getCPtr(value), value);
	}

	public stUAIS_AISSD getAiSSD() {
		long cPtr = elecchartcoreJNI.stAISDATA_PACK_aiSSD_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stUAIS_AISSD(cPtr, false);
	}

	public void setAiVSD(stUAIS_AIVSD value) {
		elecchartcoreJNI.stAISDATA_PACK_aiVSD_set(swigCPtr, this,
				stUAIS_AIVSD.getCPtr(value), value);
	}

	public stUAIS_AIVSD getAiVSD() {
		long cPtr = elecchartcoreJNI.stAISDATA_PACK_aiVSD_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stUAIS_AIVSD(cPtr, false);
	}

	public stAISDATA_PACK() {
		this(elecchartcoreJNI.new_stAISDATA_PACK(), true);
	}

}
