/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stBODY_LOGO_HCHDT {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stBODY_LOGO_HCHDT(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stBODY_LOGO_HCHDT obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stBODY_LOGO_HCHDT(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setFHead(double value) {
		elecchartcoreJNI.stBODY_LOGO_HCHDT_fHead_set(swigCPtr, this, value);
	}

	public double getFHead() {
		return elecchartcoreJNI.stBODY_LOGO_HCHDT_fHead_get(swigCPtr, this);
	}

	public stBODY_LOGO_HCHDT() {
		this(elecchartcoreJNI.new_stBODY_LOGO_HCHDT(), true);
	}

}
