/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stBODY_UAIS_MESSAGE_01 {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stBODY_UAIS_MESSAGE_01(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stBODY_UAIS_MESSAGE_01 obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stBODY_UAIS_MESSAGE_01(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setId(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_id_set(swigCPtr, this, value);
	}

	public int getId() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_id_get(swigCPtr, this);
	}

	public void setRepeat(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_repeat_set(swigCPtr, this,
				value);
	}

	public int getRepeat() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_repeat_get(swigCPtr,
				this);
	}

	public void setMmsi(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_mmsi_set(swigCPtr, this, value);
	}

	public int getMmsi() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_mmsi_get(swigCPtr, this);
	}

	public void setNavState(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_navState_set(swigCPtr, this,
				value);
	}

	public int getNavState() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_navState_get(swigCPtr,
				this);
	}

	public void setRot(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_rot_set(swigCPtr, this, value);
	}

	public int getRot() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_rot_get(swigCPtr, this);
	}

	public void setSog(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_sog_set(swigCPtr, this, value);
	}

	public int getSog() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_sog_get(swigCPtr, this);
	}

	public void setPrecise(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_precise_set(swigCPtr, this,
				value);
	}

	public int getPrecise() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_precise_get(swigCPtr,
				this);
	}

	public void setLongitude(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_longitude_set(swigCPtr, this,
				value);
	}

	public int getLongitude() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_longitude_get(swigCPtr,
				this);
	}

	public void setLatitude(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_latitude_set(swigCPtr, this,
				value);
	}

	public int getLatitude() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_latitude_get(swigCPtr,
				this);
	}

	public void setCog(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_cog_set(swigCPtr, this, value);
	}

	public int getCog() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_cog_get(swigCPtr, this);
	}

	public void setCourse(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_course_set(swigCPtr, this,
				value);
	}

	public int getCourse() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_course_get(swigCPtr,
				this);
	}

	public void setReserve(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_reserve_set(swigCPtr, this,
				value);
	}

	public int getReserve() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_reserve_get(swigCPtr,
				this);
	}

	public void setUtc(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_utc_set(swigCPtr, this, value);
	}

	public int getUtc() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_utc_get(swigCPtr, this);
	}

	public void setRaim(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_raim_set(swigCPtr, this, value);
	}

	public int getRaim() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_raim_get(swigCPtr, this);
	}

	public void setComState(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_comState_set(swigCPtr, this,
				value);
	}

	public int getComState() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_01_comState_get(swigCPtr,
				this);
	}

	public stBODY_UAIS_MESSAGE_01() {
		this(elecchartcoreJNI.new_stBODY_UAIS_MESSAGE_01(), true);
	}

}
