/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stBODY_UAIS_MESSAGE_05 {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stBODY_UAIS_MESSAGE_05(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stBODY_UAIS_MESSAGE_05 obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stBODY_UAIS_MESSAGE_05(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setId(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_id_set(swigCPtr, this, value);
	}

	public int getId() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_id_get(swigCPtr, this);
	}

	public void setRepeat(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_repeat_set(swigCPtr, this,
				value);
	}

	public int getRepeat() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_repeat_get(swigCPtr,
				this);
	}

	public void setMmsi(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_mmsi_set(swigCPtr, this, value);
	}

	public int getMmsi() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_mmsi_get(swigCPtr, this);
	}

	public void setVersion(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_version_set(swigCPtr, this,
				value);
	}

	public int getVersion() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_version_get(swigCPtr,
				this);
	}

	public void setImo(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_imo_set(swigCPtr, this, value);
	}

	public int getImo() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_imo_get(swigCPtr, this);
	}

	public void setCallNo(String value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_callNo_set(swigCPtr, this,
				value);
	}

	public String getCallNo() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_callNo_get(swigCPtr,
				this);
	}

	public void setName(String value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_name_set(swigCPtr, this, value);
	}

	public String getName() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_name_get(swigCPtr, this);
	}

	public void setShipType(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_shipType_set(swigCPtr, this,
				value);
	}

	public int getShipType() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_shipType_get(swigCPtr,
				this);
	}

	public void setTxHead(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_txHead_set(swigCPtr, this,
				value);
	}

	public int getTxHead() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_txHead_get(swigCPtr,
				this);
	}

	public void setTxTail(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_txTail_set(swigCPtr, this,
				value);
	}

	public int getTxTail() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_txTail_get(swigCPtr,
				this);
	}

	public void setTxLeft(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_txLeft_set(swigCPtr, this,
				value);
	}

	public int getTxLeft() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_txLeft_get(swigCPtr,
				this);
	}

	public void setTxRight(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_txRight_set(swigCPtr, this,
				value);
	}

	public int getTxRight() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_txRight_get(swigCPtr,
				this);
	}

	public void setDeviceType(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_deviceType_set(swigCPtr, this,
				value);
	}

	public int getDeviceType() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_deviceType_get(swigCPtr,
				this);
	}

	public void setUtcMonth(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_utcMonth_set(swigCPtr, this,
				value);
	}

	public int getUtcMonth() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_utcMonth_get(swigCPtr,
				this);
	}

	public void setUtcDay(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_utcDay_set(swigCPtr, this,
				value);
	}

	public int getUtcDay() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_utcDay_get(swigCPtr,
				this);
	}

	public void setUtcHour(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_utcHour_set(swigCPtr, this,
				value);
	}

	public int getUtcHour() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_utcHour_get(swigCPtr,
				this);
	}

	public void setUtcMintue(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_utcMintue_set(swigCPtr, this,
				value);
	}

	public int getUtcMintue() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_utcMintue_get(swigCPtr,
				this);
	}

	public void setDraught(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_draught_set(swigCPtr, this,
				value);
	}

	public int getDraught() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_draught_get(swigCPtr,
				this);
	}

	public void setDes(String value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_des_set(swigCPtr, this, value);
	}

	public String getDes() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_des_get(swigCPtr, this);
	}

	public void setDte(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_dte_set(swigCPtr, this, value);
	}

	public int getDte() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_05_dte_get(swigCPtr, this);
	}

	public stBODY_UAIS_MESSAGE_05() {
		this(elecchartcoreJNI.new_stBODY_UAIS_MESSAGE_05(), true);
	}

}
