/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stBODY_UAIS_MESSAGE_6_SUB0 {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stBODY_UAIS_MESSAGE_6_SUB0(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stBODY_UAIS_MESSAGE_6_SUB0 obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stBODY_UAIS_MESSAGE_6_SUB0(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setAck(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_6_SUB0_ack_set(swigCPtr, this,
				value);
	}

	public int getAck() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_6_SUB0_ack_get(swigCPtr,
				this);
	}

	public void setMessageNo(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_6_SUB0_messageNo_set(swigCPtr,
				this, value);
	}

	public int getMessageNo() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_6_SUB0_messageNo_get(
				swigCPtr, this);
	}

	public void setText(String value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_6_SUB0_text_set(swigCPtr, this,
				value);
	}

	public String getText() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_6_SUB0_text_get(swigCPtr,
				this);
	}

	public stBODY_UAIS_MESSAGE_6_SUB0() {
		this(elecchartcoreJNI.new_stBODY_UAIS_MESSAGE_6_SUB0(), true);
	}

}
