/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stBODY_UAIS_MESSAGE_16 {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stBODY_UAIS_MESSAGE_16(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stBODY_UAIS_MESSAGE_16 obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stBODY_UAIS_MESSAGE_16(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setId(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_16_id_set(swigCPtr, this, value);
	}

	public int getId() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_16_id_get(swigCPtr, this);
	}

	public void setRepeat(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_16_repeat_set(swigCPtr, this,
				value);
	}

	public int getRepeat() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_16_repeat_get(swigCPtr,
				this);
	}

	public void setMmsi(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_16_mmsi_set(swigCPtr, this, value);
	}

	public int getMmsi() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_16_mmsi_get(swigCPtr, this);
	}

	public void setBack1(int value) {
		elecchartcoreJNI
				.stBODY_UAIS_MESSAGE_16_back1_set(swigCPtr, this, value);
	}

	public int getBack1() {
		return elecchartcoreJNI
				.stBODY_UAIS_MESSAGE_16_back1_get(swigCPtr, this);
	}

	public void setTmmsiA(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_16_tmmsiA_set(swigCPtr, this,
				value);
	}

	public int getTmmsiA() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_16_tmmsiA_get(swigCPtr,
				this);
	}

	public void setTAOffset(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_16_tAOffset_set(swigCPtr, this,
				value);
	}

	public int getTAOffset() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_16_tAOffset_get(swigCPtr,
				this);
	}

	public void setTAIncrement(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_16_tAIncrement_set(swigCPtr, this,
				value);
	}

	public int getTAIncrement() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_16_tAIncrement_get(
				swigCPtr, this);
	}

	public void setTmmsiB(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_16_tmmsiB_set(swigCPtr, this,
				value);
	}

	public int getTmmsiB() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_16_tmmsiB_get(swigCPtr,
				this);
	}

	public void setTBOffset(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_16_tBOffset_set(swigCPtr, this,
				value);
	}

	public int getTBOffset() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_16_tBOffset_get(swigCPtr,
				this);
	}

	public void setTBIncrement(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_16_tBIncrement_set(swigCPtr, this,
				value);
	}

	public int getTBIncrement() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_16_tBIncrement_get(
				swigCPtr, this);
	}

	public void setBack2(int value) {
		elecchartcoreJNI
				.stBODY_UAIS_MESSAGE_16_back2_set(swigCPtr, this, value);
	}

	public int getBack2() {
		return elecchartcoreJNI
				.stBODY_UAIS_MESSAGE_16_back2_get(swigCPtr, this);
	}

	public stBODY_UAIS_MESSAGE_16() {
		this(elecchartcoreJNI.new_stBODY_UAIS_MESSAGE_16(), true);
	}

}
