/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stBODY_UAIS_MESSAGE_17 {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stBODY_UAIS_MESSAGE_17(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stBODY_UAIS_MESSAGE_17 obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stBODY_UAIS_MESSAGE_17(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setId(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_17_id_set(swigCPtr, this, value);
	}

	public int getId() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_17_id_get(swigCPtr, this);
	}

	public void setRepeat(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_17_repeat_set(swigCPtr, this,
				value);
	}

	public int getRepeat() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_17_repeat_get(swigCPtr,
				this);
	}

	public void setSmmsi(int value) {
		elecchartcoreJNI
				.stBODY_UAIS_MESSAGE_17_smmsi_set(swigCPtr, this, value);
	}

	public int getSmmsi() {
		return elecchartcoreJNI
				.stBODY_UAIS_MESSAGE_17_smmsi_get(swigCPtr, this);
	}

	public void setLongitude(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_17_longitude_set(swigCPtr, this,
				value);
	}

	public int getLongitude() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_17_longitude_get(swigCPtr,
				this);
	}

	public void setLatitude(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_17_latitude_set(swigCPtr, this,
				value);
	}

	public int getLatitude() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_17_latitude_get(swigCPtr,
				this);
	}

	public void setMsgType(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_17_msgType_set(swigCPtr, this,
				value);
	}

	public int getMsgType() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_17_msgType_get(swigCPtr,
				this);
	}

	public void setStation(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_17_station_set(swigCPtr, this,
				value);
	}

	public int getStation() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_17_station_get(swigCPtr,
				this);
	}

	public void setTimeValue(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_17_timeValue_set(swigCPtr, this,
				value);
	}

	public int getTimeValue() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_17_timeValue_get(swigCPtr,
				this);
	}

	public void setMsgSerial(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_17_msgSerial_set(swigCPtr, this,
				value);
	}

	public int getMsgSerial() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_17_msgSerial_get(swigCPtr,
				this);
	}

	public void setWordNum(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_17_wordNum_set(swigCPtr, this,
				value);
	}

	public int getWordNum() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_17_wordNum_get(swigCPtr,
				this);
	}

	public void setState(int value) {
		elecchartcoreJNI
				.stBODY_UAIS_MESSAGE_17_state_set(swigCPtr, this, value);
	}

	public int getState() {
		return elecchartcoreJNI
				.stBODY_UAIS_MESSAGE_17_state_get(swigCPtr, this);
	}

	public void setDate(SWIGTYPE_p_long value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_17_date_set(swigCPtr, this,
				SWIGTYPE_p_long.getCPtr(value));
	}

	public SWIGTYPE_p_long getDate() {
		long cPtr = elecchartcoreJNI.stBODY_UAIS_MESSAGE_17_date_get(swigCPtr,
				this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_long(cPtr, false);
	}

	public stBODY_UAIS_MESSAGE_17() {
		this(elecchartcoreJNI.new_stBODY_UAIS_MESSAGE_17(), true);
	}

}
