/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stBODY_NEMA_GPGGA {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stBODY_NEMA_GPGGA(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stBODY_NEMA_GPGGA obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stBODY_NEMA_GPGGA(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setTime(stUTC_TIME value) {
		elecchartcoreJNI.stBODY_NEMA_GPGGA_time_set(swigCPtr, this,
				stUTC_TIME.getCPtr(value), value);
	}

	public stUTC_TIME getTime() {
		long cPtr = elecchartcoreJNI.stBODY_NEMA_GPGGA_time_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stUTC_TIME(cPtr, false);
	}

	public void setLatitude(double value) {
		elecchartcoreJNI.stBODY_NEMA_GPGGA_latitude_set(swigCPtr, this, value);
	}

	public double getLatitude() {
		return elecchartcoreJNI.stBODY_NEMA_GPGGA_latitude_get(swigCPtr, this);
	}

	public void setLatitudeType(char value) {
		elecchartcoreJNI.stBODY_NEMA_GPGGA_latitudeType_set(swigCPtr, this,
				value);
	}

	public char getLatitudeType() {
		return elecchartcoreJNI.stBODY_NEMA_GPGGA_latitudeType_get(swigCPtr,
				this);
	}

	public void setLongitude(double value) {
		elecchartcoreJNI.stBODY_NEMA_GPGGA_longitude_set(swigCPtr, this, value);
	}

	public double getLongitude() {
		return elecchartcoreJNI.stBODY_NEMA_GPGGA_longitude_get(swigCPtr, this);
	}

	public void setLongitudeType(char value) {
		elecchartcoreJNI.stBODY_NEMA_GPGGA_longitudeType_set(swigCPtr, this,
				value);
	}

	public char getLongitudeType() {
		return elecchartcoreJNI.stBODY_NEMA_GPGGA_longitudeType_get(swigCPtr,
				this);
	}

	public void setGpsStatus(char value) {
		elecchartcoreJNI.stBODY_NEMA_GPGGA_gpsStatus_set(swigCPtr, this, value);
	}

	public char getGpsStatus() {
		return elecchartcoreJNI.stBODY_NEMA_GPGGA_gpsStatus_get(swigCPtr, this);
	}

	public void setSateCount(int value) {
		elecchartcoreJNI.stBODY_NEMA_GPGGA_sateCount_set(swigCPtr, this, value);
	}

	public int getSateCount() {
		return elecchartcoreJNI.stBODY_NEMA_GPGGA_sateCount_get(swigCPtr, this);
	}

	public void setHdop(double value) {
		elecchartcoreJNI.stBODY_NEMA_GPGGA_hdop_set(swigCPtr, this, value);
	}

	public double getHdop() {
		return elecchartcoreJNI.stBODY_NEMA_GPGGA_hdop_get(swigCPtr, this);
	}

	public void setAltitude(double value) {
		elecchartcoreJNI.stBODY_NEMA_GPGGA_altitude_set(swigCPtr, this, value);
	}

	public double getAltitude() {
		return elecchartcoreJNI.stBODY_NEMA_GPGGA_altitude_get(swigCPtr, this);
	}

	public void setHeight(double value) {
		elecchartcoreJNI.stBODY_NEMA_GPGGA_height_set(swigCPtr, this, value);
	}

	public double getHeight() {
		return elecchartcoreJNI.stBODY_NEMA_GPGGA_height_get(swigCPtr, this);
	}

	public void setDiffSecond(int value) {
		elecchartcoreJNI
				.stBODY_NEMA_GPGGA_diffSecond_set(swigCPtr, this, value);
	}

	public int getDiffSecond() {
		return elecchartcoreJNI
				.stBODY_NEMA_GPGGA_diffSecond_get(swigCPtr, this);
	}

	public void setDiffStationID(String value) {
		elecchartcoreJNI.stBODY_NEMA_GPGGA_diffStationID_set(swigCPtr, this,
				value);
	}

	public String getDiffStationID() {
		return elecchartcoreJNI.stBODY_NEMA_GPGGA_diffStationID_get(swigCPtr,
				this);
	}

	public stBODY_NEMA_GPGGA() {
		this(elecchartcoreJNI.new_stBODY_NEMA_GPGGA(), true);
	}

}
