/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stBODY_NEMA_GPVTG {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stBODY_NEMA_GPVTG(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stBODY_NEMA_GPVTG obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stBODY_NEMA_GPVTG(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setDirecttn(int value) {
		elecchartcoreJNI.stBODY_NEMA_GPVTG_directtn_set(swigCPtr, this, value);
	}

	public int getDirecttn() {
		return elecchartcoreJNI.stBODY_NEMA_GPVTG_directtn_get(swigCPtr, this);
	}

	public void setDirectcn(int value) {
		elecchartcoreJNI.stBODY_NEMA_GPVTG_directcn_set(swigCPtr, this, value);
	}

	public int getDirectcn() {
		return elecchartcoreJNI.stBODY_NEMA_GPVTG_directcn_get(swigCPtr, this);
	}

	public void setVolityj(double value) {
		elecchartcoreJNI.stBODY_NEMA_GPVTG_volityj_set(swigCPtr, this, value);
	}

	public double getVolityj() {
		return elecchartcoreJNI.stBODY_NEMA_GPVTG_volityj_get(swigCPtr, this);
	}

	public void setVolitykm(double value) {
		elecchartcoreJNI.stBODY_NEMA_GPVTG_volitykm_set(swigCPtr, this, value);
	}

	public double getVolitykm() {
		return elecchartcoreJNI.stBODY_NEMA_GPVTG_volitykm_get(swigCPtr, this);
	}

	public void setMode(char value) {
		elecchartcoreJNI.stBODY_NEMA_GPVTG_mode_set(swigCPtr, this, value);
	}

	public char getMode() {
		return elecchartcoreJNI.stBODY_NEMA_GPVTG_mode_get(swigCPtr, this);
	}

	public stBODY_NEMA_GPVTG() {
		this(elecchartcoreJNI.new_stBODY_NEMA_GPVTG(), true);
	}

}
