/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stBODY_UAIS_MESSAGE_21 {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stBODY_UAIS_MESSAGE_21(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stBODY_UAIS_MESSAGE_21 obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stBODY_UAIS_MESSAGE_21(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setId(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_id_set(swigCPtr, this, value);
	}

	public int getId() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_id_get(swigCPtr, this);
	}

	public void setRepeat(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_repeat_set(swigCPtr, this,
				value);
	}

	public int getRepeat() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_repeat_get(swigCPtr,
				this);
	}

	public void setMmsi(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_mmsi_set(swigCPtr, this, value);
	}

	public int getMmsi() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_mmsi_get(swigCPtr, this);
	}

	public void setAidType(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_aidType_set(swigCPtr, this,
				value);
	}

	public int getAidType() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_aidType_get(swigCPtr,
				this);
	}

	public void setAidName(SWIGTYPE_p_int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_aidName_set(swigCPtr, this,
				SWIGTYPE_p_int.getCPtr(value));
	}

	public SWIGTYPE_p_int getAidName() {
		long cPtr = elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_aidName_get(
				swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
	}

	public void setPrecise(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_precise_set(swigCPtr, this,
				value);
	}

	public int getPrecise() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_precise_get(swigCPtr,
				this);
	}

	public void setLongitude(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_longitude_set(swigCPtr, this,
				value);
	}

	public int getLongitude() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_longitude_get(swigCPtr,
				this);
	}

	public void setLatitude(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_latitude_set(swigCPtr, this,
				value);
	}

	public int getLatitude() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_latitude_get(swigCPtr,
				this);
	}

	public void setTxHead(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_txHead_set(swigCPtr, this,
				value);
	}

	public int getTxHead() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_txHead_get(swigCPtr,
				this);
	}

	public void setTxTail(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_txTail_set(swigCPtr, this,
				value);
	}

	public int getTxTail() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_txTail_get(swigCPtr,
				this);
	}

	public void setTxLeft(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_txLeft_set(swigCPtr, this,
				value);
	}

	public int getTxLeft() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_txLeft_get(swigCPtr,
				this);
	}

	public void setTxRight(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_txRight_set(swigCPtr, this,
				value);
	}

	public int getTxRight() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_txRight_get(swigCPtr,
				this);
	}

	public void setDeviceType(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_deviceType_set(swigCPtr, this,
				value);
	}

	public int getDeviceType() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_deviceType_get(swigCPtr,
				this);
	}

	public void setUtcSec(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_utcSec_set(swigCPtr, this,
				value);
	}

	public int getUtcSec() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_utcSec_get(swigCPtr,
				this);
	}

	public void setDte(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_dte_set(swigCPtr, this, value);
	}

	public int getDte() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_dte_get(swigCPtr, this);
	}

	public void setReserve(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_reserve_set(swigCPtr, this,
				value);
	}

	public int getReserve() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_reserve_get(swigCPtr,
				this);
	}

	public void setRaim(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_raim_set(swigCPtr, this, value);
	}

	public int getRaim() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_raim_get(swigCPtr, this);
	}

	public void setPoserFlag(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_poserFlag_set(swigCPtr, this,
				value);
	}

	public int getPoserFlag() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_poserFlag_get(swigCPtr,
				this);
	}

	public void setModeFlag(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_modeFlag_set(swigCPtr, this,
				value);
	}

	public int getModeFlag() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_modeFlag_get(swigCPtr,
				this);
	}

	public void setBack(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_back_set(swigCPtr, this, value);
	}

	public int getBack() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_21_back_get(swigCPtr, this);
	}

	public stBODY_UAIS_MESSAGE_21() {
		this(elecchartcoreJNI.new_stBODY_UAIS_MESSAGE_21(), true);
	}

}
