/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stBODY_NEMA_GPGSA {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stBODY_NEMA_GPGSA(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stBODY_NEMA_GPGSA obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stBODY_NEMA_GPGSA(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setGpsmode(char value) {
		elecchartcoreJNI.stBODY_NEMA_GPGSA_gpsmode_set(swigCPtr, this, value);
	}

	public char getGpsmode() {
		return elecchartcoreJNI.stBODY_NEMA_GPGSA_gpsmode_get(swigCPtr, this);
	}

	public void setPostype(char value) {
		elecchartcoreJNI.stBODY_NEMA_GPGSA_postype_set(swigCPtr, this, value);
	}

	public char getPostype() {
		return elecchartcoreJNI.stBODY_NEMA_GPGSA_postype_get(swigCPtr, this);
	}

	public void setPrn(SWIGTYPE_p_int value) {
		elecchartcoreJNI.stBODY_NEMA_GPGSA_prn_set(swigCPtr, this,
				SWIGTYPE_p_int.getCPtr(value));
	}

	public SWIGTYPE_p_int getPrn() {
		long cPtr = elecchartcoreJNI.stBODY_NEMA_GPGSA_prn_get(swigCPtr, this);
		return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
	}

	public void setPdop(double value) {
		elecchartcoreJNI.stBODY_NEMA_GPGSA_pdop_set(swigCPtr, this, value);
	}

	public double getPdop() {
		return elecchartcoreJNI.stBODY_NEMA_GPGSA_pdop_get(swigCPtr, this);
	}

	public void setHdop(double value) {
		elecchartcoreJNI.stBODY_NEMA_GPGSA_hdop_set(swigCPtr, this, value);
	}

	public double getHdop() {
		return elecchartcoreJNI.stBODY_NEMA_GPGSA_hdop_get(swigCPtr, this);
	}

	public void setVdop(double value) {
		elecchartcoreJNI.stBODY_NEMA_GPGSA_vdop_set(swigCPtr, this, value);
	}

	public double getVdop() {
		return elecchartcoreJNI.stBODY_NEMA_GPGSA_vdop_get(swigCPtr, this);
	}

	public stBODY_NEMA_GPGSA() {
		this(elecchartcoreJNI.new_stBODY_NEMA_GPGSA(), true);
	}

}
