/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stBODY_NEMA_GPDTM {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stBODY_NEMA_GPDTM(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stBODY_NEMA_GPDTM obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stBODY_NEMA_GPDTM(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setLocaldatum(String value) {
		elecchartcoreJNI
				.stBODY_NEMA_GPDTM_localdatum_set(swigCPtr, this, value);
	}

	public String getLocaldatum() {
		return elecchartcoreJNI
				.stBODY_NEMA_GPDTM_localdatum_get(swigCPtr, this);
	}

	public void setSubdatum(String value) {
		elecchartcoreJNI.stBODY_NEMA_GPDTM_subdatum_set(swigCPtr, this, value);
	}

	public String getSubdatum() {
		return elecchartcoreJNI.stBODY_NEMA_GPDTM_subdatum_get(swigCPtr, this);
	}

	public void setLatitudeoffset(double value) {
		elecchartcoreJNI.stBODY_NEMA_GPDTM_latitudeoffset_set(swigCPtr, this,
				value);
	}

	public double getLatitudeoffset() {
		return elecchartcoreJNI.stBODY_NEMA_GPDTM_latitudeoffset_get(swigCPtr,
				this);
	}

	public void setLatitudetype(char value) {
		elecchartcoreJNI.stBODY_NEMA_GPDTM_latitudetype_set(swigCPtr, this,
				value);
	}

	public char getLatitudetype() {
		return elecchartcoreJNI.stBODY_NEMA_GPDTM_latitudetype_get(swigCPtr,
				this);
	}

	public void setLongitudeoffset(double value) {
		elecchartcoreJNI.stBODY_NEMA_GPDTM_longitudeoffset_set(swigCPtr, this,
				value);
	}

	public double getLongitudeoffset() {
		return elecchartcoreJNI.stBODY_NEMA_GPDTM_longitudeoffset_get(swigCPtr,
				this);
	}

	public void setLongitudetype(char value) {
		elecchartcoreJNI.stBODY_NEMA_GPDTM_longitudetype_set(swigCPtr, this,
				value);
	}

	public char getLongitudetype() {
		return elecchartcoreJNI.stBODY_NEMA_GPDTM_longitudetype_get(swigCPtr,
				this);
	}

	public void setAlitudeoffset(double value) {
		elecchartcoreJNI.stBODY_NEMA_GPDTM_alitudeoffset_set(swigCPtr, this,
				value);
	}

	public double getAlitudeoffset() {
		return elecchartcoreJNI.stBODY_NEMA_GPDTM_alitudeoffset_get(swigCPtr,
				this);
	}

	public void setDatum(String value) {
		elecchartcoreJNI.stBODY_NEMA_GPDTM_datum_set(swigCPtr, this, value);
	}

	public String getDatum() {
		return elecchartcoreJNI.stBODY_NEMA_GPDTM_datum_get(swigCPtr, this);
	}

	public stBODY_NEMA_GPDTM() {
		this(elecchartcoreJNI.new_stBODY_NEMA_GPDTM(), true);
	}

}
