/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stBODY_UAIS_MESSAGE_04 {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stBODY_UAIS_MESSAGE_04(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stBODY_UAIS_MESSAGE_04 obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stBODY_UAIS_MESSAGE_04(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setId(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_id_set(swigCPtr, this, value);
	}

	public int getId() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_id_get(swigCPtr, this);
	}

	public void setRepeat(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_repeat_set(swigCPtr, this,
				value);
	}

	public int getRepeat() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_repeat_get(swigCPtr,
				this);
	}

	public void setMmsi(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_mmsi_set(swigCPtr, this, value);
	}

	public int getMmsi() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_mmsi_get(swigCPtr, this);
	}

	public void setDate(stUTC_DATE value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_date_set(swigCPtr, this,
				stUTC_DATE.getCPtr(value), value);
	}

	public stUTC_DATE getDate() {
		long cPtr = elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_date_get(swigCPtr,
				this);
		return (cPtr == 0) ? null : new stUTC_DATE(cPtr, false);
	}

	public void setTime(stUTC_TIME value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_time_set(swigCPtr, this,
				stUTC_TIME.getCPtr(value), value);
	}

	public stUTC_TIME getTime() {
		long cPtr = elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_time_get(swigCPtr,
				this);
		return (cPtr == 0) ? null : new stUTC_TIME(cPtr, false);
	}

	public void setPrecise(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_precise_set(swigCPtr, this,
				value);
	}

	public int getPrecise() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_precise_get(swigCPtr,
				this);
	}

	public void setLongitude(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_longitude_set(swigCPtr, this,
				value);
	}

	public int getLongitude() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_longitude_get(swigCPtr,
				this);
	}

	public void setLatitude(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_latitude_set(swigCPtr, this,
				value);
	}

	public int getLatitude() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_latitude_get(swigCPtr,
				this);
	}

	public void setDeviceType(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_deviceType_set(swigCPtr, this,
				value);
	}

	public int getDeviceType() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_deviceType_get(swigCPtr,
				this);
	}

	public void setRaim(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_raim_set(swigCPtr, this, value);
	}

	public int getRaim() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_raim_get(swigCPtr, this);
	}

	public void setComState(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_comState_set(swigCPtr, this,
				value);
	}

	public int getComState() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_04_comState_get(swigCPtr,
				this);
	}

	public stBODY_UAIS_MESSAGE_04() {
		this(elecchartcoreJNI.new_stBODY_UAIS_MESSAGE_04(), true);
	}

}
