/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stBODY_UAIS_MESSAGE_10 {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stBODY_UAIS_MESSAGE_10(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stBODY_UAIS_MESSAGE_10 obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stBODY_UAIS_MESSAGE_10(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setId(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_10_id_set(swigCPtr, this, value);
	}

	public int getId() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_10_id_get(swigCPtr, this);
	}

	public void setRepeat(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_10_repeat_set(swigCPtr, this,
				value);
	}

	public int getRepeat() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_10_repeat_get(swigCPtr,
				this);
	}

	public void setMmsi(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_10_mmsi_set(swigCPtr, this, value);
	}

	public int getMmsi() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_10_mmsi_get(swigCPtr, this);
	}

	public void setBack1(int value) {
		elecchartcoreJNI
				.stBODY_UAIS_MESSAGE_10_back1_set(swigCPtr, this, value);
	}

	public int getBack1() {
		return elecchartcoreJNI
				.stBODY_UAIS_MESSAGE_10_back1_get(swigCPtr, this);
	}

	public void setTmmsi(int value) {
		elecchartcoreJNI
				.stBODY_UAIS_MESSAGE_10_tmmsi_set(swigCPtr, this, value);
	}

	public int getTmmsi() {
		return elecchartcoreJNI
				.stBODY_UAIS_MESSAGE_10_tmmsi_get(swigCPtr, this);
	}

	public void setBack2(int value) {
		elecchartcoreJNI
				.stBODY_UAIS_MESSAGE_10_back2_set(swigCPtr, this, value);
	}

	public int getBack2() {
		return elecchartcoreJNI
				.stBODY_UAIS_MESSAGE_10_back2_get(swigCPtr, this);
	}

	public stBODY_UAIS_MESSAGE_10() {
		this(elecchartcoreJNI.new_stBODY_UAIS_MESSAGE_10(), true);
	}

}
