/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stBODY_UAIS_MESSAGE_19 {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stBODY_UAIS_MESSAGE_19(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stBODY_UAIS_MESSAGE_19 obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stBODY_UAIS_MESSAGE_19(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setId(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_id_set(swigCPtr, this, value);
	}

	public int getId() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_id_get(swigCPtr, this);
	}

	public void setRepeat(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_repeat_set(swigCPtr, this,
				value);
	}

	public int getRepeat() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_repeat_get(swigCPtr,
				this);
	}

	public void setMmsi(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_mmsi_set(swigCPtr, this, value);
	}

	public int getMmsi() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_mmsi_get(swigCPtr, this);
	}

	public void setReserve(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_reserve_set(swigCPtr, this,
				value);
	}

	public int getReserve() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_reserve_get(swigCPtr,
				this);
	}

	public void setSog(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_sog_set(swigCPtr, this, value);
	}

	public int getSog() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_sog_get(swigCPtr, this);
	}

	public void setPrecise(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_precise_set(swigCPtr, this,
				value);
	}

	public int getPrecise() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_precise_get(swigCPtr,
				this);
	}

	public void setLongitude(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_longitude_set(swigCPtr, this,
				value);
	}

	public int getLongitude() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_longitude_get(swigCPtr,
				this);
	}

	public void setLatitude(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_latitude_set(swigCPtr, this,
				value);
	}

	public int getLatitude() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_latitude_get(swigCPtr,
				this);
	}

	public void setCog(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_cog_set(swigCPtr, this, value);
	}

	public int getCog() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_cog_get(swigCPtr, this);
	}

	public void setCourse(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_course_set(swigCPtr, this,
				value);
	}

	public int getCourse() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_course_get(swigCPtr,
				this);
	}

	public void setUtcSec(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_utcSec_set(swigCPtr, this,
				value);
	}

	public int getUtcSec() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_utcSec_get(swigCPtr,
				this);
	}

	public void setName(String value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_name_set(swigCPtr, this, value);
	}

	public String getName() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_name_get(swigCPtr, this);
	}

	public void setShipType(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_shipType_set(swigCPtr, this,
				value);
	}

	public int getShipType() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_shipType_get(swigCPtr,
				this);
	}

	public void setTxHead(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_txHead_set(swigCPtr, this,
				value);
	}

	public int getTxHead() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_txHead_get(swigCPtr,
				this);
	}

	public void setTxTail(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_txTail_set(swigCPtr, this,
				value);
	}

	public int getTxTail() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_txTail_get(swigCPtr,
				this);
	}

	public void setTxLeft(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_txLeft_set(swigCPtr, this,
				value);
	}

	public int getTxLeft() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_txLeft_get(swigCPtr,
				this);
	}

	public void setTxRight(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_txRight_set(swigCPtr, this,
				value);
	}

	public int getTxRight() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_txRight_get(swigCPtr,
				this);
	}

	public void setDeviceType(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_deviceType_set(swigCPtr, this,
				value);
	}

	public int getDeviceType() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_deviceType_get(swigCPtr,
				this);
	}

	public void setRaim(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_raim_set(swigCPtr, this, value);
	}

	public int getRaim() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_raim_get(swigCPtr, this);
	}

	public void setDte(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_dte_set(swigCPtr, this, value);
	}

	public int getDte() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_dte_get(swigCPtr, this);
	}

	public void setModeFlag(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_modeFlag_set(swigCPtr, this,
				value);
	}

	public int getModeFlag() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_modeFlag_get(swigCPtr,
				this);
	}

	public void setBack(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_back_set(swigCPtr, this, value);
	}

	public int getBack() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_19_back_get(swigCPtr, this);
	}

	public stBODY_UAIS_MESSAGE_19() {
		this(elecchartcoreJNI.new_stBODY_UAIS_MESSAGE_19(), true);
	}

}
