/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stBODY_UAIS_MESSAGE_08 {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stBODY_UAIS_MESSAGE_08(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stBODY_UAIS_MESSAGE_08 obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stBODY_UAIS_MESSAGE_08(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setId(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_08_id_set(swigCPtr, this, value);
	}

	public int getId() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_08_id_get(swigCPtr, this);
	}

	public void setRepeat(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_08_repeat_set(swigCPtr, this,
				value);
	}

	public int getRepeat() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_08_repeat_get(swigCPtr,
				this);
	}

	public void setMmsi(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_08_mmsi_set(swigCPtr, this, value);
	}

	public int getMmsi() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_08_mmsi_get(swigCPtr, this);
	}

	public void setBack(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_08_back_set(swigCPtr, this, value);
	}

	public int getBack() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_08_back_get(swigCPtr, this);
	}

	public void setDac(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_08_dac_set(swigCPtr, this, value);
	}

	public int getDac() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_08_dac_get(swigCPtr, this);
	}

	public void setFi(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_08_fi_set(swigCPtr, this, value);
	}

	public int getFi() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_08_fi_get(swigCPtr, this);
	}

	public void setMsg0(stBODY_UAIS_MESSAGE_8_SUB0 value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_08_msg0_set(swigCPtr, this,
				stBODY_UAIS_MESSAGE_8_SUB0.getCPtr(value), value);
	}

	public stBODY_UAIS_MESSAGE_8_SUB0 getMsg0() {
		long cPtr = elecchartcoreJNI.stBODY_UAIS_MESSAGE_08_msg0_get(swigCPtr,
				this);
		return (cPtr == 0) ? null : new stBODY_UAIS_MESSAGE_8_SUB0(cPtr, false);
	}

	public stBODY_UAIS_MESSAGE_08() {
		this(elecchartcoreJNI.new_stBODY_UAIS_MESSAGE_08(), true);
	}

}
