/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stBODY_UAIS_MESSAGE_12 {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stBODY_UAIS_MESSAGE_12(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stBODY_UAIS_MESSAGE_12 obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stBODY_UAIS_MESSAGE_12(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setId(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_12_id_set(swigCPtr, this, value);
	}

	public int getId() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_12_id_get(swigCPtr, this);
	}

	public void setRepeat(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_12_repeat_set(swigCPtr, this,
				value);
	}

	public int getRepeat() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_12_repeat_get(swigCPtr,
				this);
	}

	public void setMmsi(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_12_mmsi_set(swigCPtr, this, value);
	}

	public int getMmsi() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_12_mmsi_get(swigCPtr, this);
	}

	public void setSerialNo(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_12_serialNo_set(swigCPtr, this,
				value);
	}

	public int getSerialNo() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_12_serialNo_get(swigCPtr,
				this);
	}

	public void setTmmsi(int value) {
		elecchartcoreJNI
				.stBODY_UAIS_MESSAGE_12_tmmsi_set(swigCPtr, this, value);
	}

	public int getTmmsi() {
		return elecchartcoreJNI
				.stBODY_UAIS_MESSAGE_12_tmmsi_get(swigCPtr, this);
	}

	public void setRepeatFlag(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_12_repeatFlag_set(swigCPtr, this,
				value);
	}

	public int getRepeatFlag() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_12_repeatFlag_get(swigCPtr,
				this);
	}

	public void setBack(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_12_back_set(swigCPtr, this, value);
	}

	public int getBack() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_12_back_get(swigCPtr, this);
	}

	public void setChData(String value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_12_chData_set(swigCPtr, this,
				value);
	}

	public String getChData() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_12_chData_get(swigCPtr,
				this);
	}

	public stBODY_UAIS_MESSAGE_12() {
		this(elecchartcoreJNI.new_stBODY_UAIS_MESSAGE_12(), true);
	}

}
