/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stBODY_UAIS_MESSAGE_20 {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stBODY_UAIS_MESSAGE_20(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stBODY_UAIS_MESSAGE_20 obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stBODY_UAIS_MESSAGE_20(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setId(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_id_set(swigCPtr, this, value);
	}

	public int getId() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_id_get(swigCPtr, this);
	}

	public void setRepeat(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_repeat_set(swigCPtr, this,
				value);
	}

	public int getRepeat() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_repeat_get(swigCPtr,
				this);
	}

	public void setMmsi(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_mmsi_set(swigCPtr, this, value);
	}

	public int getMmsi() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_mmsi_get(swigCPtr, this);
	}

	public void setBack1(int value) {
		elecchartcoreJNI
				.stBODY_UAIS_MESSAGE_20_back1_set(swigCPtr, this, value);
	}

	public int getBack1() {
		return elecchartcoreJNI
				.stBODY_UAIS_MESSAGE_20_back1_get(swigCPtr, this);
	}

	public void setOffset1(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_offset1_set(swigCPtr, this,
				value);
	}

	public int getOffset1() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_offset1_get(swigCPtr,
				this);
	}

	public void setNum1(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_num1_set(swigCPtr, this, value);
	}

	public int getNum1() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_num1_get(swigCPtr, this);
	}

	public void setTimeout1(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_timeout1_set(swigCPtr, this,
				value);
	}

	public int getTimeout1() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_timeout1_get(swigCPtr,
				this);
	}

	public void setIncrement1(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_increment1_set(swigCPtr, this,
				value);
	}

	public int getIncrement1() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_increment1_get(swigCPtr,
				this);
	}

	public void setOffset2(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_offset2_set(swigCPtr, this,
				value);
	}

	public int getOffset2() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_offset2_get(swigCPtr,
				this);
	}

	public void setNum2(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_num2_set(swigCPtr, this, value);
	}

	public int getNum2() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_num2_get(swigCPtr, this);
	}

	public void setTimeout2(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_timeout2_set(swigCPtr, this,
				value);
	}

	public int getTimeout2() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_timeout2_get(swigCPtr,
				this);
	}

	public void setIncrement2(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_increment2_set(swigCPtr, this,
				value);
	}

	public int getIncrement2() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_increment2_get(swigCPtr,
				this);
	}

	public void setOffset3(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_offset3_set(swigCPtr, this,
				value);
	}

	public int getOffset3() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_offset3_get(swigCPtr,
				this);
	}

	public void setNum3(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_num3_set(swigCPtr, this, value);
	}

	public int getNum3() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_num3_get(swigCPtr, this);
	}

	public void setTimeout3(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_timeout3_set(swigCPtr, this,
				value);
	}

	public int getTimeout3() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_timeout3_get(swigCPtr,
				this);
	}

	public void setIncrement3(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_increment3_set(swigCPtr, this,
				value);
	}

	public int getIncrement3() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_increment3_get(swigCPtr,
				this);
	}

	public void setOffset4(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_offset4_set(swigCPtr, this,
				value);
	}

	public int getOffset4() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_offset4_get(swigCPtr,
				this);
	}

	public void setNum4(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_num4_set(swigCPtr, this, value);
	}

	public int getNum4() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_num4_get(swigCPtr, this);
	}

	public void setTimeout4(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_timeout4_set(swigCPtr, this,
				value);
	}

	public int getTimeout4() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_timeout4_get(swigCPtr,
				this);
	}

	public void setIncrement4(int value) {
		elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_increment4_set(swigCPtr, this,
				value);
	}

	public int getIncrement4() {
		return elecchartcoreJNI.stBODY_UAIS_MESSAGE_20_increment4_get(swigCPtr,
				this);
	}

	public void setBack2(int value) {
		elecchartcoreJNI
				.stBODY_UAIS_MESSAGE_20_back2_set(swigCPtr, this, value);
	}

	public int getBack2() {
		return elecchartcoreJNI
				.stBODY_UAIS_MESSAGE_20_back2_get(swigCPtr, this);
	}

	public stBODY_UAIS_MESSAGE_20() {
		this(elecchartcoreJNI.new_stBODY_UAIS_MESSAGE_20(), true);
	}

}
