/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stCHARTINITCONFIG {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stCHARTINITCONFIG(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stCHARTINITCONFIG obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stCHARTINITCONFIG(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setSzVCFGeoDatabase(String value) {
		elecchartcoreJNI.stCHARTINITCONFIG_szVCFGeoDatabase_set(swigCPtr, this,
				value);
	}

	public String getSzVCFGeoDatabase() {
		return elecchartcoreJNI.stCHARTINITCONFIG_szVCFGeoDatabase_get(
				swigCPtr, this);
	}

	public void setSzChartCode(String value) {
		elecchartcoreJNI.stCHARTINITCONFIG_szChartCode_set(swigCPtr, this,
				value);
	}

	public String getSzChartCode() {
		return elecchartcoreJNI.stCHARTINITCONFIG_szChartCode_get(swigCPtr,
				this);
	}

	public void setDViewCenLong(double value) {
		elecchartcoreJNI.stCHARTINITCONFIG_dViewCenLong_set(swigCPtr, this,
				value);
	}

	public double getDViewCenLong() {
		return elecchartcoreJNI.stCHARTINITCONFIG_dViewCenLong_get(swigCPtr,
				this);
	}

	public void setDViewCenLat(double value) {
		elecchartcoreJNI.stCHARTINITCONFIG_dViewCenLat_set(swigCPtr, this,
				value);
	}

	public double getDViewCenLat() {
		return elecchartcoreJNI.stCHARTINITCONFIG_dViewCenLat_get(swigCPtr,
				this);
	}

	public void setNViewSizeX(int value) {
		elecchartcoreJNI
				.stCHARTINITCONFIG_nViewSizeX_set(swigCPtr, this, value);
	}

	public int getNViewSizeX() {
		return elecchartcoreJNI
				.stCHARTINITCONFIG_nViewSizeX_get(swigCPtr, this);
	}

	public void setNViewSizeY(int value) {
		elecchartcoreJNI
				.stCHARTINITCONFIG_nViewSizeY_set(swigCPtr, this, value);
	}

	public int getNViewSizeY() {
		return elecchartcoreJNI
				.stCHARTINITCONFIG_nViewSizeY_get(swigCPtr, this);
	}

	public void setDDefaultScale(double value) {
		elecchartcoreJNI.stCHARTINITCONFIG_dDefaultScale_set(swigCPtr, this,
				value);
	}

	public double getDDefaultScale() {
		return elecchartcoreJNI.stCHARTINITCONFIG_dDefaultScale_get(swigCPtr,
				this);
	}

	public void setNDisplayMode(int value) {
		elecchartcoreJNI.stCHARTINITCONFIG_nDisplayMode_set(swigCPtr, this,
				value);
	}

	public int getNDisplayMode() {
		return elecchartcoreJNI.stCHARTINITCONFIG_nDisplayMode_get(swigCPtr,
				this);
	}

	public void setNChartSelectMode(int value) {
		elecchartcoreJNI.stCHARTINITCONFIG_nChartSelectMode_set(swigCPtr, this,
				value);
	}

	public int getNChartSelectMode() {
		return elecchartcoreJNI.stCHARTINITCONFIG_nChartSelectMode_get(
				swigCPtr, this);
	}

	public void setNLongLatShowMode(int value) {
		elecchartcoreJNI.stCHARTINITCONFIG_nLongLatShowMode_set(swigCPtr, this,
				value);
	}

	public int getNLongLatShowMode() {
		return elecchartcoreJNI.stCHARTINITCONFIG_nLongLatShowMode_get(
				swigCPtr, this);
	}

	public void setNScrResetMode(int value) {
		elecchartcoreJNI.stCHARTINITCONFIG_nScrResetMode_set(swigCPtr, this,
				value);
	}

	public int getNScrResetMode() {
		return elecchartcoreJNI.stCHARTINITCONFIG_nScrResetMode_get(swigCPtr,
				this);
	}

	public void setFSafeDepth(double value) {
		elecchartcoreJNI
				.stCHARTINITCONFIG_fSafeDepth_set(swigCPtr, this, value);
	}

	public double getFSafeDepth() {
		return elecchartcoreJNI
				.stCHARTINITCONFIG_fSafeDepth_get(swigCPtr, this);
	}

	public void setNTideZX(int value) {
		elecchartcoreJNI.stCHARTINITCONFIG_nTideZX_set(swigCPtr, this, value);
	}

	public int getNTideZX() {
		return elecchartcoreJNI.stCHARTINITCONFIG_nTideZX_get(swigCPtr, this);
	}

	public void setFMaxScale(double value) {
		elecchartcoreJNI.stCHARTINITCONFIG_fMaxScale_set(swigCPtr, this, value);
	}

	public double getFMaxScale() {
		return elecchartcoreJNI.stCHARTINITCONFIG_fMaxScale_get(swigCPtr, this);
	}

	public void setFMinScale(double value) {
		elecchartcoreJNI.stCHARTINITCONFIG_fMinScale_set(swigCPtr, this, value);
	}

	public double getFMinScale() {
		return elecchartcoreJNI.stCHARTINITCONFIG_fMinScale_get(swigCPtr, this);
	}

	public stCHARTINITCONFIG() {
		this(elecchartcoreJNI.new_stCHARTINITCONFIG(), true);
	}

}
