/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stCHARTDSPPRI {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stCHARTDSPPRI(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stCHARTDSPPRI obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stCHARTDSPPRI(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setNDisplayPri(int value) {
		elecchartcoreJNI.stCHARTDSPPRI_nDisplayPri_set(swigCPtr, this, value);
	}

	public int getNDisplayPri() {
		return elecchartcoreJNI.stCHARTDSPPRI_nDisplayPri_get(swigCPtr, this);
	}

	public void setNLayerCode(int value) {
		elecchartcoreJNI.stCHARTDSPPRI_nLayerCode_set(swigCPtr, this, value);
	}

	public int getNLayerCode() {
		return elecchartcoreJNI.stCHARTDSPPRI_nLayerCode_get(swigCPtr, this);
	}

	public void setNGeoNum(int value) {
		elecchartcoreJNI.stCHARTDSPPRI_nGeoNum_set(swigCPtr, this, value);
	}

	public int getNGeoNum() {
		return elecchartcoreJNI.stCHARTDSPPRI_nGeoNum_get(swigCPtr, this);
	}

	public void setLObjectFC(int value) {
		elecchartcoreJNI.stCHARTDSPPRI_lObjectFC_set(swigCPtr, this, value);
	}

	public int getLObjectFC() {
		return elecchartcoreJNI.stCHARTDSPPRI_lObjectFC_get(swigCPtr, this);
	}

	public void setNClassNum(int value) {
		elecchartcoreJNI.stCHARTDSPPRI_nClassNum_set(swigCPtr, this, value);
	}

	public int getNClassNum() {
		return elecchartcoreJNI.stCHARTDSPPRI_nClassNum_get(swigCPtr, this);
	}

	public stCHARTDSPPRI() {
		this(elecchartcoreJNI.new_stCHARTDSPPRI(), true);
	}

}
