/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stCHARTPLANPARAMETER {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stCHARTPLANPARAMETER(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stCHARTPLANPARAMETER obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stCHARTPLANPARAMETER(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setFLeft(float value) {
		elecchartcoreJNI.stCHARTPLANPARAMETER_fLeft_set(swigCPtr, this, value);
	}

	public float getFLeft() {
		return elecchartcoreJNI.stCHARTPLANPARAMETER_fLeft_get(swigCPtr, this);
	}

	public void setFRight(float value) {
		elecchartcoreJNI.stCHARTPLANPARAMETER_fRight_set(swigCPtr, this, value);
	}

	public float getFRight() {
		return elecchartcoreJNI.stCHARTPLANPARAMETER_fRight_get(swigCPtr, this);
	}

	public void setFBottom(float value) {
		elecchartcoreJNI
				.stCHARTPLANPARAMETER_fBottom_set(swigCPtr, this, value);
	}

	public float getFBottom() {
		return elecchartcoreJNI
				.stCHARTPLANPARAMETER_fBottom_get(swigCPtr, this);
	}

	public void setFTop(float value) {
		elecchartcoreJNI.stCHARTPLANPARAMETER_fTop_set(swigCPtr, this, value);
	}

	public float getFTop() {
		return elecchartcoreJNI.stCHARTPLANPARAMETER_fTop_get(swigCPtr, this);
	}

	public stCHARTPLANPARAMETER() {
		this(elecchartcoreJNI.new_stCHARTPLANPARAMETER(), true);
	}

}
