/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stCHARTGEOPARAMETER {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stCHARTGEOPARAMETER(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stCHARTGEOPARAMETER obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stCHARTGEOPARAMETER(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setFMinLat(double value) {
		elecchartcoreJNI.stCHARTGEOPARAMETER_fMinLat_set(swigCPtr, this, value);
	}

	public double getFMinLat() {
		return elecchartcoreJNI.stCHARTGEOPARAMETER_fMinLat_get(swigCPtr, this);
	}

	public void setFMinLong(double value) {
		elecchartcoreJNI
				.stCHARTGEOPARAMETER_fMinLong_set(swigCPtr, this, value);
	}

	public double getFMinLong() {
		return elecchartcoreJNI
				.stCHARTGEOPARAMETER_fMinLong_get(swigCPtr, this);
	}

	public void setFMaxLat(double value) {
		elecchartcoreJNI.stCHARTGEOPARAMETER_fMaxLat_set(swigCPtr, this, value);
	}

	public double getFMaxLat() {
		return elecchartcoreJNI.stCHARTGEOPARAMETER_fMaxLat_get(swigCPtr, this);
	}

	public void setFMaxLong(double value) {
		elecchartcoreJNI
				.stCHARTGEOPARAMETER_fMaxLong_set(swigCPtr, this, value);
	}

	public double getFMaxLong() {
		return elecchartcoreJNI
				.stCHARTGEOPARAMETER_fMaxLong_get(swigCPtr, this);
	}

	public void setFMainLat(double value) {
		elecchartcoreJNI
				.stCHARTGEOPARAMETER_fMainLat_set(swigCPtr, this, value);
	}

	public double getFMainLat() {
		return elecchartcoreJNI
				.stCHARTGEOPARAMETER_fMainLat_get(swigCPtr, this);
	}

	public void setFMScale(double value) {
		elecchartcoreJNI.stCHARTGEOPARAMETER_fMScale_set(swigCPtr, this, value);
	}

	public double getFMScale() {
		return elecchartcoreJNI.stCHARTGEOPARAMETER_fMScale_get(swigCPtr, this);
	}

	public stCHARTGEOPARAMETER() {
		this(elecchartcoreJNI.new_stCHARTGEOPARAMETER(), true);
	}

}
