/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stGEOENVELOPE {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stGEOENVELOPE(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stGEOENVELOPE obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stGEOENVELOPE(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setDMinX(double value) {
		elecchartcoreJNI.stGEOENVELOPE_dMinX_set(swigCPtr, this, value);
	}

	public double getDMinX() {
		return elecchartcoreJNI.stGEOENVELOPE_dMinX_get(swigCPtr, this);
	}

	public void setDMinY(double value) {
		elecchartcoreJNI.stGEOENVELOPE_dMinY_set(swigCPtr, this, value);
	}

	public double getDMinY() {
		return elecchartcoreJNI.stGEOENVELOPE_dMinY_get(swigCPtr, this);
	}

	public void setDMaxX(double value) {
		elecchartcoreJNI.stGEOENVELOPE_dMaxX_set(swigCPtr, this, value);
	}

	public double getDMaxX() {
		return elecchartcoreJNI.stGEOENVELOPE_dMaxX_get(swigCPtr, this);
	}

	public void setDMaxY(double value) {
		elecchartcoreJNI.stGEOENVELOPE_dMaxY_set(swigCPtr, this, value);
	}

	public double getDMaxY() {
		return elecchartcoreJNI.stGEOENVELOPE_dMaxY_get(swigCPtr, this);
	}

	public stGEOENVELOPE() {
		this(elecchartcoreJNI.new_stGEOENVELOPE(), true);
	}

}
