/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stGEOOBJPICKINDEX {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stGEOOBJPICKINDEX(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stGEOOBJPICKINDEX obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stGEOOBJPICKINDEX(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setNdbIndex(int value) {
		elecchartcoreJNI.stGEOOBJPICKINDEX_ndbIndex_set(swigCPtr, this, value);
	}

	public int getNdbIndex() {
		return elecchartcoreJNI.stGEOOBJPICKINDEX_ndbIndex_get(swigCPtr, this);
	}

	public void setNdsIndex(int value) {
		elecchartcoreJNI.stGEOOBJPICKINDEX_ndsIndex_set(swigCPtr, this, value);
	}

	public int getNdsIndex() {
		return elecchartcoreJNI.stGEOOBJPICKINDEX_ndsIndex_get(swigCPtr, this);
	}

	public void setSzdsName(String value) {
		elecchartcoreJNI.stGEOOBJPICKINDEX_szdsName_set(swigCPtr, this, value);
	}

	public String getSzdsName() {
		return elecchartcoreJNI.stGEOOBJPICKINDEX_szdsName_get(swigCPtr, this);
	}

	public void setNlyIndex(int value) {
		elecchartcoreJNI.stGEOOBJPICKINDEX_nlyIndex_set(swigCPtr, this, value);
	}

	public int getNlyIndex() {
		return elecchartcoreJNI.stGEOOBJPICKINDEX_nlyIndex_get(swigCPtr, this);
	}

	public void setNobIndex(int value) {
		elecchartcoreJNI.stGEOOBJPICKINDEX_nobIndex_set(swigCPtr, this, value);
	}

	public int getNobIndex() {
		return elecchartcoreJNI.stGEOOBJPICKINDEX_nobIndex_get(swigCPtr, this);
	}

	public void setNgpIndex(int value) {
		elecchartcoreJNI.stGEOOBJPICKINDEX_ngpIndex_set(swigCPtr, this, value);
	}

	public int getNgpIndex() {
		return elecchartcoreJNI.stGEOOBJPICKINDEX_ngpIndex_get(swigCPtr, this);
	}

	public void setNgeIndex(int value) {
		elecchartcoreJNI.stGEOOBJPICKINDEX_ngeIndex_set(swigCPtr, this, value);
	}

	public int getNgeIndex() {
		return elecchartcoreJNI.stGEOOBJPICKINDEX_ngeIndex_get(swigCPtr, this);
	}

	public void setNobUpdate(int value) {
		elecchartcoreJNI.stGEOOBJPICKINDEX_nobUpdate_set(swigCPtr, this, value);
	}

	public int getNobUpdate() {
		return elecchartcoreJNI.stGEOOBJPICKINDEX_nobUpdate_get(swigCPtr, this);
	}

	public void setNPickType(int value) {
		elecchartcoreJNI.stGEOOBJPICKINDEX_nPickType_set(swigCPtr, this, value);
	}

	public int getNPickType() {
		return elecchartcoreJNI.stGEOOBJPICKINDEX_nPickType_get(swigCPtr, this);
	}

	public stGEOOBJPICKINDEX() {
		this(elecchartcoreJNI.new_stGEOOBJPICKINDEX(), true);
	}

}
