/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stOBJECTDICTIONARY {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stOBJECTDICTIONARY(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stOBJECTDICTIONARY obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stOBJECTDICTIONARY(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setLObjectFC(int value) {
		elecchartcoreJNI
				.stOBJECTDICTIONARY_lObjectFC_set(swigCPtr, this, value);
	}

	public int getLObjectFC() {
		return elecchartcoreJNI
				.stOBJECTDICTIONARY_lObjectFC_get(swigCPtr, this);
	}

	public void setNBigLayerNo(int value) {
		elecchartcoreJNI.stOBJECTDICTIONARY_nBigLayerNo_set(swigCPtr, this,
				value);
	}

	public int getNBigLayerNo() {
		return elecchartcoreJNI.stOBJECTDICTIONARY_nBigLayerNo_get(swigCPtr,
				this);
	}

	public void setSzBigLayerNa(String value) {
		elecchartcoreJNI.stOBJECTDICTIONARY_szBigLayerNa_set(swigCPtr, this,
				value);
	}

	public String getSzBigLayerNa() {
		return elecchartcoreJNI.stOBJECTDICTIONARY_szBigLayerNa_get(swigCPtr,
				this);
	}

	public void setSzSmlLayerNa(String value) {
		elecchartcoreJNI.stOBJECTDICTIONARY_szSmlLayerNa_set(swigCPtr, this,
				value);
	}

	public String getSzSmlLayerNa() {
		return elecchartcoreJNI.stOBJECTDICTIONARY_szSmlLayerNa_get(swigCPtr,
				this);
	}

	public void setSzSmlLayChName(String value) {
		elecchartcoreJNI.stOBJECTDICTIONARY_szSmlLayChName_set(swigCPtr, this,
				value);
	}

	public String getSzSmlLayChName() {
		return elecchartcoreJNI.stOBJECTDICTIONARY_szSmlLayChName_get(swigCPtr,
				this);
	}

	public void setSzAncroy(String value) {
		elecchartcoreJNI.stOBJECTDICTIONARY_szAncroy_set(swigCPtr, this, value);
	}

	public String getSzAncroy() {
		return elecchartcoreJNI.stOBJECTDICTIONARY_szAncroy_get(swigCPtr, this);
	}

	public void setNGeoType(int value) {
		elecchartcoreJNI.stOBJECTDICTIONARY_nGeoType_set(swigCPtr, this, value);
	}

	public int getNGeoType() {
		return elecchartcoreJNI.stOBJECTDICTIONARY_nGeoType_get(swigCPtr, this);
	}

	public void setNShapeType(int value) {
		elecchartcoreJNI.stOBJECTDICTIONARY_nShapeType_set(swigCPtr, this,
				value);
	}

	public int getNShapeType() {
		return elecchartcoreJNI.stOBJECTDICTIONARY_nShapeType_get(swigCPtr,
				this);
	}

	public void setSzObjectDesc(String value) {
		elecchartcoreJNI.stOBJECTDICTIONARY_szObjectDesc_set(swigCPtr, this,
				value);
	}

	public String getSzObjectDesc() {
		return elecchartcoreJNI.stOBJECTDICTIONARY_szObjectDesc_get(swigCPtr,
				this);
	}

	public void setSzSmlLayAttriDescr(String value) {
		elecchartcoreJNI.stOBJECTDICTIONARY_szSmlLayAttriDescr_set(swigCPtr,
				this, value);
	}

	public String getSzSmlLayAttriDescr() {
		return elecchartcoreJNI.stOBJECTDICTIONARY_szSmlLayAttriDescr_get(
				swigCPtr, this);
	}

	public void setSzSmlLayDataSource(String value) {
		elecchartcoreJNI.stOBJECTDICTIONARY_szSmlLayDataSource_set(swigCPtr,
				this, value);
	}

	public String getSzSmlLayDataSource() {
		return elecchartcoreJNI.stOBJECTDICTIONARY_szSmlLayDataSource_get(
				swigCPtr, this);
	}

	public void setNSymbolId(int value) {
		elecchartcoreJNI
				.stOBJECTDICTIONARY_nSymbolId_set(swigCPtr, this, value);
	}

	public int getNSymbolId() {
		return elecchartcoreJNI
				.stOBJECTDICTIONARY_nSymbolId_get(swigCPtr, this);
	}

	public stOBJECTDICTIONARY() {
		this(elecchartcoreJNI.new_stOBJECTDICTIONARY(), true);
	}

}
