/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stOBJECTRECHEADER {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stOBJECTRECHEADER(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stOBJECTRECHEADER obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stOBJECTRECHEADER(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setNGeometryType(int value) {
		elecchartcoreJNI.stOBJECTRECHEADER_nGeometryType_set(swigCPtr, this,
				value);
	}

	public int getNGeometryType() {
		return elecchartcoreJNI.stOBJECTRECHEADER_nGeometryType_get(swigCPtr,
				this);
	}

	public void setNObjectId(int value) {
		elecchartcoreJNI.stOBJECTRECHEADER_nObjectId_set(swigCPtr, this, value);
	}

	public int getNObjectId() {
		return elecchartcoreJNI.stOBJECTRECHEADER_nObjectId_get(swigCPtr, this);
	}

	public void setLClsFC(int value) {
		elecchartcoreJNI.stOBJECTRECHEADER_lClsFC_set(swigCPtr, this, value);
	}

	public int getLClsFC() {
		return elecchartcoreJNI.stOBJECTRECHEADER_lClsFC_get(swigCPtr, this);
	}

	public void setNAttriLen(int value) {
		elecchartcoreJNI.stOBJECTRECHEADER_nAttriLen_set(swigCPtr, this, value);
	}

	public int getNAttriLen() {
		return elecchartcoreJNI.stOBJECTRECHEADER_nAttriLen_get(swigCPtr, this);
	}

	public void setUnST(long value) {
		elecchartcoreJNI.stOBJECTRECHEADER_unST_set(swigCPtr, this, value);
	}

	public long getUnST() {
		return elecchartcoreJNI.stOBJECTRECHEADER_unST_get(swigCPtr, this);
	}

	public void setLCoordsLen(int value) {
		elecchartcoreJNI
				.stOBJECTRECHEADER_lCoordsLen_set(swigCPtr, this, value);
	}

	public int getLCoordsLen() {
		return elecchartcoreJNI
				.stOBJECTRECHEADER_lCoordsLen_get(swigCPtr, this);
	}

	public stOBJECTRECHEADER() {
		this(elecchartcoreJNI.new_stOBJECTRECHEADER(), true);
	}

}
