/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stONEINDEX {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stONEINDEX(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stONEINDEX obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stONEINDEX(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setNLayerNum(int value) {
		elecchartcoreJNI.stONEINDEX_nLayerNum_set(swigCPtr, this, value);
	}

	public int getNLayerNum() {
		return elecchartcoreJNI.stONEINDEX_nLayerNum_get(swigCPtr, this);
	}

	public void setLLayerOffset(int value) {
		elecchartcoreJNI.stONEINDEX_lLayerOffset_set(swigCPtr, this, value);
	}

	public int getLLayerOffset() {
		return elecchartcoreJNI.stONEINDEX_lLayerOffset_get(swigCPtr, this);
	}

	public void setLLayerLenth(int value) {
		elecchartcoreJNI.stONEINDEX_lLayerLenth_set(swigCPtr, this, value);
	}

	public int getLLayerLenth() {
		return elecchartcoreJNI.stONEINDEX_lLayerLenth_get(swigCPtr, this);
	}

	public void setNGeometryCount(int value) {
		elecchartcoreJNI.stONEINDEX_nGeometryCount_set(swigCPtr, this, value);
	}

	public int getNGeometryCount() {
		return elecchartcoreJNI.stONEINDEX_nGeometryCount_get(swigCPtr, this);
	}

	public void setNGeometryPos(int value) {
		elecchartcoreJNI.stONEINDEX_nGeometryPos_set(swigCPtr, this, value);
	}

	public int getNGeometryPos() {
		return elecchartcoreJNI.stONEINDEX_nGeometryPos_get(swigCPtr, this);
	}

	public stONEINDEX() {
		this(elecchartcoreJNI.new_stONEINDEX(), true);
	}

}
