/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stPLANEENVELOPE {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stPLANEENVELOPE(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stPLANEENVELOPE obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stPLANEENVELOPE(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setLMinX(int value) {
		elecchartcoreJNI.stPLANEENVELOPE_lMinX_set(swigCPtr, this, value);
	}

	public int getLMinX() {
		return elecchartcoreJNI.stPLANEENVELOPE_lMinX_get(swigCPtr, this);
	}

	public void setLMinY(int value) {
		elecchartcoreJNI.stPLANEENVELOPE_lMinY_set(swigCPtr, this, value);
	}

	public int getLMinY() {
		return elecchartcoreJNI.stPLANEENVELOPE_lMinY_get(swigCPtr, this);
	}

	public void setLMaxX(int value) {
		elecchartcoreJNI.stPLANEENVELOPE_lMaxX_set(swigCPtr, this, value);
	}

	public int getLMaxX() {
		return elecchartcoreJNI.stPLANEENVELOPE_lMaxX_get(swigCPtr, this);
	}

	public void setLMaxY(int value) {
		elecchartcoreJNI.stPLANEENVELOPE_lMaxY_set(swigCPtr, this, value);
	}

	public int getLMaxY() {
		return elecchartcoreJNI.stPLANEENVELOPE_lMaxY_get(swigCPtr, this);
	}

	public stPLANEENVELOPE() {
		this(elecchartcoreJNI.new_stPLANEENVELOPE(), true);
	}

}
