/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stSIMPOBJECTDICTIONARY {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stSIMPOBJECTDICTIONARY(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stSIMPOBJECTDICTIONARY obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stSIMPOBJECTDICTIONARY(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setLObjectFC(int value) {
		elecchartcoreJNI.stSIMPOBJECTDICTIONARY_lObjectFC_set(swigCPtr, this,
				value);
	}

	public int getLObjectFC() {
		return elecchartcoreJNI.stSIMPOBJECTDICTIONARY_lObjectFC_get(swigCPtr,
				this);
	}

	public void setSzSmlLayerNa(String value) {
		elecchartcoreJNI.stSIMPOBJECTDICTIONARY_szSmlLayerNa_set(swigCPtr,
				this, value);
	}

	public String getSzSmlLayerNa() {
		return elecchartcoreJNI.stSIMPOBJECTDICTIONARY_szSmlLayerNa_get(
				swigCPtr, this);
	}

	public void setNGeoType(int value) {
		elecchartcoreJNI.stSIMPOBJECTDICTIONARY_nGeoType_set(swigCPtr, this,
				value);
	}

	public int getNGeoType() {
		return elecchartcoreJNI.stSIMPOBJECTDICTIONARY_nGeoType_get(swigCPtr,
				this);
	}

	public void setSzObjectDesc(String value) {
		elecchartcoreJNI.stSIMPOBJECTDICTIONARY_szObjectDesc_set(swigCPtr,
				this, value);
	}

	public String getSzObjectDesc() {
		return elecchartcoreJNI.stSIMPOBJECTDICTIONARY_szObjectDesc_get(
				swigCPtr, this);
	}

	public void setNSymbolId(int value) {
		elecchartcoreJNI.stSIMPOBJECTDICTIONARY_nSymbolId_set(swigCPtr, this,
				value);
	}

	public int getNSymbolId() {
		return elecchartcoreJNI.stSIMPOBJECTDICTIONARY_nSymbolId_get(swigCPtr,
				this);
	}

	public stSIMPOBJECTDICTIONARY() {
		this(elecchartcoreJNI.new_stSIMPOBJECTDICTIONARY(), true);
	}

}
