/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stTHRINDEX {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stTHRINDEX(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stTHRINDEX obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stTHRINDEX(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setNClsNum(int value) {
		elecchartcoreJNI.stTHRINDEX_nClsNum_set(swigCPtr, this, value);
	}

	public int getNClsNum() {
		return elecchartcoreJNI.stTHRINDEX_nClsNum_get(swigCPtr, this);
	}

	public void setLClsFC(int value) {
		elecchartcoreJNI.stTHRINDEX_lClsFC_set(swigCPtr, this, value);
	}

	public int getLClsFC() {
		return elecchartcoreJNI.stTHRINDEX_lClsFC_get(swigCPtr, this);
	}

	public void setLClsOffset(int value) {
		elecchartcoreJNI.stTHRINDEX_lClsOffset_set(swigCPtr, this, value);
	}

	public int getLClsOffset() {
		return elecchartcoreJNI.stTHRINDEX_lClsOffset_get(swigCPtr, this);
	}

	public void setLClsLenth(int value) {
		elecchartcoreJNI.stTHRINDEX_lClsLenth_set(swigCPtr, this, value);
	}

	public int getLClsLenth() {
		return elecchartcoreJNI.stTHRINDEX_lClsLenth_get(swigCPtr, this);
	}

	public void setNElementCount(int value) {
		elecchartcoreJNI.stTHRINDEX_nElementCount_set(swigCPtr, this, value);
	}

	public int getNElementCount() {
		return elecchartcoreJNI.stTHRINDEX_nElementCount_get(swigCPtr, this);
	}

	public stTHRINDEX() {
		this(elecchartcoreJNI.new_stTHRINDEX(), true);
	}

}
