/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stTVCFGEODATASETDESCR {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stTVCFGEODATASETDESCR(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stTVCFGEODATASETDESCR obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stTVCFGEODATASETDESCR(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setSzChartCode(String value) {
		elecchartcoreJNI.stTVCFGEODATASETDESCR_szChartCode_set(swigCPtr, this,
				value);
	}

	public String getSzChartCode() {
		return elecchartcoreJNI.stTVCFGEODATASETDESCR_szChartCode_get(swigCPtr,
				this);
	}

	public void setSzChartName(String value) {
		elecchartcoreJNI.stTVCFGEODATASETDESCR_szChartName_set(swigCPtr, this,
				value);
	}

	public String getSzChartName() {
		return elecchartcoreJNI.stTVCFGEODATASETDESCR_szChartName_get(swigCPtr,
				this);
	}

	public void setSzHGeodeticDatum(String value) {
		elecchartcoreJNI.stTVCFGEODATASETDESCR_szHGeodeticDatum_set(swigCPtr,
				this, value);
	}

	public String getSzHGeodeticDatum() {
		return elecchartcoreJNI.stTVCFGEODATASETDESCR_szHGeodeticDatum_get(
				swigCPtr, this);
	}

	public void setFMidLatitude(double value) {
		elecchartcoreJNI.stTVCFGEODATASETDESCR_fMidLatitude_set(swigCPtr, this,
				value);
	}

	public double getFMidLatitude() {
		return elecchartcoreJNI.stTVCFGEODATASETDESCR_fMidLatitude_get(
				swigCPtr, this);
	}

	public void setFOrigScale(double value) {
		elecchartcoreJNI.stTVCFGEODATASETDESCR_fOrigScale_set(swigCPtr, this,
				value);
	}

	public double getFOrigScale() {
		return elecchartcoreJNI.stTVCFGEODATASETDESCR_fOrigScale_get(swigCPtr,
				this);
	}

	public void setFMinLat(double value) {
		elecchartcoreJNI.stTVCFGEODATASETDESCR_fMinLat_set(swigCPtr, this,
				value);
	}

	public double getFMinLat() {
		return elecchartcoreJNI.stTVCFGEODATASETDESCR_fMinLat_get(swigCPtr,
				this);
	}

	public void setFMaxLat(double value) {
		elecchartcoreJNI.stTVCFGEODATASETDESCR_fMaxLat_set(swigCPtr, this,
				value);
	}

	public double getFMaxLat() {
		return elecchartcoreJNI.stTVCFGEODATASETDESCR_fMaxLat_get(swigCPtr,
				this);
	}

	public void setFMinLong(double value) {
		elecchartcoreJNI.stTVCFGEODATASETDESCR_fMinLong_set(swigCPtr, this,
				value);
	}

	public double getFMinLong() {
		return elecchartcoreJNI.stTVCFGEODATASETDESCR_fMinLong_get(swigCPtr,
				this);
	}

	public void setFMaxLong(double value) {
		elecchartcoreJNI.stTVCFGEODATASETDESCR_fMaxLong_set(swigCPtr, this,
				value);
	}

	public double getFMaxLong() {
		return elecchartcoreJNI.stTVCFGEODATASETDESCR_fMaxLong_get(swigCPtr,
				this);
	}

	public void setFCorrectLat(double value) {
		elecchartcoreJNI.stTVCFGEODATASETDESCR_fCorrectLat_set(swigCPtr, this,
				value);
	}

	public double getFCorrectLat() {
		return elecchartcoreJNI.stTVCFGEODATASETDESCR_fCorrectLat_get(swigCPtr,
				this);
	}

	public void setFCorrectLong(double value) {
		elecchartcoreJNI.stTVCFGEODATASETDESCR_fCorrectLong_set(swigCPtr, this,
				value);
	}

	public double getFCorrectLong() {
		return elecchartcoreJNI.stTVCFGEODATASETDESCR_fCorrectLong_get(
				swigCPtr, this);
	}

	public void setBDelFlag(short value) {
		elecchartcoreJNI.stTVCFGEODATASETDESCR_bDelFlag_set(swigCPtr, this,
				value);
	}

	public short getBDelFlag() {
		return elecchartcoreJNI.stTVCFGEODATASETDESCR_bDelFlag_get(swigCPtr,
				this);
	}

	public void setBIsDisplay(short value) {
		elecchartcoreJNI.stTVCFGEODATASETDESCR_bIsDisplay_set(swigCPtr, this,
				value);
	}

	public short getBIsDisplay() {
		return elecchartcoreJNI.stTVCFGEODATASETDESCR_bIsDisplay_get(swigCPtr,
				this);
	}

	public stTVCFGEODATASETDESCR() {
		this(elecchartcoreJNI.new_stTVCFGEODATASETDESCR(), true);
	}

}
