/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stTWOINDEX {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stTWOINDEX(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stTWOINDEX obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stTWOINDEX(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setNGeometryNum(int value) {
		elecchartcoreJNI.stTWOINDEX_nGeometryNum_set(swigCPtr, this, value);
	}

	public int getNGeometryNum() {
		return elecchartcoreJNI.stTWOINDEX_nGeometryNum_get(swigCPtr, this);
	}

	public void setNShapeType(int value) {
		elecchartcoreJNI.stTWOINDEX_nShapeType_set(swigCPtr, this, value);
	}

	public int getNShapeType() {
		return elecchartcoreJNI.stTWOINDEX_nShapeType_get(swigCPtr, this);
	}

	public void setLMinX(int value) {
		elecchartcoreJNI.stTWOINDEX_lMinX_set(swigCPtr, this, value);
	}

	public int getLMinX() {
		return elecchartcoreJNI.stTWOINDEX_lMinX_get(swigCPtr, this);
	}

	public void setLMinY(int value) {
		elecchartcoreJNI.stTWOINDEX_lMinY_set(swigCPtr, this, value);
	}

	public int getLMinY() {
		return elecchartcoreJNI.stTWOINDEX_lMinY_get(swigCPtr, this);
	}

	public void setLMaxX(int value) {
		elecchartcoreJNI.stTWOINDEX_lMaxX_set(swigCPtr, this, value);
	}

	public int getLMaxX() {
		return elecchartcoreJNI.stTWOINDEX_lMaxX_get(swigCPtr, this);
	}

	public void setLMaxY(int value) {
		elecchartcoreJNI.stTWOINDEX_lMaxY_set(swigCPtr, this, value);
	}

	public int getLMaxY() {
		return elecchartcoreJNI.stTWOINDEX_lMaxY_get(swigCPtr, this);
	}

	public void setNGeometryOffset(int value) {
		elecchartcoreJNI.stTWOINDEX_nGeometryOffset_set(swigCPtr, this, value);
	}

	public int getNGeometryOffset() {
		return elecchartcoreJNI.stTWOINDEX_nGeometryOffset_get(swigCPtr, this);
	}

	public void setNGeometryLenth(int value) {
		elecchartcoreJNI.stTWOINDEX_nGeometryLenth_set(swigCPtr, this, value);
	}

	public int getNGeometryLenth() {
		return elecchartcoreJNI.stTWOINDEX_nGeometryLenth_get(swigCPtr, this);
	}

	public void setNClassCount(int value) {
		elecchartcoreJNI.stTWOINDEX_nClassCount_set(swigCPtr, this, value);
	}

	public int getNClassCount() {
		return elecchartcoreJNI.stTWOINDEX_nClassCount_get(swigCPtr, this);
	}

	public void setNClassPos(int value) {
		elecchartcoreJNI.stTWOINDEX_nClassPos_set(swigCPtr, this, value);
	}

	public int getNClassPos() {
		return elecchartcoreJNI.stTWOINDEX_nClassPos_get(swigCPtr, this);
	}

	public stTWOINDEX() {
		this(elecchartcoreJNI.new_stTWOINDEX(), true);
	}

}
