/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stUAIS_AIBBM {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stUAIS_AIBBM(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stUAIS_AIBBM obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stUAIS_AIBBM(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setNNum(int value) {
		elecchartcoreJNI.stUAIS_AIBBM_nNum_set(swigCPtr, this, value);
	}

	public int getNNum() {
		return elecchartcoreJNI.stUAIS_AIBBM_nNum_get(swigCPtr, this);
	}

	public void setNNO(int value) {
		elecchartcoreJNI.stUAIS_AIBBM_nNO_set(swigCPtr, this, value);
	}

	public int getNNO() {
		return elecchartcoreJNI.stUAIS_AIBBM_nNO_get(swigCPtr, this);
	}

	public void setNserialNO(int value) {
		elecchartcoreJNI.stUAIS_AIBBM_nserialNO_set(swigCPtr, this, value);
	}

	public int getNserialNO() {
		return elecchartcoreJNI.stUAIS_AIBBM_nserialNO_get(swigCPtr, this);
	}

	public void setNchannel(int value) {
		elecchartcoreJNI.stUAIS_AIBBM_nchannel_set(swigCPtr, this, value);
	}

	public int getNchannel() {
		return elecchartcoreJNI.stUAIS_AIBBM_nchannel_get(swigCPtr, this);
	}

	public void setMsgid(int value) {
		elecchartcoreJNI.stUAIS_AIBBM_msgid_set(swigCPtr, this, value);
	}

	public int getMsgid() {
		return elecchartcoreJNI.stUAIS_AIBBM_msgid_get(swigCPtr, this);
	}

	public void setSzText(String value) {
		elecchartcoreJNI.stUAIS_AIBBM_szText_set(swigCPtr, this, value);
	}

	public String getSzText() {
		return elecchartcoreJNI.stUAIS_AIBBM_szText_get(swigCPtr, this);
	}

	public void setFillbit(int value) {
		elecchartcoreJNI.stUAIS_AIBBM_fillbit_set(swigCPtr, this, value);
	}

	public int getFillbit() {
		return elecchartcoreJNI.stUAIS_AIBBM_fillbit_get(swigCPtr, this);
	}

	public void setState(int value) {
		elecchartcoreJNI.stUAIS_AIBBM_state_set(swigCPtr, this, value);
	}

	public int getState() {
		return elecchartcoreJNI.stUAIS_AIBBM_state_get(swigCPtr, this);
	}

	public stUAIS_AIBBM() {
		this(elecchartcoreJNI.new_stUAIS_AIBBM(), true);
	}

}
