/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stUAIS_AIAIR {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stUAIS_AIAIR(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stUAIS_AIAIR obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stUAIS_AIAIR(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setMmsi1(int value) {
		elecchartcoreJNI.stUAIS_AIAIR_mmsi1_set(swigCPtr, this, value);
	}

	public int getMmsi1() {
		return elecchartcoreJNI.stUAIS_AIAIR_mmsi1_get(swigCPtr, this);
	}

	public void setMsgid11(int value) {
		elecchartcoreJNI.stUAIS_AIAIR_msgid11_set(swigCPtr, this, value);
	}

	public int getMsgid11() {
		return elecchartcoreJNI.stUAIS_AIAIR_msgid11_get(swigCPtr, this);
	}

	public void setMsgSub11(int value) {
		elecchartcoreJNI.stUAIS_AIAIR_msgSub11_set(swigCPtr, this, value);
	}

	public int getMsgSub11() {
		return elecchartcoreJNI.stUAIS_AIAIR_msgSub11_get(swigCPtr, this);
	}

	public void setMsgid12(int value) {
		elecchartcoreJNI.stUAIS_AIAIR_msgid12_set(swigCPtr, this, value);
	}

	public int getMsgid12() {
		return elecchartcoreJNI.stUAIS_AIAIR_msgid12_get(swigCPtr, this);
	}

	public void setMsgsub12(int value) {
		elecchartcoreJNI.stUAIS_AIAIR_msgsub12_set(swigCPtr, this, value);
	}

	public int getMsgsub12() {
		return elecchartcoreJNI.stUAIS_AIAIR_msgsub12_get(swigCPtr, this);
	}

	public void setMmsi2(int value) {
		elecchartcoreJNI.stUAIS_AIAIR_mmsi2_set(swigCPtr, this, value);
	}

	public int getMmsi2() {
		return elecchartcoreJNI.stUAIS_AIAIR_mmsi2_get(swigCPtr, this);
	}

	public void setMsgid2(int value) {
		elecchartcoreJNI.stUAIS_AIAIR_msgid2_set(swigCPtr, this, value);
	}

	public int getMsgid2() {
		return elecchartcoreJNI.stUAIS_AIAIR_msgid2_get(swigCPtr, this);
	}

	public void setMsgidsub2(int value) {
		elecchartcoreJNI.stUAIS_AIAIR_msgidsub2_set(swigCPtr, this, value);
	}

	public int getMsgidsub2() {
		return elecchartcoreJNI.stUAIS_AIAIR_msgidsub2_get(swigCPtr, this);
	}

	public stUAIS_AIAIR() {
		this(elecchartcoreJNI.new_stUAIS_AIAIR(), true);
	}

}
