/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stUAIS_AIVSD {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stUAIS_AIVSD(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stUAIS_AIVSD obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stUAIS_AIVSD(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setCargotype(int value) {
		elecchartcoreJNI.stUAIS_AIVSD_cargotype_set(swigCPtr, this, value);
	}

	public int getCargotype() {
		return elecchartcoreJNI.stUAIS_AIVSD_cargotype_get(swigCPtr, this);
	}

	public void setDraught(int value) {
		elecchartcoreJNI.stUAIS_AIVSD_draught_set(swigCPtr, this, value);
	}

	public int getDraught() {
		return elecchartcoreJNI.stUAIS_AIVSD_draught_get(swigCPtr, this);
	}

	public void setPerson(int value) {
		elecchartcoreJNI.stUAIS_AIVSD_person_set(swigCPtr, this, value);
	}

	public int getPerson() {
		return elecchartcoreJNI.stUAIS_AIVSD_person_get(swigCPtr, this);
	}

	public void setSzDest(String value) {
		elecchartcoreJNI.stUAIS_AIVSD_szDest_set(swigCPtr, this, value);
	}

	public String getSzDest() {
		return elecchartcoreJNI.stUAIS_AIVSD_szDest_get(swigCPtr, this);
	}

	public void setSzTime(String value) {
		elecchartcoreJNI.stUAIS_AIVSD_szTime_set(swigCPtr, this, value);
	}

	public String getSzTime() {
		return elecchartcoreJNI.stUAIS_AIVSD_szTime_get(swigCPtr, this);
	}

	public void setDay(int value) {
		elecchartcoreJNI.stUAIS_AIVSD_day_set(swigCPtr, this, value);
	}

	public int getDay() {
		return elecchartcoreJNI.stUAIS_AIVSD_day_get(swigCPtr, this);
	}

	public void setMonth(int value) {
		elecchartcoreJNI.stUAIS_AIVSD_month_set(swigCPtr, this, value);
	}

	public int getMonth() {
		return elecchartcoreJNI.stUAIS_AIVSD_month_get(swigCPtr, this);
	}

	public void setStatus(int value) {
		elecchartcoreJNI.stUAIS_AIVSD_status_set(swigCPtr, this, value);
	}

	public int getStatus() {
		return elecchartcoreJNI.stUAIS_AIVSD_status_get(swigCPtr, this);
	}

	public void setPflag(int value) {
		elecchartcoreJNI.stUAIS_AIVSD_pflag_set(swigCPtr, this, value);
	}

	public int getPflag() {
		return elecchartcoreJNI.stUAIS_AIVSD_pflag_get(swigCPtr, this);
	}

	public stUAIS_AIVSD() {
		this(elecchartcoreJNI.new_stUAIS_AIVSD(), true);
	}

}
