/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stUAIS_AIVDM {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stUAIS_AIVDM(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stUAIS_AIVDM obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stUAIS_AIVDM(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setNNum(int value) {
		elecchartcoreJNI.stUAIS_AIVDM_nNum_set(swigCPtr, this, value);
	}

	public int getNNum() {
		return elecchartcoreJNI.stUAIS_AIVDM_nNum_get(swigCPtr, this);
	}

	public void setNNo(int value) {
		elecchartcoreJNI.stUAIS_AIVDM_nNo_set(swigCPtr, this, value);
	}

	public int getNNo() {
		return elecchartcoreJNI.stUAIS_AIVDM_nNo_get(swigCPtr, this);
	}

	public void setNSerial(int value) {
		elecchartcoreJNI.stUAIS_AIVDM_nSerial_set(swigCPtr, this, value);
	}

	public int getNSerial() {
		return elecchartcoreJNI.stUAIS_AIVDM_nSerial_get(swigCPtr, this);
	}

	public void setCchannel(char value) {
		elecchartcoreJNI.stUAIS_AIVDM_cchannel_set(swigCPtr, this, value);
	}

	public char getCchannel() {
		return elecchartcoreJNI.stUAIS_AIVDM_cchannel_get(swigCPtr, this);
	}

	public void setNmsgID(int value) {
		elecchartcoreJNI.stUAIS_AIVDM_nmsgID_set(swigCPtr, this, value);
	}

	public int getNmsgID() {
		return elecchartcoreJNI.stUAIS_AIVDM_nmsgID_get(swigCPtr, this);
	}

	public void setMsg123(stBODY_UAIS_MESSAGE_01 value) {
		elecchartcoreJNI.stUAIS_AIVDM_msg123_set(swigCPtr, this,
				stBODY_UAIS_MESSAGE_01.getCPtr(value), value);
	}

	public stBODY_UAIS_MESSAGE_01 getMsg123() {
		long cPtr = elecchartcoreJNI.stUAIS_AIVDM_msg123_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stBODY_UAIS_MESSAGE_01(cPtr, false);
	}

	public void setMsg4(stBODY_UAIS_MESSAGE_04 value) {
		elecchartcoreJNI.stUAIS_AIVDM_msg4_set(swigCPtr, this,
				stBODY_UAIS_MESSAGE_04.getCPtr(value), value);
	}

	public stBODY_UAIS_MESSAGE_04 getMsg4() {
		long cPtr = elecchartcoreJNI.stUAIS_AIVDM_msg4_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stBODY_UAIS_MESSAGE_04(cPtr, false);
	}

	public void setMsg5(stBODY_UAIS_MESSAGE_05 value) {
		elecchartcoreJNI.stUAIS_AIVDM_msg5_set(swigCPtr, this,
				stBODY_UAIS_MESSAGE_05.getCPtr(value), value);
	}

	public stBODY_UAIS_MESSAGE_05 getMsg5() {
		long cPtr = elecchartcoreJNI.stUAIS_AIVDM_msg5_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stBODY_UAIS_MESSAGE_05(cPtr, false);
	}

	public void setMsg6(stBODY_UAIS_MESSAGE_06 value) {
		elecchartcoreJNI.stUAIS_AIVDM_msg6_set(swigCPtr, this,
				stBODY_UAIS_MESSAGE_06.getCPtr(value), value);
	}

	public stBODY_UAIS_MESSAGE_06 getMsg6() {
		long cPtr = elecchartcoreJNI.stUAIS_AIVDM_msg6_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stBODY_UAIS_MESSAGE_06(cPtr, false);
	}

	public void setMsg7(stBODY_UAIS_MESSAGE_07 value) {
		elecchartcoreJNI.stUAIS_AIVDM_msg7_set(swigCPtr, this,
				stBODY_UAIS_MESSAGE_07.getCPtr(value), value);
	}

	public stBODY_UAIS_MESSAGE_07 getMsg7() {
		long cPtr = elecchartcoreJNI.stUAIS_AIVDM_msg7_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stBODY_UAIS_MESSAGE_07(cPtr, false);
	}

	public void setMsg8(stBODY_UAIS_MESSAGE_08 value) {
		elecchartcoreJNI.stUAIS_AIVDM_msg8_set(swigCPtr, this,
				stBODY_UAIS_MESSAGE_08.getCPtr(value), value);
	}

	public stBODY_UAIS_MESSAGE_08 getMsg8() {
		long cPtr = elecchartcoreJNI.stUAIS_AIVDM_msg8_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stBODY_UAIS_MESSAGE_08(cPtr, false);
	}

	public void setMsg9(stBODY_UAIS_MESSAGE_09 value) {
		elecchartcoreJNI.stUAIS_AIVDM_msg9_set(swigCPtr, this,
				stBODY_UAIS_MESSAGE_09.getCPtr(value), value);
	}

	public stBODY_UAIS_MESSAGE_09 getMsg9() {
		long cPtr = elecchartcoreJNI.stUAIS_AIVDM_msg9_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stBODY_UAIS_MESSAGE_09(cPtr, false);
	}

	public void setMsg10(stBODY_UAIS_MESSAGE_10 value) {
		elecchartcoreJNI.stUAIS_AIVDM_msg10_set(swigCPtr, this,
				stBODY_UAIS_MESSAGE_10.getCPtr(value), value);
	}

	public stBODY_UAIS_MESSAGE_10 getMsg10() {
		long cPtr = elecchartcoreJNI.stUAIS_AIVDM_msg10_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stBODY_UAIS_MESSAGE_10(cPtr, false);
	}

	public void setMsg12(stBODY_UAIS_MESSAGE_12 value) {
		elecchartcoreJNI.stUAIS_AIVDM_msg12_set(swigCPtr, this,
				stBODY_UAIS_MESSAGE_12.getCPtr(value), value);
	}

	public stBODY_UAIS_MESSAGE_12 getMsg12() {
		long cPtr = elecchartcoreJNI.stUAIS_AIVDM_msg12_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stBODY_UAIS_MESSAGE_12(cPtr, false);
	}

	public void setMsg13(stBODY_UAIS_MESSAGE_13 value) {
		elecchartcoreJNI.stUAIS_AIVDM_msg13_set(swigCPtr, this,
				stBODY_UAIS_MESSAGE_13.getCPtr(value), value);
	}

	public stBODY_UAIS_MESSAGE_13 getMsg13() {
		long cPtr = elecchartcoreJNI.stUAIS_AIVDM_msg13_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stBODY_UAIS_MESSAGE_13(cPtr, false);
	}

	public void setMsg14(stBODY_UAIS_MESSAGE_14 value) {
		elecchartcoreJNI.stUAIS_AIVDM_msg14_set(swigCPtr, this,
				stBODY_UAIS_MESSAGE_14.getCPtr(value), value);
	}

	public stBODY_UAIS_MESSAGE_14 getMsg14() {
		long cPtr = elecchartcoreJNI.stUAIS_AIVDM_msg14_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stBODY_UAIS_MESSAGE_14(cPtr, false);
	}

	public void setMsg15(stBODY_UAIS_MESSAGE_15 value) {
		elecchartcoreJNI.stUAIS_AIVDM_msg15_set(swigCPtr, this,
				stBODY_UAIS_MESSAGE_15.getCPtr(value), value);
	}

	public stBODY_UAIS_MESSAGE_15 getMsg15() {
		long cPtr = elecchartcoreJNI.stUAIS_AIVDM_msg15_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stBODY_UAIS_MESSAGE_15(cPtr, false);
	}

	public void setMsg16(stBODY_UAIS_MESSAGE_16 value) {
		elecchartcoreJNI.stUAIS_AIVDM_msg16_set(swigCPtr, this,
				stBODY_UAIS_MESSAGE_16.getCPtr(value), value);
	}

	public stBODY_UAIS_MESSAGE_16 getMsg16() {
		long cPtr = elecchartcoreJNI.stUAIS_AIVDM_msg16_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stBODY_UAIS_MESSAGE_16(cPtr, false);
	}

	public void setMsg17(stBODY_UAIS_MESSAGE_17 value) {
		elecchartcoreJNI.stUAIS_AIVDM_msg17_set(swigCPtr, this,
				stBODY_UAIS_MESSAGE_17.getCPtr(value), value);
	}

	public stBODY_UAIS_MESSAGE_17 getMsg17() {
		long cPtr = elecchartcoreJNI.stUAIS_AIVDM_msg17_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stBODY_UAIS_MESSAGE_17(cPtr, false);
	}

	public void setMsg18(stBODY_UAIS_MESSAGE_18 value) {
		elecchartcoreJNI.stUAIS_AIVDM_msg18_set(swigCPtr, this,
				stBODY_UAIS_MESSAGE_18.getCPtr(value), value);
	}

	public stBODY_UAIS_MESSAGE_18 getMsg18() {
		long cPtr = elecchartcoreJNI.stUAIS_AIVDM_msg18_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stBODY_UAIS_MESSAGE_18(cPtr, false);
	}

	public void setMsg19(stBODY_UAIS_MESSAGE_19 value) {
		elecchartcoreJNI.stUAIS_AIVDM_msg19_set(swigCPtr, this,
				stBODY_UAIS_MESSAGE_19.getCPtr(value), value);
	}

	public stBODY_UAIS_MESSAGE_19 getMsg19() {
		long cPtr = elecchartcoreJNI.stUAIS_AIVDM_msg19_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stBODY_UAIS_MESSAGE_19(cPtr, false);
	}

	public void setMsg20(stBODY_UAIS_MESSAGE_20 value) {
		elecchartcoreJNI.stUAIS_AIVDM_msg20_set(swigCPtr, this,
				stBODY_UAIS_MESSAGE_20.getCPtr(value), value);
	}

	public stBODY_UAIS_MESSAGE_20 getMsg20() {
		long cPtr = elecchartcoreJNI.stUAIS_AIVDM_msg20_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stBODY_UAIS_MESSAGE_20(cPtr, false);
	}

	public void setMsg21(stBODY_UAIS_MESSAGE_21 value) {
		elecchartcoreJNI.stUAIS_AIVDM_msg21_set(swigCPtr, this,
				stBODY_UAIS_MESSAGE_21.getCPtr(value), value);
	}

	public stBODY_UAIS_MESSAGE_21 getMsg21() {
		long cPtr = elecchartcoreJNI.stUAIS_AIVDM_msg21_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stBODY_UAIS_MESSAGE_21(cPtr, false);
	}

	public void setMsg22(stBODY_UAIS_MESSAGE_22 value) {
		elecchartcoreJNI.stUAIS_AIVDM_msg22_set(swigCPtr, this,
				stBODY_UAIS_MESSAGE_22.getCPtr(value), value);
	}

	public stBODY_UAIS_MESSAGE_22 getMsg22() {
		long cPtr = elecchartcoreJNI.stUAIS_AIVDM_msg22_get(swigCPtr, this);
		return (cPtr == 0) ? null : new stBODY_UAIS_MESSAGE_22(cPtr, false);
	}

	public void setNfillbit(int value) {
		elecchartcoreJNI.stUAIS_AIVDM_nfillbit_set(swigCPtr, this, value);
	}

	public int getNfillbit() {
		return elecchartcoreJNI.stUAIS_AIVDM_nfillbit_get(swigCPtr, this);
	}

	public void setUncheaksum(long value) {
		elecchartcoreJNI.stUAIS_AIVDM_uncheaksum_set(swigCPtr, this, value);
	}

	public long getUncheaksum() {
		return elecchartcoreJNI.stUAIS_AIVDM_uncheaksum_get(swigCPtr, this);
	}

	public stUAIS_AIVDM() {
		this(elecchartcoreJNI.new_stUAIS_AIVDM(), true);
	}

}
