/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stUAIS_AIABK {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stUAIS_AIABK(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stUAIS_AIABK obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stUAIS_AIABK(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setMmsi(int value) {
		elecchartcoreJNI.stUAIS_AIABK_mmsi_set(swigCPtr, this, value);
	}

	public int getMmsi() {
		return elecchartcoreJNI.stUAIS_AIABK_mmsi_get(swigCPtr, this);
	}

	public void setChannel(String value) {
		elecchartcoreJNI.stUAIS_AIABK_channel_set(swigCPtr, this, value);
	}

	public String getChannel() {
		return elecchartcoreJNI.stUAIS_AIABK_channel_get(swigCPtr, this);
	}

	public void setMsgid(int value) {
		elecchartcoreJNI.stUAIS_AIABK_msgid_set(swigCPtr, this, value);
	}

	public int getMsgid() {
		return elecchartcoreJNI.stUAIS_AIABK_msgid_get(swigCPtr, this);
	}

	public void setSerialNO(int value) {
		elecchartcoreJNI.stUAIS_AIABK_serialNO_set(swigCPtr, this, value);
	}

	public int getSerialNO() {
		return elecchartcoreJNI.stUAIS_AIABK_serialNO_get(swigCPtr, this);
	}

	public void setType(int value) {
		elecchartcoreJNI.stUAIS_AIABK_type_set(swigCPtr, this, value);
	}

	public int getType() {
		return elecchartcoreJNI.stUAIS_AIABK_type_get(swigCPtr, this);
	}

	public void setCheaksum(long value) {
		elecchartcoreJNI.stUAIS_AIABK_cheaksum_set(swigCPtr, this, value);
	}

	public long getCheaksum() {
		return elecchartcoreJNI.stUAIS_AIABK_cheaksum_get(swigCPtr, this);
	}

	public stUAIS_AIABK() {
		this(elecchartcoreJNI.new_stUAIS_AIABK(), true);
	}

}
