/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stUTC_TIME {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stUTC_TIME(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stUTC_TIME obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stUTC_TIME(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setHour(int value) {
		elecchartcoreJNI.stUTC_TIME_hour_set(swigCPtr, this, value);
	}

	public int getHour() {
		return elecchartcoreJNI.stUTC_TIME_hour_get(swigCPtr, this);
	}

	public void setMinute(int value) {
		elecchartcoreJNI.stUTC_TIME_minute_set(swigCPtr, this, value);
	}

	public int getMinute() {
		return elecchartcoreJNI.stUTC_TIME_minute_get(swigCPtr, this);
	}

	public void setSecond(int value) {
		elecchartcoreJNI.stUTC_TIME_second_set(swigCPtr, this, value);
	}

	public int getSecond() {
		return elecchartcoreJNI.stUTC_TIME_second_get(swigCPtr, this);
	}

	public stUTC_TIME() {
		this(elecchartcoreJNI.new_stUTC_TIME(), true);
	}

}
