/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stUTC_DATE {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stUTC_DATE(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stUTC_DATE obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stUTC_DATE(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setYear(int value) {
		elecchartcoreJNI.stUTC_DATE_year_set(swigCPtr, this, value);
	}

	public int getYear() {
		return elecchartcoreJNI.stUTC_DATE_year_get(swigCPtr, this);
	}

	public void setMonth(int value) {
		elecchartcoreJNI.stUTC_DATE_month_set(swigCPtr, this, value);
	}

	public int getMonth() {
		return elecchartcoreJNI.stUTC_DATE_month_get(swigCPtr, this);
	}

	public void setDay(int value) {
		elecchartcoreJNI.stUTC_DATE_day_set(swigCPtr, this, value);
	}

	public int getDay() {
		return elecchartcoreJNI.stUTC_DATE_day_get(swigCPtr, this);
	}

	public stUTC_DATE() {
		this(elecchartcoreJNI.new_stUTC_DATE(), true);
	}

}
