/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stVCFGEOOBJECTINDEX {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stVCFGEOOBJECTINDEX(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stVCFGEOOBJECTINDEX obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stVCFGEOOBJECTINDEX(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setNLayerCode(int value) {
		elecchartcoreJNI.stVCFGEOOBJECTINDEX_nLayerCode_set(swigCPtr, this,
				value);
	}

	public int getNLayerCode() {
		return elecchartcoreJNI.stVCFGEOOBJECTINDEX_nLayerCode_get(swigCPtr,
				this);
	}

	public void setNPrim(int value) {
		elecchartcoreJNI.stVCFGEOOBJECTINDEX_nPrim_set(swigCPtr, this, value);
	}

	public int getNPrim() {
		return elecchartcoreJNI.stVCFGEOOBJECTINDEX_nPrim_get(swigCPtr, this);
	}

	public void setNGeoLayer(int value) {
		elecchartcoreJNI.stVCFGEOOBJECTINDEX_nGeoLayer_set(swigCPtr, this,
				value);
	}

	public int getNGeoLayer() {
		return elecchartcoreJNI.stVCFGEOOBJECTINDEX_nGeoLayer_get(swigCPtr,
				this);
	}

	public void setNObjectId(int value) {
		elecchartcoreJNI.stVCFGEOOBJECTINDEX_nObjectId_set(swigCPtr, this,
				value);
	}

	public int getNObjectId() {
		return elecchartcoreJNI.stVCFGEOOBJECTINDEX_nObjectId_get(swigCPtr,
				this);
	}

	public void setLObjectFC(int value) {
		elecchartcoreJNI.stVCFGEOOBJECTINDEX_lObjectFC_set(swigCPtr, this,
				value);
	}

	public int getLObjectFC() {
		return elecchartcoreJNI.stVCFGEOOBJECTINDEX_lObjectFC_get(swigCPtr,
				this);
	}

	public void setLObjectOffset(int value) {
		elecchartcoreJNI.stVCFGEOOBJECTINDEX_lObjectOffset_set(swigCPtr, this,
				value);
	}

	public int getLObjectOffset() {
		return elecchartcoreJNI.stVCFGEOOBJECTINDEX_lObjectOffset_get(swigCPtr,
				this);
	}

	public void setNObjectLen(int value) {
		elecchartcoreJNI.stVCFGEOOBJECTINDEX_nObjectLen_set(swigCPtr, this,
				value);
	}

	public int getNObjectLen() {
		return elecchartcoreJNI.stVCFGEOOBJECTINDEX_nObjectLen_get(swigCPtr,
				this);
	}

	public stVCFGEOOBJECTINDEX() {
		this(elecchartcoreJNI.new_stVCFGEOOBJECTINDEX(), true);
	}

}
