/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stVCFDISPLAYPRIO {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stVCFDISPLAYPRIO(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stVCFDISPLAYPRIO obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stVCFDISPLAYPRIO(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setNDspPrioNo(int value) {
		elecchartcoreJNI.stVCFDISPLAYPRIO_nDspPrioNo_set(swigCPtr, this, value);
	}

	public int getNDspPrioNo() {
		return elecchartcoreJNI.stVCFDISPLAYPRIO_nDspPrioNo_get(swigCPtr, this);
	}

	public void setNSmlLayerNo(int value) {
		elecchartcoreJNI
				.stVCFDISPLAYPRIO_nSmlLayerNo_set(swigCPtr, this, value);
	}

	public int getNSmlLayerNo() {
		return elecchartcoreJNI
				.stVCFDISPLAYPRIO_nSmlLayerNo_get(swigCPtr, this);
	}

	public void setSzSmLAncroy(String value) {
		elecchartcoreJNI
				.stVCFDISPLAYPRIO_szSmLAncroy_set(swigCPtr, this, value);
	}

	public String getSzSmLAncroy() {
		return elecchartcoreJNI
				.stVCFDISPLAYPRIO_szSmLAncroy_get(swigCPtr, this);
	}

	public void setNBigLayerNo(int value) {
		elecchartcoreJNI
				.stVCFDISPLAYPRIO_nBigLayerNo_set(swigCPtr, this, value);
	}

	public int getNBigLayerNo() {
		return elecchartcoreJNI
				.stVCFDISPLAYPRIO_nBigLayerNo_get(swigCPtr, this);
	}

	public void setNShapeType(int value) {
		elecchartcoreJNI.stVCFDISPLAYPRIO_nShapeType_set(swigCPtr, this, value);
	}

	public int getNShapeType() {
		return elecchartcoreJNI.stVCFDISPLAYPRIO_nShapeType_get(swigCPtr, this);
	}

	public void setNIMOCategory(int value) {
		elecchartcoreJNI.stVCFDISPLAYPRIO_nIMOCategory_set(swigCPtr, this,
				value);
	}

	public int getNIMOCategory() {
		return elecchartcoreJNI.stVCFDISPLAYPRIO_nIMOCategory_get(swigCPtr,
				this);
	}

	public stVCFDISPLAYPRIO() {
		this(elecchartcoreJNI.new_stVCFDISPLAYPRIO(), true);
	}

}
