/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stVCFGEODATASETDESCR {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stVCFGEODATASETDESCR(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stVCFGEODATASETDESCR obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stVCFGEODATASETDESCR(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setSzChartCode(String value) {
		elecchartcoreJNI.stVCFGEODATASETDESCR_szChartCode_set(swigCPtr, this,
				value);
	}

	public String getSzChartCode() {
		return elecchartcoreJNI.stVCFGEODATASETDESCR_szChartCode_get(swigCPtr,
				this);
	}

	public void setSzChartName(String value) {
		elecchartcoreJNI.stVCFGEODATASETDESCR_szChartName_set(swigCPtr, this,
				value);
	}

	public String getSzChartName() {
		return elecchartcoreJNI.stVCFGEODATASETDESCR_szChartName_get(swigCPtr,
				this);
	}

	public void setSzHGeodeticDatum(String value) {
		elecchartcoreJNI.stVCFGEODATASETDESCR_szHGeodeticDatum_set(swigCPtr,
				this, value);
	}

	public String getSzHGeodeticDatum() {
		return elecchartcoreJNI.stVCFGEODATASETDESCR_szHGeodeticDatum_get(
				swigCPtr, this);
	}

	public void setFMidLatitude(double value) {
		elecchartcoreJNI.stVCFGEODATASETDESCR_fMidLatitude_set(swigCPtr, this,
				value);
	}

	public double getFMidLatitude() {
		return elecchartcoreJNI.stVCFGEODATASETDESCR_fMidLatitude_get(swigCPtr,
				this);
	}

	public void setFOrigScale(double value) {
		elecchartcoreJNI.stVCFGEODATASETDESCR_fOrigScale_set(swigCPtr, this,
				value);
	}

	public double getFOrigScale() {
		return elecchartcoreJNI.stVCFGEODATASETDESCR_fOrigScale_get(swigCPtr,
				this);
	}

	public void setFMinLat(double value) {
		elecchartcoreJNI
				.stVCFGEODATASETDESCR_fMinLat_set(swigCPtr, this, value);
	}

	public double getFMinLat() {
		return elecchartcoreJNI
				.stVCFGEODATASETDESCR_fMinLat_get(swigCPtr, this);
	}

	public void setFMaxLat(double value) {
		elecchartcoreJNI
				.stVCFGEODATASETDESCR_fMaxLat_set(swigCPtr, this, value);
	}

	public double getFMaxLat() {
		return elecchartcoreJNI
				.stVCFGEODATASETDESCR_fMaxLat_get(swigCPtr, this);
	}

	public void setFMinLong(double value) {
		elecchartcoreJNI.stVCFGEODATASETDESCR_fMinLong_set(swigCPtr, this,
				value);
	}

	public double getFMinLong() {
		return elecchartcoreJNI.stVCFGEODATASETDESCR_fMinLong_get(swigCPtr,
				this);
	}

	public void setFMaxLong(double value) {
		elecchartcoreJNI.stVCFGEODATASETDESCR_fMaxLong_set(swigCPtr, this,
				value);
	}

	public double getFMaxLong() {
		return elecchartcoreJNI.stVCFGEODATASETDESCR_fMaxLong_get(swigCPtr,
				this);
	}

	public void setFCorrectLat(double value) {
		elecchartcoreJNI.stVCFGEODATASETDESCR_fCorrectLat_set(swigCPtr, this,
				value);
	}

	public double getFCorrectLat() {
		return elecchartcoreJNI.stVCFGEODATASETDESCR_fCorrectLat_get(swigCPtr,
				this);
	}

	public void setFCorrectLong(double value) {
		elecchartcoreJNI.stVCFGEODATASETDESCR_fCorrectLong_set(swigCPtr, this,
				value);
	}

	public double getFCorrectLong() {
		return elecchartcoreJNI.stVCFGEODATASETDESCR_fCorrectLong_get(swigCPtr,
				this);
	}

	public void setBDelFlag(short value) {
		elecchartcoreJNI.stVCFGEODATASETDESCR_bDelFlag_set(swigCPtr, this,
				value);
	}

	public short getBDelFlag() {
		return elecchartcoreJNI.stVCFGEODATASETDESCR_bDelFlag_get(swigCPtr,
				this);
	}

	public void setBIsDisplay(short value) {
		elecchartcoreJNI.stVCFGEODATASETDESCR_bIsDisplay_set(swigCPtr, this,
				value);
	}

	public short getBIsDisplay() {
		return elecchartcoreJNI.stVCFGEODATASETDESCR_bIsDisplay_get(swigCPtr,
				this);
	}

	public stVCFGEODATASETDESCR() {
		this(elecchartcoreJNI.new_stVCFGEODATASETDESCR(), true);
	}

}
