/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stVCFCHARTGEODESCR {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stVCFCHARTGEODESCR(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stVCFCHARTGEODESCR obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stVCFCHARTGEODESCR(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setSzChartCode(String value) {
		elecchartcoreJNI.stVCFCHARTGEODESCR_szChartCode_set(swigCPtr, this,
				value);
	}

	public String getSzChartCode() {
		return elecchartcoreJNI.stVCFCHARTGEODESCR_szChartCode_get(swigCPtr,
				this);
	}

	public void setSzChartName(String value) {
		elecchartcoreJNI.stVCFCHARTGEODESCR_szChartName_set(swigCPtr, this,
				value);
	}

	public String getSzChartName() {
		return elecchartcoreJNI.stVCFCHARTGEODESCR_szChartName_get(swigCPtr,
				this);
	}

	public void setSzHGeodeticDatum(String value) {
		elecchartcoreJNI.stVCFCHARTGEODESCR_szHGeodeticDatum_set(swigCPtr,
				this, value);
	}

	public String getSzHGeodeticDatum() {
		return elecchartcoreJNI.stVCFCHARTGEODESCR_szHGeodeticDatum_get(
				swigCPtr, this);
	}

	public void setFMidLatitude(double value) {
		elecchartcoreJNI.stVCFCHARTGEODESCR_fMidLatitude_set(swigCPtr, this,
				value);
	}

	public double getFMidLatitude() {
		return elecchartcoreJNI.stVCFCHARTGEODESCR_fMidLatitude_get(swigCPtr,
				this);
	}

	public void setFOrigScale(double value) {
		elecchartcoreJNI.stVCFCHARTGEODESCR_fOrigScale_set(swigCPtr, this,
				value);
	}

	public double getFOrigScale() {
		return elecchartcoreJNI.stVCFCHARTGEODESCR_fOrigScale_get(swigCPtr,
				this);
	}

	public void setFMinLat(double value) {
		elecchartcoreJNI.stVCFCHARTGEODESCR_fMinLat_set(swigCPtr, this, value);
	}

	public double getFMinLat() {
		return elecchartcoreJNI.stVCFCHARTGEODESCR_fMinLat_get(swigCPtr, this);
	}

	public void setFMaxLat(double value) {
		elecchartcoreJNI.stVCFCHARTGEODESCR_fMaxLat_set(swigCPtr, this, value);
	}

	public double getFMaxLat() {
		return elecchartcoreJNI.stVCFCHARTGEODESCR_fMaxLat_get(swigCPtr, this);
	}

	public void setFMinLong(double value) {
		elecchartcoreJNI.stVCFCHARTGEODESCR_fMinLong_set(swigCPtr, this, value);
	}

	public double getFMinLong() {
		return elecchartcoreJNI.stVCFCHARTGEODESCR_fMinLong_get(swigCPtr, this);
	}

	public void setFMaxLong(double value) {
		elecchartcoreJNI.stVCFCHARTGEODESCR_fMaxLong_set(swigCPtr, this, value);
	}

	public double getFMaxLong() {
		return elecchartcoreJNI.stVCFCHARTGEODESCR_fMaxLong_get(swigCPtr, this);
	}

	public stVCFCHARTGEODESCR() {
		this(elecchartcoreJNI.new_stVCFCHARTGEODESCR(), true);
	}

}
