/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public class stVCFLOOKUPTBITEM {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected stVCFLOOKUPTBITEM(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(stVCFLOOKUPTBITEM obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				elecchartcoreJNI.delete_stVCFLOOKUPTBITEM(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	public void setLRecordId(int value) {
		elecchartcoreJNI.stVCFLOOKUPTBITEM_lRecordId_set(swigCPtr, this, value);
	}

	public int getLRecordId() {
		return elecchartcoreJNI.stVCFLOOKUPTBITEM_lRecordId_get(swigCPtr, this);
	}

	public void setNLookTbType(int value) {
		elecchartcoreJNI.stVCFLOOKUPTBITEM_nLookTbType_set(swigCPtr, this,
				value);
	}

	public int getNLookTbType() {
		return elecchartcoreJNI.stVCFLOOKUPTBITEM_nLookTbType_get(swigCPtr,
				this);
	}

	public void setLFC(int value) {
		elecchartcoreJNI.stVCFLOOKUPTBITEM_lFC_set(swigCPtr, this, value);
	}

	public int getLFC() {
		return elecchartcoreJNI.stVCFLOOKUPTBITEM_lFC_get(swigCPtr, this);
	}

	public void setNSymbolId(int value) {
		elecchartcoreJNI.stVCFLOOKUPTBITEM_nSymbolId_set(swigCPtr, this, value);
	}

	public int getNSymbolId() {
		return elecchartcoreJNI.stVCFLOOKUPTBITEM_nSymbolId_get(swigCPtr, this);
	}

	public stVCFLOOKUPTBITEM() {
		this(elecchartcoreJNI.new_stVCFLOOKUPTBITEM(), true);
	}

}
