/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public final class xhfDrawBufferSwap {
	public final static xhfDrawBufferSwap XHFDBSCopyToShow = new xhfDrawBufferSwap(
			"XHFDBSCopyToShow", elecchartcoreJNI.XHFDBSCopyToShow_get());
	public final static xhfDrawBufferSwap XHFDBSShowToCopy = new xhfDrawBufferSwap(
			"XHFDBSShowToCopy");

	public final int swigValue() {
		return swigValue;
	}

	public String toString() {
		return swigName;
	}

	public static xhfDrawBufferSwap swigToEnum(int swigValue) {
		if (swigValue < swigValues.length && swigValue >= 0
				&& swigValues[swigValue].swigValue == swigValue)
			return swigValues[swigValue];
		for (int i = 0; i < swigValues.length; i++)
			if (swigValues[i].swigValue == swigValue)
				return swigValues[i];
		throw new IllegalArgumentException("No enum " + xhfDrawBufferSwap.class
				+ " with value " + swigValue);
	}

	private xhfDrawBufferSwap(String swigName) {
		this.swigName = swigName;
		this.swigValue = swigNext++;
	}

	private xhfDrawBufferSwap(String swigName, int swigValue) {
		this.swigName = swigName;
		this.swigValue = swigValue;
		swigNext = swigValue + 1;
	}

	private xhfDrawBufferSwap(String swigName, xhfDrawBufferSwap swigEnum) {
		this.swigName = swigName;
		this.swigValue = swigEnum.swigValue;
		swigNext = this.swigValue + 1;
	}

	private static xhfDrawBufferSwap[] swigValues = { XHFDBSCopyToShow,
			XHFDBSShowToCopy };
	private static int swigNext = 0;
	private final int swigValue;
	private final String swigName;
}
