/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xhf.project.chartcorejni;

public final class xhfDrawBufferType {
	public final static xhfDrawBufferType XHFDBShowBuffer = new xhfDrawBufferType(
			"XHFDBShowBuffer", elecchartcoreJNI.XHFDBShowBuffer_get());
	public final static xhfDrawBufferType XHFDBCopyBuffer = new xhfDrawBufferType(
			"XHFDBCopyBuffer");

	public final int swigValue() {
		return swigValue;
	}

	public String toString() {
		return swigName;
	}

	public static xhfDrawBufferType swigToEnum(int swigValue) {
		if (swigValue < swigValues.length && swigValue >= 0
				&& swigValues[swigValue].swigValue == swigValue)
			return swigValues[swigValue];
		for (int i = 0; i < swigValues.length; i++)
			if (swigValues[i].swigValue == swigValue)
				return swigValues[i];
		throw new IllegalArgumentException("No enum " + xhfDrawBufferType.class
				+ " with value " + swigValue);
	}

	private xhfDrawBufferType(String swigName) {
		this.swigName = swigName;
		this.swigValue = swigNext++;
	}

	private xhfDrawBufferType(String swigName, int swigValue) {
		this.swigName = swigName;
		this.swigValue = swigValue;
		swigNext = swigValue + 1;
	}

	private xhfDrawBufferType(String swigName, xhfDrawBufferType swigEnum) {
		this.swigName = swigName;
		this.swigValue = swigEnum.swigValue;
		swigNext = this.swigValue + 1;
	}

	private static xhfDrawBufferType[] swigValues = { XHFDBShowBuffer,
			XHFDBCopyBuffer };
	private static int swigNext = 0;
	private final int swigValue;
	private final String swigName;
}
